directive @system_token repeatable on OBJECT | FIELD_DEFINITION

directive @platform_token repeatable on OBJECT | FIELD_DEFINITION

directive @auth(requires: [Restriction] = []) repeatable on OBJECT | FIELD_DEFINITION

directive @service_capa(requires: [ServiceRestriction] = []) repeatable on OBJECT | FIELD_DEFINITION

scalar JSON

scalar Date

scalar Upload

enum FilterKey {
  label
  organization_id
  personal_space
  integration_type
  integration_subtype
  slug
  product_version
  manager_supported
}

enum LogicalOperator {
  AND
  OR
}

input Filter {
  key: FilterKey
  value: [String!]!
}

input LogicalFilterInput {
  leaf: Filter
  operator: LogicalOperator
  children: [LogicalFilterInput!]
}

type Success {
  success: Boolean!
}

type Query {
  updateOpenCTIManifest(tag: String): Success!
  organization(id: ID!): Organization
  organizations(first: Int = 50, after: ID, orderBy: OrganizationOrdering!, orderMode: OrderingMode!, searchTerm: String): OrganizationConnection!
  userOrganizations: [Organization!]!
  rolePortal(id: ID!): RolePortal
  rolesPortal: [RolePortal!]!
  seoCustomDashboardsByServiceSlug(serviceSlug: String): [CustomDashboard]
  seoCustomDashboardBySlug(slug: String): CustomDashboard
  customDashboards(first: Int!, after: ID, orderBy: DocumentOrdering!, orderMode: OrderingMode!, searchTerm: String, logicalFilters: LogicalFilterInput, serviceInstanceId: String): CustomDashboardConnection!
  customDashboard(id: ID, serviceInstanceId: ID): CustomDashboard
  deploymentRequests(first: Int!, after: ID, filters: [DeploymentRequestFilter!]): PlatformDeploymentRequestConnection!
  deploymentRequestsAvailable(platformIdentifier: PlatformIdentifier): [DeploymentAvailability!]!
  deploymentRequestsList(first: Int!, after: ID, filters: [DeploymentRequestFilter!], orderBy: DeploymentRequestOrdering!, orderMode: OrderingMode!, searchTerm: String): DeploymentRequestConnection!
  documentExists(documentName: String, service_instance_id: String): Boolean
  documents(first: Int!, after: ID, orderBy: DocumentOrdering!, orderMode: OrderingMode!, searchTerm: String, filters: [Filter!], logicalFilters: LogicalFilterInput, serviceInstanceId: String, parentsOnly: Boolean): DocumentConnection!
  document(documentId: ID, serviceInstanceId: ID): Document
  serviceGroups(serviceInstanceId: ID!): [ServiceGroup!]!
  integrations(first: Int!, after: ID, orderBy: DocumentOrdering!, orderMode: OrderingMode!, searchTerm: String, filters: [Filter!], logicalFilters: LogicalFilterInput, serviceInstanceId: String): IntegrationConnection!
  integration(id: ID, serviceInstanceId: ID): Integration
  publicIntegrations(slug: String!, first: Int!, after: ID, orderBy: DocumentOrdering!, orderMode: OrderingMode!, searchTerm: String, filters: [Filter!], logicalFilters: LogicalFilterInput, serviceInstanceId: String): IntegrationConnection!
  publicIntegrationsByServiceSlug(serviceSlug: String): [Integration]
  publicIntegrationBySlug(slug: String): Integration
  seoOpenAEVScenariosByServiceSlug(serviceSlug: String): [OpenAEVScenario]
  seoOpenAEVScenarioBySlug(slug: String): OpenAEVScenario
  openAEVScenarios(first: Int!, after: ID, orderBy: DocumentOrdering!, orderMode: OrderingMode!, searchTerm: String, logicalFilters: LogicalFilterInput, serviceInstanceId: String): OpenAEVScenarioConnection!
  openAEVScenario(id: ID, serviceInstanceId: ID): OpenAEVScenario
  openCTIPlatformRegistrationStatus(input: OpenCTIPlatformRegistrationStatusInput!): OpenCTIPlatformRegistrationStatusResponse! @deprecated(reason: "Use `refreshPlatformRegistrationConnectivityStatus` instead. This field is no longer used in the OpenCTI platform due to refactoring and the addition of a version value in the endpoint.")
  isPlatformRegistered(input: IsPlatformRegisteredInput!): IsPlatformRegisteredResponse!
  canUnregisterPlatform(input: CanUnregisterPlatformInput!): CanUnregisterResponse!
  registeredPlatform(input: RegisteredPlatformInput!): RegisteredPlatform
  registeredPlatforms(input: RegisteredPlatformsInput): [RegisteredPlatform!]!
  platformAssociatedOrganization(platformId: String!): Organization
  publicServiceInstances(first: Int!, after: ID, orderBy: ServiceInstanceOrdering!, orderMode: OrderingMode!): ServiceConnection!
  serviceInstances(first: Int!, after: ID, orderBy: ServiceInstanceOrdering!, orderMode: OrderingMode!, searchTerm: String, filters: [ServiceInstanceFilter!]): ServiceConnection!
  serviceInstanceLinksByTags(tags: [ServiceInstanceTag!]!): [SeoServiceInstance!]!
  serviceInstanceById(service_instance_id: ID): ServiceInstance
  serviceInstanceByIdWithSubscriptions(service_instance_id: ID): ServiceInstance
  subscribedServiceInstancesByIdentifier(identifier: ServiceDefinitionIdentifier!): [SubscribedServiceInstance!]!
  seoServiceInstances: [SeoServiceInstance!]!
  seoServiceInstance(slug: String!): SeoServiceInstance!
  labels(first: Int!, after: ID, orderBy: LabelOrdering!, orderMode: OrderingMode!, searchTerm: String, documentType: String): LabelConnection
  label(id: ID!): Label
  settings: Settings!
  subscriptionById(subscription_id: ID): SubscriptionModel
  userServiceOwned(first: Int!, after: ID, orderBy: UserServiceOrdering!, orderMode: OrderingMode!): UserServiceConnection
  serviceUsers(id: ID!, first: Int!, after: ID, orderBy: UserServiceOrdering!, orderMode: OrderingMode!): UserServiceConnection
  userServiceFromSubscription(first: Int!, after: ID, orderBy: UserServiceOrdering!, orderMode: OrderingMode!, subscription_id: ID!): UserServiceConnection
  me: User
  usersWithCapabilitiesInOrganization(input: UsersWithCapabilitiesInOrganizationInput!): [User!]!
  users(first: Int!, after: ID, orderBy: UserOrdering!, orderMode: OrderingMode!, searchTerm: String, filters: [Filter!]): UserConnection!
  pendingUsers(first: Int!, after: ID, orderBy: UserOrdering!, orderMode: OrderingMode!, searchTerm: String, filters: [Filter!]): UserConnection!
  userHasOrganizationWithSubscription: Boolean!
  node(id: ID!): Node
}

type Mutation {
  frontendErrorLog(message: String!, codeStack: String, componentStack: String): Boolean
  addOrganization(input: OrganizationInput!): Organization
  editOrganization(id: ID!, input: OrganizationInput!): Organization
  deleteOrganization(id: ID!): Organization
  createDeploymentRequest(input: CreateDeploymentRequestInput): DeploymentRequest!
  updateDeploymentRequest(input: UpdateDeploymentRequestInput!): PlatformDeploymentRequest!
  reorderDeploymentRequestInQueue(input: ReorderDeploymentRequestInQueueInput!): Success!
  cancelDeploymentRequest(deploymentRequestId: ID!, cancellationReason: String): DeploymentRequest
  adminCancelDeploymentRequest(deploymentRequestId: ID): DeploymentRequest
  updateDeploymentQuotaCapacity(input: UpdateDeploymentQuotaCapacityInput!): Success!
  createDocument(input: CreateDocumentInput!, metadata: [DocumentMetadata!]!, document: [Upload!]!, serviceInstanceId: String): Document!
  updateDocument(documentId: ID!, input: UpdateDocumentInput!, metadata: [DocumentMetadata!]!, document: [Upload!]!, updateDocument: Boolean!, images: [String!], serviceInstanceId: String): Document!
  deleteDocument(documentId: ID, service_instance_id: String, forceDelete: Boolean): Document!
  incrementShareNumberDocument(documentId: ID): Document!
  updateServiceGroups(input: UpdateServiceGroupsInput!): Success
  registerPlatform(input: RegisterPlatformInput!): RegistrationResponse!
  unregisterPlatform(input: UnregisterPlatformInput): Success!
  refreshUserPlatformToken: RefreshUserPlatformTokenResponse!
  refreshPlatformRegistrationConnectivityStatus(input: RefreshPlatformRegistrationConnectivityStatusInput!): RefreshPlatformRegistrationConnectivityStatusResponse!
  autoRegisterPlatform(platform: PlatformInput!): Success!
  editServiceInstance(id: ID!, name: String!): ServiceInstance
  addServiceInstance(input: AddServiceInput): SubscriptionModel
  deleteServiceInstance(id: ID!): ServiceInstance
  addServicePicture(serviceInstanceId: ID!, document: Upload, isLogo: Boolean): ServiceInstance
  updatePlatformServiceMetadata(input: UpdatePlatformServiceMetadataInput!, document: Upload): RegisteredPlatform
  addLabel(input: AddLabelInput!): Label!
  editLabel(id: ID!, input: EditLabelInput!): Label!
  deleteLabel(id: ID!): Label!
  addSubscription(service_instance_id: String): ServiceInstance
  addSubscriptionInService(service_instance_id: String, organization_id: ID, capability_ids: [ID], start_date: Date, end_date: Date): ServiceInstance
  deleteSubscription(subscription_id: ID!): ServiceInstance
  sendTelemetryEvent: SendTelemetryMutation
  editServiceCapability(input: EditServiceCapabilityInput, serviceInstanceId: String): SubscriptionModel
  addUserService(input: UserServiceAddInput!): [UserService]
  addYourselfInUserService(input: UserServiceAddYourselfInput!): [UserService]
  deleteUserService(input: UserServiceDeleteInput!): UserService
  adminAddUser(input: AdminAddUserInput!): User
  adminEditUser(id: ID!, input: AdminEditUserInput!): User!
  mergeTest(from: ID!, target: ID!): ID!
  addUser(input: AddUserInput!): User
  editUserCapabilities(id: ID!, input: EditUserCapabilitiesInput!): User!
  changeSelectedOrganization(organization_id: ID!): User
  bulkRemovePendingUserFromOrganization(input: BulkPendingUserFromOrganizationInput): Success
  bulkAcceptPendingUserInOrganization(input: BulkPendingUserFromOrganizationInput): Success
  removePendingUserFromOrganization(user_id: ID!, organization_id: ID!): User
  removeUserFromOrganization(user_id: ID!, organization_id: ID!): User
  editMeUser(input: EditMeUserInput!): User!
  resetPassword: Success!
  requestTransferPersonalSpace(new_email: String): Success!
  transferPersonalSpace(requestId: ID!): Success!
  login(email: String!, password: String): User
  logout: ID!
  contactUs: Success!
}

enum OrganizationOrdering {
  name
}

type OrganizationId implements Node {
  id: ID!
}

type Organization implements Node {
  id: ID!
  name: String!
  domains: [String!]
  personal_space: Boolean!
  capabilityUser: [Capability]
}

type OrganizationEdge {
  cursor: String!
  node: Organization!
}

type OrganizationConnection {
  totalCount: Int!
  edges: [OrganizationEdge!]!
  pageInfo: PageInfo!
}

input OrganizationInput {
  name: String!
  domains: [String!]
}

type RolePortal implements Node {
  id: ID!
  name: String!
}

enum ServiceConfigurationStatus {
  active
  inactive
}

type CustomDashboard implements Document & Node {
  id: ID!
  type: String!
  uploader: User
  uploader_organization: Organization
  name: String!
  short_description: String
  description: String
  file_name: String!
  minio_name: String!
  active: Boolean!
  created_at: Date!
  updated_at: Date
  updater_id: String
  download_number: Int
  share_number: Int
  slug: String!
  labels: [Label!]
  service_instance_id: String!
  service_instance: ServiceInstance
  subscription: SubscriptionModel
  children_documents: [ShareableResource!]
  product_version: String
}

type CustomDashboardEdge {
  cursor: String!
  node: CustomDashboard!
}

type CustomDashboardConnection {
  totalCount: Int!
  edges: [CustomDashboardEdge!]!
  pageInfo: PageInfo!
}

enum ServiceDefinitionIdentifier {
  vault
  link
  opencti_custom_dashboards
  opencti_integrations
  openaev_scenarios
  opencti_registration
  openaev_registration
}

type ServiceDefinition implements Node {
  id: ID!
  name: String!
  description: String
  public: Boolean
  identifier: ServiceDefinitionIdentifier!
  service_capability: [ServiceCapability]
}

enum DeploymentRequestPlatformRegion {
  eu_west
  us_east
  apac_au
  apac_sg
}

enum DeploymentRequestDeploymentType {
  trial
}

enum DeploymentRequestHubStatus {
  queued
  pending
  provisioning
  active
  expired
  failed
  cancelled
}

enum DeploymentRequestPlatformState {
  unprovisioned
  provisioning
  active
  removing
  removed
}

type DeploymentRequest implements Node {
  id: ID!
  platform_identifier: PlatformIdentifier!
  region: DeploymentRequestPlatformRegion!
  type: DeploymentRequestDeploymentType!
  job_title: String
  activity_sector: String
  use_case: String
  start_date: Date
  end_date: Date
  hub_status: DeploymentRequestHubStatus!
  ordering: Int!
  requester_email: String
  organization_name: String
  request_date: Date!
  counts_in_orga_quota: Boolean!
  cancellation_date: Date
  cancellation_user_email: String
  cancellation_reason: String
}

type PlatformDeploymentRequest {
  id: ID!
  platform_identifier: PlatformIdentifier!
  region: DeploymentRequestPlatformRegion!
  type: DeploymentRequestDeploymentType!
  platform_token: String!
  hub_status: DeploymentRequestHubStatus!
  target_state: DeploymentRequestPlatformState
  actual_state: DeploymentRequestPlatformState
  ordering: Int!
  start_date: Date
  end_date: Date
  job_title: String
  activity_sector: String
  use_case: String
  organization_name: String!
  organization_domains: [String!]
  requester_email: String!
  requester_first_name: String
  requester_last_name: String
  platform_id: String
  failure_reason: String
}

input CreateDeploymentRequestInput {
  platform_identifier: PlatformIdentifier!
  region: DeploymentRequestPlatformRegion!
  type: DeploymentRequestDeploymentType!
  job_title: String
  activity_sector: String
  use_case: String
}

input UpdateDeploymentRequestInput {
  id: ID!
  start_date: Date
  end_date: Date
  platform_id: String
  failure_reason: String
  actual_state: DeploymentRequestPlatformState
  ordering: Int
}

enum DeploymentRequestFilterKey {
  region
  type
  hub_status
  target_state
  actual_state
  platform_identifier
}

input DeploymentRequestFilter {
  key: DeploymentRequestFilterKey
  value: [String!]!
}

type DeploymentRequestEdge {
  cursor: String!
  node: DeploymentRequest!
}

type PlatformDeploymentRequestEdge {
  cursor: String!
  node: PlatformDeploymentRequest!
}

type DeploymentRequestConnection {
  totalCount: Int!
  edges: [DeploymentRequestEdge!]!
  pageInfo: PageInfo!
}

type PlatformDeploymentRequestConnection {
  totalCount: Int!
  edges: [PlatformDeploymentRequestEdge!]!
  pageInfo: PageInfo!
}

type DeploymentAvailability {
  region: DeploymentRequestPlatformRegion!
  availableCount: Int!
  capacity: Int!
  platform_identifier: PlatformIdentifier!
}

enum DeploymentRequestOrdering {
  requester_email
  organization_name
  start_date
  end_date
  hub_status
  region
  ordering
  request_date
  cancellation_date
  cancellation_user_email
  cancellation_reason
}

enum ReorderDeploymentRequestInQueueDirection {
  top
  up
}

input ReorderDeploymentRequestInQueueInput {
  id: ID!
  direction: ReorderDeploymentRequestInQueueDirection!
}

input UpdateDeploymentQuotaCapacityInput {
  platformIdentifier: PlatformIdentifier!
  region: DeploymentRequestPlatformRegion!
  newCapacity: Int!
}

type ShareableResource {
  id: ID!
  file_name: String!
  created_at: Date!
  name: String
  description: String
  download_number: Int
  active: Boolean!
}

enum DocumentOrdering {
  file_name
  description
  created_at
  download_number
  name
}

"""
 /!\ WARNING Do not use this type.
It exists only to cover cases where we failed to map to a specific Document.
"""
type DefaultDocument implements Node & Document {
  id: ID!
  type: String!
  uploader: User
  uploader_organization: Organization
  name: String
  short_description: String
  description: String
  file_name: String
  minio_name: String!
  active: Boolean!
  created_at: Date!
  updated_at: Date
  updater_id: String
  download_number: Int
  share_number: Int
  slug: String
  labels: [Label!]
  service_instance_id: String!
  service_instance: ServiceInstance
  subscription: SubscriptionModel
  children_documents: [ShareableResource!]
}

interface Document implements Node {
  id: ID!
  type: String!
  uploader: User
  uploader_organization: Organization
  name: String
  short_description: String
  description: String
  file_name: String
  minio_name: String!
  active: Boolean!
  created_at: Date!
  updated_at: Date
  updater_id: String
  download_number: Int
  share_number: Int
  slug: String
  labels: [Label!]
  service_instance_id: String!
  service_instance: ServiceInstance
  subscription: SubscriptionModel
  children_documents: [ShareableResource!]
}

input DocumentMetadata {
  key: String!
  value: String!
}

input CreateDocumentInput {
  name: String!
  slug: String!
  short_description: String!
  description: String!
  active: Boolean!
  labels: [String!]
  uploader_id: String!
}

input UpdateDocumentInput {
  name: String
  slug: String
  short_description: String
  description: String
  active: Boolean
  labels: [String!]
  uploader_organization_id: String
  uploader_id: String
}

type DocumentEdge {
  cursor: String!
  node: Document!
}

type DocumentConnection {
  totalCount: Int!
  edges: [DocumentEdge!]!
  pageInfo: PageInfo!
}

type ServiceGroup implements Node {
  id: ID!
  name: String!
  users: [User!]
}

input UpdateServiceGroupsInputGroup {
  id: ID!
  userIds: [ID!]!
}

input UpdateServiceGroupsInput {
  groups: [UpdateServiceGroupsInputGroup!]!
}

type ServiceLink implements Node {
  id: ID!
  service_instance_id: ID
  url: String
  name: String
}

enum IntegrationType {
  csv_feed
  connector
  rss_feed
  json_feed
  taxii_feed
  stream
  third_party_integration
}

enum IntegrationSubType {
  EXTERNAL_IMPORT
  INTERNAL_ENRICHMENT
  INTERNAL_EXPORT_FILE
  INTERNAL_IMPORT_FILE
  STREAM
  NATIVE
  ORCHESTRATION
  DETECTION
  CASE_MANAGEMENT
}

interface Integration implements Node & Document {
  id: ID!
  type: String!
  uploader: User
  uploader_organization: Organization
  name: String!
  short_description: String
  description: String
  file_name: String
  minio_name: String!
  active: Boolean!
  created_at: Date!
  updated_at: Date
  updater_id: String
  download_number: Int
  share_number: Int
  slug: String!
  labels: [Label!]
  service_instance_id: String!
  service_instance: ServiceInstance
  subscription: SubscriptionModel
  children_documents: [ShareableResource!]
  remover_id: ID
  integration_type: IntegrationType!
}

type CsvFeed implements Node & Document & Integration {
  id: ID!
  type: String!
  uploader: User
  uploader_organization: Organization
  name: String!
  short_description: String
  description: String
  file_name: String
  minio_name: String!
  active: Boolean!
  created_at: Date!
  updated_at: Date
  updater_id: String
  download_number: Int
  share_number: Int
  slug: String!
  labels: [Label!]
  service_instance_id: String!
  service_instance: ServiceInstance
  subscription: SubscriptionModel
  children_documents: [ShareableResource!]
  remover_id: ID
  integration_type: IntegrationType!
}

type Connector implements Node & Document & Integration {
  id: ID!
  type: String!
  uploader: User
  uploader_organization: Organization
  name: String!
  short_description: String
  description: String
  file_name: String
  minio_name: String!
  active: Boolean!
  created_at: Date!
  updated_at: Date
  updater_id: String
  download_number: Int
  share_number: Int
  slug: String!
  labels: [Label!]
  service_instance_id: String!
  service_instance: ServiceInstance
  subscription: SubscriptionModel
  children_documents: [ShareableResource!]
  remover_id: ID
  integration_type: IntegrationType!
  product_version: String
  container_image: String
  verified: Boolean!
  source_code: String
  subscription_link: String
  integration_subtype: IntegrationSubType!
  manager_supported: Boolean!
  playbook_supported: Boolean!
}

type TaxiiFeed implements Node & Document & Integration {
  id: ID!
  type: String!
  uploader: User
  uploader_organization: Organization
  name: String!
  short_description: String
  description: String
  file_name: String
  minio_name: String!
  active: Boolean!
  created_at: Date!
  updated_at: Date
  updater_id: String
  download_number: Int
  share_number: Int
  slug: String!
  labels: [Label!]
  service_instance_id: String!
  service_instance: ServiceInstance
  subscription: SubscriptionModel
  children_documents: [ShareableResource!]
  remover_id: ID
  integration_type: IntegrationType!
  integration_subtype: IntegrationSubType!
}

type Stream implements Node & Document & Integration {
  id: ID!
  type: String!
  uploader: User
  uploader_organization: Organization
  name: String!
  short_description: String
  description: String
  file_name: String
  minio_name: String!
  active: Boolean!
  created_at: Date!
  updated_at: Date
  updater_id: String
  download_number: Int
  share_number: Int
  slug: String!
  labels: [Label!]
  service_instance_id: String!
  service_instance: ServiceInstance
  subscription: SubscriptionModel
  children_documents: [ShareableResource!]
  remover_id: ID
  integration_type: IntegrationType!
  integration_subtype: IntegrationSubType!
}

type ThirdPartyIntegration implements Node & Document & Integration {
  id: ID!
  type: String!
  uploader: User
  uploader_organization: Organization
  name: String!
  short_description: String
  description: String
  file_name: String
  minio_name: String!
  active: Boolean!
  created_at: Date!
  updated_at: Date
  updater_id: String
  download_number: Int
  share_number: Int
  slug: String!
  labels: [Label!]
  service_instance_id: String!
  service_instance: ServiceInstance
  subscription: SubscriptionModel
  children_documents: [ShareableResource!]
  remover_id: ID
  integration_type: IntegrationType!
  integration_subtype: IntegrationSubType!
  vendor_url: String!
  product_version: String
  github_url: String
}

type IntegrationEdge {
  cursor: String!
  node: Integration!
}

type IntegrationConnection {
  totalCount: Int!
  edges: [IntegrationEdge!]!
  pageInfo: PageInfo!
}

type OpenAEVScenario implements Document & Node {
  id: ID!
  type: String!
  uploader: User
  uploader_organization: Organization
  name: String!
  short_description: String
  description: String
  file_name: String!
  minio_name: String!
  active: Boolean!
  created_at: Date!
  updated_at: Date
  updater_id: String
  download_number: Int
  share_number: Int
  slug: String!
  labels: [Label!]
  service_instance_id: String!
  service_instance: ServiceInstance
  subscription: SubscriptionModel
  children_documents: [ShareableResource!]
  product_version: String
}

type OpenAEVScenarioEdge {
  cursor: String!
  node: OpenAEVScenario!
}

type OpenAEVScenarioConnection {
  totalCount: Int!
  edges: [OpenAEVScenarioEdge!]!
  pageInfo: PageInfo!
}

input OpenCTIPlatformRegistrationStatusInput {
  platformId: String!
  token: String!
}

type OpenCTIPlatformRegistrationStatusResponse {
  status: PlatformRegistrationConnectivityStatus!
}

enum PlatformContract {
  CE
  EE
  trial
}

type RegisteredPlatform implements Node {
  id: ID!
  url: String!
  title: String!
  contract: PlatformContract!
  platform_id: String!
  identifier: ServiceDefinitionIdentifier!
  version: String
  illustration_document_id: String
  deployment_request: DeploymentRequest
  subscription: SubscriptionModel
}

input PlatformInput {
  id: ID!
  url: String!
  title: String!
  contract: PlatformContract!
  version: String
}

enum PlatformIdentifier {
  opencti
  openaev
}

input RegisterPlatformInput {
  organizationId: ID!
  platform: PlatformInput!
  identifier: PlatformIdentifier!
}

input CanUnregisterPlatformInput {
  platformId: String!
}

type RegistrationResponse {
  token: String!
}

enum PlatformRegistrationStatus {
  registered
  unregistered
  never_registered
}

input IsPlatformRegisteredInput {
  platformId: String!
}

type IsPlatformRegisteredOrganization implements Node {
  id: ID!
}

type IsPlatformRegisteredResponse {
  status: PlatformRegistrationStatus!
  platformTitle: String
  organization: IsPlatformRegisteredOrganization
}

type CanUnregisterResponse {
  isPlatformRegistered: Boolean!
  isAllowed: Boolean
  isInOrganization: Boolean
  organizationId: ID
}

input UnregisterPlatformInput {
  platformId: String!
  identifier: PlatformIdentifier!
}

enum PlatformRegistrationConnectivityStatus {
  active
  inactive
  not_found
}

input RefreshPlatformRegistrationConnectivityStatusInput {
  platformId: String!
  token: String!
  platformVersion: String!
  platformIdentifier: PlatformIdentifier
}

type RefreshPlatformRegistrationConnectivityStatusResponse {
  status: PlatformRegistrationConnectivityStatus!
}

type RefreshUserPlatformTokenResponse {
  token: String!
}

input RegisteredPlatformsInput {
  identifier: PlatformIdentifier
}

input RegisteredPlatformInput {
  service_instance_id: ID!
}

enum ServiceInstanceOrdering {
  name
  description
  ordering
}

enum ServiceInstanceCreationStatus {
  DISABLED
  PENDING
  CREATED
  READY
}

enum ServiceInstanceJoinType {
  JOIN_INVITE
  JOIN_ASK
  JOIN_AUTO
  JOIN_SELF
}

enum ServiceInstanceTag {
  openCTI
  openAEV
  trial
  others
}

enum ServiceInstanceFilterKey {
  tags
  service_definition_identifier
}

input ServiceInstanceFilter {
  key: ServiceInstanceFilterKey
  value: [String!]!
}

type ServiceInstance implements Node {
  id: ID!
  name: String!
  description: String
  slug: String
  creation_status: ServiceInstanceCreationStatus
  organization_subscribed: Boolean
  user_joined: Boolean
  links: [ServiceLink]
  organization: [Organization]
  subscriptions: [SubscriptionModel]
  capabilities: [String]!
  public: Boolean
  join_type: ServiceInstanceJoinType
  tags: [ServiceInstanceTag!]
  service_definition: ServiceDefinition
  logo_document_id: ID
  illustration_document_id: ID
  ordering: Int!
}

type ServiceInstanceEdge {
  cursor: String!
  node: ServiceInstance
}

type ServiceConnection {
  totalCount: Int!
  edges: [ServiceInstanceEdge!]!
  pageInfo: PageInfo!
}

type SeoServiceInstance implements Node {
  id: ID!
  name: String!
  slug: String
  description: String
  links: [ServiceLink]
  tags: [ServiceInstanceTag!]
  service_definition: ServiceDefinition!
  logo_document_id: ID
  illustration_document_id: ID
}

input AddServiceInput {
  service_instance_name: String
  service_instance_description: String
  fee_type: String
  price: Int
  organization_id: String
  url: String
}

input UpdatePlatformServiceMetadataInput {
  serviceInstanceId: ID!
  name: String
}

type SubscribedServiceInstanceConfiguration {
  token: String!
  platform_id: String!
  platform_url: String!
  registerer_id: String!
  platform_title: String!
  platform_contract: PlatformContract!
}

type SubscribedServiceInstance {
  service_instance_id: ID!
  organization_id: ID!
  is_personal_space: Boolean!
  configurations: [SubscribedServiceInstanceConfiguration]
}

type ServiceInstanceSubscription {
  add: ServiceInstance
  edit: ServiceInstance
  delete: ServiceInstance
}

type Subscription {
  ServiceInstance: ServiceInstanceSubscription
  User(organizationId: ID): UserSubscription
  MeUser: MeUserSubscription
  UserPending(organizationId: ID!): UserPendingSubscription
}

type Label implements Node {
  id: ID!
  name: String!
  color: String!
}

enum LabelOrdering {
  name
  color
}

type LabelEdge {
  cursor: String!
  node: Label!
}

type LabelConnection {
  totalCount: Int!
  edges: [LabelEdge!]!
  pageInfo: PageInfo!
}

input AddLabelInput {
  name: String!
  color: String!
}

input EditLabelInput {
  name: String
  color: String
}

type PlatformProvider {
  name: String!
  type: String!
  provider: String!
}

type Settings {
  platform_feature_flags: [String!]!
  platform_providers: [PlatformProvider!]!
  base_url_front: String!
  environment: String!
  domains_blacklist: String!
}

enum SubscriptionOrdering {
  organization_name
  start_date
  end_date
  status
  service_name
  service_provider
  service_type
  service_description
}

type SubscriptionModel implements Node {
  id: ID!
  organization_id: ID!
  service_instance_id: ID!
  start_date: Date
  end_date: Date
  status: String
  organization: Organization!
  service_url: String!
  service_instance: ServiceInstance
  subscription_capability: [SubscriptionCapability]
  user_service: [UserService]!
}

type SubscriptionEdge {
  cursor: String!
  node: SubscriptionModel!
}

type TelemetryResponse {
  result: Boolean!
  message: String
}

input OneClickDeployInput {
  platform_identifier: PlatformIdentifier!
  service_instance_id: ID!
  resource_id: ID!
  resource_title: String!
  platform_service_instance_id: ID!
}

type SendTelemetryMutation {
  oneClickDeploy(input: OneClickDeployInput!): TelemetryResponse
}

type GenericServiceCapability implements Node {
  id: ID!
  name: String
}

input EditServiceCapabilityInput {
  user_service_id: String
  capabilities: [String]!
}

type UserServiceCapability implements Node {
  id: ID!
  user_service_id: ID!
  generic_service_capability: GenericServiceCapability
  subscription_capability: SubscriptionCapability
}

type SubscriptionCapability implements Node {
  id: ID!
  service_capability: ServiceCapability
}

type ServiceCapability implements Node {
  id: ID!
  name: String
  description: String
  service_definition_id: ID
}

enum UserServiceOrdering {
  first_name
  last_name
  email
  service_name
  service_provider
  service_type
  service_description
  subscription_status
  ordering
}

input UserServiceAddInput {
  email: [String!]!
  capabilities: [String]
  subscriptionId: ID
}

input UserServiceAddYourselfInput {
  email: [String!]!
  serviceInstanceId: ID
}

input UserServiceDeleteInput {
  email: String!
  capabilities: [String]
  subscriptionId: String!
}

type UserServiceConnection {
  totalCount: Int!
  edges: [UserServiceEdge!]!
  pageInfo: PageInfo!
}

type UserServiceEdge {
  cursor: String!
  node: UserService
}

type UserService implements Node {
  id: ID!
  subscription_id: ID!
  user_id: ID!
  user: User
  subscription: SubscriptionModel
  user_service_capability: [UserServiceCapability]
  ordering: Int
}

type UserServiceDeleted implements Node {
  id: ID!
  subscription_id: ID!
  user_id: ID!
}

enum UserOrdering {
  email
  first_name
  last_name
  disabled
  country
  last_login
}

type Capability implements Node {
  id: ID!
  name: Restriction!
}

type OrganizationCapabilities implements Node {
  id: ID!
  organization: Organization!
  capabilities: [OrganizationCapability!]
}

type User implements Node {
  id: ID!
  email: String!
  first_name: String
  last_name: String
  picture: String
  country: String
  disabled: Boolean
  selected_organization_id: String
  organizations: [Organization!]
  organization_capabilities: [OrganizationCapabilities!]
  capabilities: [Capability!]
  roles_portal: [RolePortal!]
  selected_org_capabilities: [OrganizationCapability!]
  last_login: Date
  pending_organization_id: ID
}

type UserEdge {
  cursor: String!
  node: User!
}

type UserConnection {
  totalCount: Int!
  edges: [UserEdge!]!
  pageInfo: PageInfo!
}

input UsersWithCapabilitiesInOrganizationInput {
  organizationId: ID!
  capabilities: [OrganizationCapability!]!
}

input AdminEditUserInput {
  disabled: Boolean
  first_name: String
  last_name: String
  email: String
  organization_capabilities: [OrganizationCapabilitiesInput!]
}

input EditUserCapabilitiesInput {
  capabilities: [String!]
}

input EditMeUserInput {
  first_name: String
  last_name: String
  picture: String
  country: String
}

input OrganizationCapabilitiesInput {
  organization_id: ID!
  capabilities: [String!]
}

input AddUserInput {
  email: String!
  password: String
  capabilities: [String!]
}

input AdminAddUserInput {
  email: String!
  first_name: String
  last_name: String
  password: String
  organization_capabilities: [OrganizationCapabilitiesInput!]
}

input BulkPendingUserFromOrganizationInput {
  ids: [ID!]
  searchTerm: String
  filters: [Filter!]
  excludedIds: [ID!]
}

type UserSubscription {
  add: User
  edit: User
  delete: User
  merge: MergeEvent
}

type MeUserSubscription {
  edit: User
  delete: User
}

type UserPendingSubscription {
  delete: User
  invalidate: OrganizationId
}

enum Restriction {
  BYPASS
  ADMINISTRATE_ORGANIZATION
  MANAGE_ACCESS
  MANAGE_SUBSCRIPTION
  MANAGE_PLATFORM_REGISTRATION
  READ_TRIALS
}

enum OrganizationCapability {
  ADMINISTRATE_ORGANIZATION
  MANAGE_ACCESS
  MANAGE_SUBSCRIPTION
  MANAGE_PLATFORM_REGISTRATION
}

enum ServiceRestriction {
  ACCESS_USER
  MANAGE_ACCESS
  UPLOAD
  DELETE
}

interface Node {
  id: ID!
}

enum OrderingMode {
  asc
  desc
}

type PageInfo {
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String
  endCursor: String
}

type MergeEvent implements Node {
  id: ID!
  from: ID!
  target: ID!
}