directive @system_token repeatable on OBJECT | FIELD_DEFINITION

directive @platform_token repeatable on OBJECT | FIELD_DEFINITION

directive @auth(portalCapa: [PortalCapability] = [], orgaCapa: [OrganizationCapability] = []) repeatable on OBJECT | FIELD_DEFINITION

directive @service_capa(requires: [ServiceRestriction] = []) repeatable on OBJECT | FIELD_DEFINITION

scalar JSON

scalar Date

scalar Upload

enum FilterKey {
  label
  organization_id
  personal_space
  integration_type
  integration_subtype
  slug
  product_version
  manager_supported
  feed_url
  verified
}

enum LogicalOperator {
  AND
  OR
}

input Filter {
  key: FilterKey
  value: [String!]!
}

input LogicalFilterInput {
  leaf: Filter
  operator: LogicalOperator
  children: [LogicalFilterInput!]
}

type Success {
  success: Boolean!
}

type Query {
  updateOpenCTIManifest(tag: String): Success!
  organization(id: ID!): Organization
  organizations(first: Int = 50, after: ID, orderBy: OrganizationOrdering!, orderMode: OrderingMode!, searchTerm: String): OrganizationConnection!
  userOrganizations: [Organization!]!
  competitors(first: Int!, after: ID, orderBy: CompetitorOrdering!, orderMode: OrderingMode!): CompetitorConnection!
  deploymentRequests(first: Int!, after: ID, filters: [DeploymentRequestFilter!]): PlatformDeploymentRequestConnection!
  deploymentRequestsAvailable(platformIdentifier: PlatformIdentifier): [DeploymentAvailability!]!
  deploymentRequestsList(first: Int!, after: ID, filters: [DeploymentRequestFilter!], orderBy: DeploymentRequestOrdering!, orderMode: OrderingMode!, searchTerm: String): DeploymentRequestConnection!
  trialDeployments(input: TrialDeploymentsInput): TrialsDeployments!
  documentExists(documentName: String, service_instance_id: String): Boolean
  publicDocuments(slug: String!, first: Int!, after: ID, orderBy: DocumentOrdering!, orderMode: OrderingMode!, searchTerm: String, logicalFilters: LogicalFilterInput, serviceInstanceId: ID!): DocumentConnection!
  publicDocumentsByServiceSlug(serviceInstanceSlug: String!): [Document!]!
  publicDocumentBySlug(serviceInstanceId: ID!, slug: String!): Document
  documents(first: Int!, after: ID, orderBy: DocumentOrdering!, orderMode: OrderingMode!, searchTerm: String, logicalFilters: LogicalFilterInput, serviceInstanceId: String, parentsOnly: Boolean): DocumentConnection!
  document(documentId: ID, serviceInstanceId: ID): Document
  serviceGroups(serviceInstanceId: ID!): [ServiceGroup!]!
  openCTIPlatformRegistrationStatus(input: OpenCTIPlatformRegistrationStatusInput!): OpenCTIPlatformRegistrationStatusResponse! @deprecated(reason: "Use `refreshPlatformRegistrationConnectivityStatus` instead. This field is no longer used in the OpenCTI platform due to refactoring and the addition of a version value in the endpoint.")
  isPlatformRegistered(input: IsPlatformRegisteredInput!): IsPlatformRegisteredResponse!
  canUnregisterPlatform(input: CanUnregisterPlatformInput!): CanUnregisterResponse!
  registeredPlatform(input: RegisteredPlatformInput!): RegisteredPlatform
  registeredPlatforms(input: RegisteredPlatformsInput): [RegisteredPlatform!]!
  platformAssociatedOrganization(platformId: String!): Organization
  publicServiceInstances(first: Int!, after: ID, orderBy: ServiceInstanceOrdering!, orderMode: OrderingMode!): ServiceConnection!
  serviceInstances(first: Int!, after: ID, orderBy: ServiceInstanceOrdering!, orderMode: OrderingMode!, searchTerm: String, filters: [ServiceInstanceFilter!]): ServiceConnection!
  serviceInstanceLinksByTags(tags: [ServiceInstanceTag!]!): [SeoServiceInstance!]!
  serviceInstanceById(service_instance_id: ID): ServiceInstance
  serviceInstanceByIdWithSubscriptions(service_instance_id: ID, searchTerm: String): ServiceInstance
  subscribedServiceInstancesByIdentifier(identifier: ServiceDefinitionIdentifier!): [SubscribedServiceInstance!]!
  seoServiceInstances: [SeoServiceInstance!]!
  seoServiceInstance(slug: String!): SeoServiceInstance!
  epics(first: Int!, after: ID, orderBy: EpicOrdering!, orderMode: OrderingMode!): EpicConnection
  settings: Settings!
  useCases(first: Int!, after: ID, orderBy: UseCaseOrdering!, orderMode: OrderingMode!, searchTerm: String, documentType: String): UseCaseConnection
  subscriptionById(subscription_id: ID): SubscriptionModel
  userServiceOwned(first: Int!, after: ID, orderBy: UserServiceOrdering!, orderMode: OrderingMode!): UserServiceConnection
  serviceUsers(id: ID!, first: Int!, after: ID, orderBy: UserServiceOrdering!, orderMode: OrderingMode!): UserServiceConnection
  userServiceFromSubscription(first: Int!, after: ID, orderBy: UserServiceOrdering!, orderMode: OrderingMode!, subscription_id: ID!): UserServiceConnection
  me: User
  usersWithCapabilitiesInOrganization(input: UsersWithCapabilitiesInOrganizationInput!): [User!]!
  users(first: Int!, after: ID, orderBy: UserOrdering!, orderMode: OrderingMode!, searchTerm: String, filters: [Filter!]): UserConnection!
  pendingUsers(first: Int!, after: ID, orderBy: UserOrdering!, orderMode: OrderingMode!, searchTerm: String, filters: [Filter!]): UserConnection!
  userHasOrganizationWithSubscription: Boolean!
  node(id: ID!): Node
}

type Mutation {
  frontendErrorLog(message: String!, codeStack: String, componentStack: String): Boolean
  addOrganization(input: OrganizationInput!): Organization
  editOrganization(id: ID!, input: OrganizationInput!): Organization
  deleteOrganization(id: ID!): Organization
  createCompetitor(input: CreateCompetitorInput!): Competitor!
  updateCompetitor(input: UpdateCompetitorInput!): Competitor!
  deleteCompetitor(id: ID!): Competitor!
  createDeploymentRequest(input: CreateDeploymentRequestInput): DeploymentRequest!
  updateDeploymentRequest(input: UpdateDeploymentRequestInput!): PlatformDeploymentRequest!
  reorderDeploymentRequestInQueue(input: ReorderDeploymentRequestInQueueInput!): Success!
  cancelDeploymentRequest(deploymentRequestId: ID!, cancellationReason: String): DeploymentRequest
  adminCancelDeploymentRequest(deploymentRequestId: ID): DeploymentRequest
  updateDeploymentQuotaCapacity(input: UpdateDeploymentQuotaCapacityInput!): Success!
  createDocument(input: CreateDocumentInput!, metadata: [DocumentMetadata!]!, serviceInstanceId: String, sourceDocument: Upload, logo: Upload, images: [Upload!]): Document!
  updateDocument(documentId: ID!, input: UpdateDocumentInput!, metadata: [DocumentMetadata!]!, serviceInstanceId: String, sourceDocument: Upload, logo: Upload, images: [Upload!], existingImageIds: [ID!]): Document!
  deleteDocument(documentId: ID, service_instance_id: String, forceDelete: Boolean): Document!
  incrementShareNumberDocument(documentId: ID): Document!
  updateServiceGroups(input: UpdateServiceGroupsInput!): Success
  registerPlatform(input: RegisterPlatformInput!): RegistrationResponse!
  unregisterPlatform(input: UnregisterPlatformInput): Success!
  refreshUserPlatformToken: RefreshUserPlatformTokenResponse!
  refreshPlatformRegistrationConnectivityStatus(input: RefreshPlatformRegistrationConnectivityStatusInput!): RefreshPlatformRegistrationConnectivityStatusResponse!
  autoRegisterPlatform(platform: PlatformInput @deprecated(reason: "Use input instead"), input: AutoRegisterPlatformInput): Success!
  addServicePicture(serviceInstanceId: ID!, document: Upload, isLogo: Boolean): ServiceInstance
  updatePlatformServiceMetadata(input: UpdatePlatformServiceMetadataInput!, document: Upload): RegisteredPlatform
  createEpic(input: CreateEpicInput!, document: [Upload!]): Epic!
  updateEpic(id: ID!, input: UpdateEpicInput!, document: [Upload!]): Epic!
  deleteEpic(id: ID!): Epic!
  addUseCase(input: AddUseCaseInput!): UseCase!
  editUseCase(id: ID!, input: EditUseCaseInput!): UseCase!
  deleteUseCase(id: ID!): UseCase!
  addSubscription(service_instance_id: String): ServiceInstance
  addSubscriptionInService(service_instance_id: String, organization_id: ID, capability_ids: [ID], start_date: Date, end_date: Date): ServiceInstance
  deleteSubscription(subscription_id: ID!): ServiceInstance
  sendTelemetryEvent: SendTelemetryMutation
  editServiceCapability(input: EditServiceCapabilityInput, serviceInstanceId: String): SubscriptionModel
  addUserService(input: UserServiceAddInput!): [UserService]
  addYourselfInUserService(input: UserServiceAddYourselfInput!): [UserService]
  deleteUserService(input: UserServiceDeleteInput!): UserService
  adminAddUser(input: AdminAddUserInput!): User
  adminEditUser(id: ID!, input: AdminEditUserInput!): User!
  mergeTest(from: ID!, target: ID!): ID!
  addUser(input: AddUserInput!): User
  editUserCapabilities(id: ID!, input: EditUserCapabilitiesInput!): User!
  changeSelectedOrganization(organization_id: ID!): User
  bulkRemovePendingUserFromOrganization(input: BulkPendingUserFromOrganizationInput): Success
  bulkAcceptPendingUserInOrganization(input: BulkPendingUserFromOrganizationInput): Success
  removePendingUserFromOrganization(user_id: ID!, organization_id: ID!): User
  removeUserFromOrganization(user_id: ID!, organization_id: ID!): User
  editMeUser(input: EditMeUserInput!): User!
  uploadUserPicture(document: Upload!): User!
  resetPassword: Success!
  requestTransferPersonalSpace(new_email: String): Success!
  transferPersonalSpace(requestId: ID!): Success!
  login(email: String!, password: String): User
  logout: ID!
  contactUs(message: String, platformId: ID, platformIdentifier: PlatformIdentifier): Success!
}

enum OrganizationOrdering {
  name
}

type OrganizationId implements Node {
  id: ID!
}

type Organization implements Node {
  id: ID!
  name: String!
  domains: [String!]
  personal_space: Boolean!
  capabilityUser: [Capability]
}

type OrganizationEdge {
  cursor: String!
  node: Organization!
}

type OrganizationConnection {
  totalCount: Int!
  edges: [OrganizationEdge!]!
  pageInfo: PageInfo!
}

input OrganizationInput {
  name: String!
  domains: [String!]
}

type RolePortal implements Node {
  id: ID!
  name: String!
}

enum CompetitorOrdering {
  name
  tier
  domain
}

enum CompetitorTier {
  tier1
  tier2
  tier3
}

type Competitor implements Node {
  id: ID!
  name: String!
  tier: CompetitorTier!
  domain: String!
}

type CompetitorEdge {
  cursor: String!
  node: Competitor!
}

type CompetitorConnection {
  totalCount: Int!
  edges: [CompetitorEdge!]!
  pageInfo: PageInfo!
}

input CreateCompetitorInput {
  name: String!
  tier: CompetitorTier!
  domain: String!
}

input UpdateCompetitorInput {
  id: ID!
  name: String
  tier: CompetitorTier
  domain: String
}

enum ServiceConfigurationStatus {
  active
  inactive
}

enum ServiceDefinitionIdentifier {
  vault
  link
  opencti_custom_dashboards
  opencti_integrations
  openaev_scenarios
  opencti_registration
  openaev_registration
  xtm_suite_roadmap
}

type ServiceDefinition implements Node {
  id: ID!
  name: String!
  description: String
  public: Boolean
  identifier: ServiceDefinitionIdentifier!
  service_capability: [ServiceCapability]
}

enum DeploymentRequestPlatformRegion {
  eu_west
  us_east
  apac_au
  apac_sg
}

enum DeploymentRequestDeploymentType {
  trial
}

enum DeploymentRequestHubStatus {
  queued
  pending
  provisioning
  active
  expired
  failed
  cancelled
}

enum DeploymentRequestPlatformState {
  unprovisioned
  provisioning
  active
  removing
  removed
}

enum DeploymentRequestSource {
  xtmhub
  opencti_demo
  openaev_demo
}

enum DeploymentRequestUseCase {
  threat_profiling_cti
  threat_profiling_fimi
  threat_profiling_faml
  threat_profiling_leo
  threat_hunting
  technical_reporting
  strategic_reporting
  incident_response
  security_stack
  detection_engineering
  attack_simulation
  crisis_simulation
  vulnerability_management
  centralizing_knowledge
  sharing_knowledge
  hosting_threat_community
}

enum DeploymentRequestActivitySector {
  computer_network_security
  computer_games
  computer_software
  defense_space
  entertainment
  financial_services
  government_administration
  government_relations
  higher_education
  hospital_health_care
  hospitality
  information_technology
  insurance
  legal_services
  luxury_goods_jewelry
  management_consulting
  marketing_advertising
  military
  non_profit
  oil_energy
  pharmaceuticals
  photography
  retail
  security_investigations
  semiconductors
  telecommunications
  transportation
  utilities
  wireless
}

enum DeploymentRequestJobTitle {
  ceo
  ciso_cso_cio
  c_level
  general_manager_vp
  director_head_cybersecurity
  cybersecurity_team_lead
  application_security_specialist
  cloud_security_specialist
  cybersecurity_architect
  cybersecurity_engineer
  dfir_specialist
  grc_specialist
  iam_specialist
  penetration_tester
  soc_analyst
  threat_intelligence_analyst
  vulnerability_analyst
  consultant
  other
}

type DeploymentRequest implements Node {
  id: ID!
  platform_identifier: PlatformIdentifier!
  region: DeploymentRequestPlatformRegion!
  type: DeploymentRequestDeploymentType!
  job_title: DeploymentRequestJobTitle
  activity_sector: DeploymentRequestActivitySector
  use_case: DeploymentRequestUseCase
  start_date: Date
  end_date: Date
  hub_status: DeploymentRequestHubStatus!
  ordering: Int!
  requester_email: String
  organization_requester_id: ID!
  service_instance_id: ID!
  organization_name: String
  request_date: Date!
  counts_in_orga_quota: Boolean!
  cancellation_date: Date
  cancellation_user_email: String
  cancellation_reason: String
  platform_id: String
  platform_url: String
}

type PlatformDeploymentRequest {
  id: ID!
  platform_identifier: PlatformIdentifier!
  region: DeploymentRequestPlatformRegion!
  type: DeploymentRequestDeploymentType!
  platform_token: String!
  hub_status: DeploymentRequestHubStatus!
  target_state: DeploymentRequestPlatformState
  actual_state: DeploymentRequestPlatformState
  ordering: Int!
  start_date: Date
  end_date: Date
  job_title: DeploymentRequestJobTitle
  activity_sector: DeploymentRequestActivitySector
  use_case: DeploymentRequestUseCase
  organization_name: String!
  organization_domains: [String!]
  requester_email: String!
  requester_first_name: String
  requester_last_name: String
  platform_id: String
  platform_url: String
  failure_reason: String
}

input CreateDeploymentRequestInput {
  platform_identifier: PlatformIdentifier!
  region: DeploymentRequestPlatformRegion!
  type: DeploymentRequestDeploymentType!
  job_title: DeploymentRequestJobTitle
  activity_sector: DeploymentRequestActivitySector
  use_case: DeploymentRequestUseCase
  source: DeploymentRequestSource!
}

input UpdateDeploymentRequestInput {
  id: ID!
  start_date: Date
  end_date: Date
  platform_id: String
  failure_reason: String
  actual_state: DeploymentRequestPlatformState
  ordering: Int
}

enum DeploymentRequestFilterKey {
  region
  type
  hub_status
  target_state
  actual_state
  platform_identifier
}

input DeploymentRequestFilter {
  key: DeploymentRequestFilterKey
  value: [String!]!
}

type DeploymentRequestEdge {
  cursor: String!
  node: DeploymentRequest!
}

type PlatformDeploymentRequestEdge {
  cursor: String!
  node: PlatformDeploymentRequest!
}

type DeploymentRequestConnection {
  totalCount: Int!
  edges: [DeploymentRequestEdge!]!
  pageInfo: PageInfo!
}

type PlatformDeploymentRequestConnection {
  totalCount: Int!
  edges: [PlatformDeploymentRequestEdge!]!
  pageInfo: PageInfo!
}

type DeploymentAvailability {
  region: DeploymentRequestPlatformRegion!
  availableCount: Int!
  capacity: Int!
  platform_identifier: PlatformIdentifier!
}

type DeployedPlatform {
  serviceInstanceId: ID!
  platformIdentifier: PlatformIdentifier!
}

type TrialsDeployments {
  availableTrials: [PlatformIdentifier!]!
  deployed: [DeployedPlatform!]!
  isBlacklisted: Boolean!
}

enum DeploymentRequestOrdering {
  requester_email
  organization_name
  start_date
  end_date
  hub_status
  region
  ordering
  request_date
  cancellation_date
  cancellation_user_email
  cancellation_reason
}

enum ReorderDeploymentRequestInQueueDirection {
  top
  up
}

input ReorderDeploymentRequestInQueueInput {
  id: ID!
  direction: ReorderDeploymentRequestInQueueDirection!
}

input UpdateDeploymentQuotaCapacityInput {
  platformIdentifier: PlatformIdentifier!
  region: DeploymentRequestPlatformRegion!
  newCapacity: Int!
}

input TrialDeploymentsInput {
  organizationId: ID!
  platformIdentifiers: [PlatformIdentifier!]
}

enum DocumentSourceType {
  external
  internal
}

enum DocumentImageType {
  logo
  image
}

enum DocumentMetadataKeyCode {
  feed_url
  integration_type
  integration_subtype
  datasheet_url
  demo_url
  product_version
  vendor_url
  github_url
  container_image
  verified
  source_code
  subscription_link
  manager_supported
  playbook_supported
  image_type
  minimum_deployable_version
}

type ShareableResource {
  id: ID!
  file_name: String!
  created_at: Date!
  name: String
  description: String
  download_number: Int
  active: Boolean!
  source_type: DocumentSourceType!
  image_type: DocumentImageType
}

enum DocumentOrdering {
  file_name
  description
  created_at
  updated_at
  download_number
  name
}

"""
/!\ WARNING Do not use this type.
It exists only to cover cases where we failed to map to a specific Document.
"""
type DefaultDocument implements Node & Document {
  id: ID!
  type: String!
  uploader: User
  uploader_organization: Organization
  name: String
  short_description: String
  description: String
  file_name: String
  minio_name: String!
  active: Boolean!
  created_at: Date!
  updated_at: Date
  updater_id: String
  download_number: Int
  share_number: Int
  slug: String
  use_cases: [UseCase!]
  service_instance_id: String!
  service_instance: ServiceInstance
  subscription: SubscriptionModel
  children_documents: [ShareableResource!]
}

interface Document implements Node {
  id: ID!
  type: String!
  uploader: User
  uploader_organization: Organization
  name: String
  short_description: String
  description: String
  file_name: String
  minio_name: String!
  active: Boolean!
  created_at: Date!
  updated_at: Date
  updater_id: String
  download_number: Int
  share_number: Int
  slug: String
  use_cases: [UseCase!]
  service_instance_id: String!
  service_instance: ServiceInstance
  subscription: SubscriptionModel
  children_documents: [ShareableResource!]
}

input DocumentMetadata {
  key: DocumentMetadataKeyCode!
  value: String!
}

input CreateDocumentInput {
  name: String!
  slug: String!
  short_description: String!
  description: String!
  active: Boolean!
  use_cases: [String!]
  uploader_id: String!
}

input UpdateDocumentInput {
  name: String
  slug: String
  short_description: String
  description: String
  active: Boolean
  use_cases: [String!]
  uploader_organization_id: String
  uploader_id: String
}

type DocumentEdge {
  cursor: String!
  node: Document!
}

type DocumentConnection {
  totalCount: Int!
  edges: [DocumentEdge!]!
  pageInfo: PageInfo!
}

type OpenAEVScenario implements Document & Node {
  id: ID!
  type: String!
  uploader: User
  uploader_organization: Organization
  name: String!
  short_description: String
  description: String
  file_name: String!
  minio_name: String!
  active: Boolean!
  created_at: Date!
  updated_at: Date
  updater_id: String
  download_number: Int
  share_number: Int
  slug: String!
  use_cases: [UseCase!]
  service_instance_id: String!
  service_instance: ServiceInstance
  subscription: SubscriptionModel
  children_documents: [ShareableResource!]
  product_version: String
}

type CustomDashboard implements Document & Node {
  id: ID!
  type: String!
  uploader: User
  uploader_organization: Organization
  name: String!
  short_description: String
  description: String
  file_name: String!
  minio_name: String!
  active: Boolean!
  created_at: Date!
  updated_at: Date
  updater_id: String
  download_number: Int
  share_number: Int
  slug: String!
  use_cases: [UseCase!]
  service_instance_id: String!
  service_instance: ServiceInstance
  subscription: SubscriptionModel
  children_documents: [ShareableResource!]
  product_version: String
}

enum IntegrationType {
  csv_feed
  connector
  rss_feed
  json_feed
  taxii_feed
  stream
  third_party_integration
}

enum IntegrationSubType {
  EXTERNAL_IMPORT
  INTERNAL_ENRICHMENT
  INTERNAL_EXPORT_FILE
  INTERNAL_IMPORT_FILE
  STREAM
  NATIVE
  ORCHESTRATION
  DETECTION
  CASE_MANAGEMENT
}

interface Integration implements Node & Document {
  id: ID!
  type: String!
  uploader: User
  uploader_organization: Organization
  name: String!
  short_description: String
  description: String
  file_name: String
  minio_name: String!
  active: Boolean!
  created_at: Date!
  updated_at: Date
  updater_id: String
  download_number: Int
  share_number: Int
  slug: String!
  use_cases: [UseCase!]
  service_instance_id: String!
  service_instance: ServiceInstance
  subscription: SubscriptionModel
  children_documents: [ShareableResource!]
  remover_id: ID
  integration_type: IntegrationType!
  datasheet_url: String
  demo_url: String
}

type IntegrationHack implements Node & Document & Integration {
  id: ID!
  type: String!
  uploader: User
  uploader_organization: Organization
  name: String!
  short_description: String
  description: String
  file_name: String
  minio_name: String!
  active: Boolean!
  created_at: Date!
  updated_at: Date
  updater_id: String
  download_number: Int
  share_number: Int
  slug: String!
  use_cases: [UseCase!]
  service_instance_id: String!
  service_instance: ServiceInstance
  subscription: SubscriptionModel
  children_documents: [ShareableResource!]
  remover_id: ID
  integration_type: IntegrationType!
  datasheet_url: String
  demo_url: String
}

type CsvFeed implements Node & Document & Integration {
  id: ID!
  type: String!
  uploader: User
  uploader_organization: Organization
  name: String!
  short_description: String
  description: String
  file_name: String
  minio_name: String!
  active: Boolean!
  created_at: Date!
  updated_at: Date
  updater_id: String
  download_number: Int
  share_number: Int
  slug: String!
  use_cases: [UseCase!]
  service_instance_id: String!
  service_instance: ServiceInstance
  subscription: SubscriptionModel
  children_documents: [ShareableResource!]
  remover_id: ID
  feed_url: String
  integration_type: IntegrationType!
  datasheet_url: String
  demo_url: String
}

type Connector implements Node & Document & Integration {
  id: ID!
  type: String!
  uploader: User
  uploader_organization: Organization
  name: String!
  short_description: String
  description: String
  file_name: String
  minio_name: String!
  active: Boolean!
  created_at: Date!
  updated_at: Date
  updater_id: String
  download_number: Int
  share_number: Int
  slug: String!
  use_cases: [UseCase!]
  service_instance_id: String!
  service_instance: ServiceInstance
  subscription: SubscriptionModel
  children_documents: [ShareableResource!]
  remover_id: ID
  integration_type: IntegrationType!
  product_version: String
  container_image: String
  verified: Boolean!
  source_code: String
  subscription_link: String
  integration_subtype: IntegrationSubType!
  manager_supported: Boolean!
  playbook_supported: Boolean!
  datasheet_url: String
  demo_url: String
  minimum_deployable_version: String
}

type TaxiiFeed implements Node & Document & Integration {
  id: ID!
  type: String!
  uploader: User
  uploader_organization: Organization
  name: String!
  short_description: String
  description: String
  file_name: String
  minio_name: String!
  active: Boolean!
  created_at: Date!
  updated_at: Date
  updater_id: String
  download_number: Int
  share_number: Int
  slug: String!
  use_cases: [UseCase!]
  service_instance_id: String!
  service_instance: ServiceInstance
  subscription: SubscriptionModel
  children_documents: [ShareableResource!]
  remover_id: ID
  feed_url: String
  integration_type: IntegrationType!
  integration_subtype: IntegrationSubType!
  datasheet_url: String
  demo_url: String
}

type Stream implements Node & Document & Integration {
  id: ID!
  type: String!
  uploader: User
  uploader_organization: Organization
  name: String!
  short_description: String
  description: String
  file_name: String
  minio_name: String!
  active: Boolean!
  created_at: Date!
  updated_at: Date
  updater_id: String
  download_number: Int
  share_number: Int
  slug: String!
  use_cases: [UseCase!]
  service_instance_id: String!
  service_instance: ServiceInstance
  subscription: SubscriptionModel
  children_documents: [ShareableResource!]
  remover_id: ID
  feed_url: String
  integration_type: IntegrationType!
  integration_subtype: IntegrationSubType!
  datasheet_url: String
  demo_url: String
}

type ThirdPartyIntegration implements Node & Document & Integration {
  id: ID!
  type: String!
  uploader: User
  uploader_organization: Organization
  name: String!
  short_description: String
  description: String
  file_name: String
  minio_name: String!
  active: Boolean!
  created_at: Date!
  updated_at: Date
  updater_id: String
  download_number: Int
  share_number: Int
  slug: String!
  use_cases: [UseCase!]
  service_instance_id: String!
  service_instance: ServiceInstance
  subscription: SubscriptionModel
  children_documents: [ShareableResource!]
  remover_id: ID
  integration_type: IntegrationType!
  integration_subtype: IntegrationSubType!
  vendor_url: String!
  product_version: String
  github_url: String
  datasheet_url: String
  demo_url: String
}

type ServiceGroup implements Node {
  id: ID!
  name: String!
  users: [User!]
}

input UpdateServiceGroupsInputGroup {
  id: ID!
  userIds: [ID!]!
}

input UpdateServiceGroupsInput {
  groups: [UpdateServiceGroupsInputGroup!]!
}

type ServiceLink implements Node {
  id: ID!
  service_instance_id: ID
  url: String
  name: String
}

input OpenCTIPlatformRegistrationStatusInput {
  platformId: String!
  token: String!
}

type OpenCTIPlatformRegistrationStatusResponse {
  status: PlatformRegistrationConnectivityStatus!
}

enum PlatformContract {
  CE
  EE
  trial
}

type RegisteredPlatform implements Node {
  id: ID!
  url: String!
  title: String!
  contract: PlatformContract!
  platform_id: String!
  identifier: ServiceDefinitionIdentifier!
  version: String
  illustration_document_id: String
  deployment_request: DeploymentRequest
  subscription: SubscriptionModel
}

input PlatformInput {
  id: ID!
  url: String!
  title: String!
  contract: PlatformContract!
  version: String
}

enum PlatformIdentifier {
  opencti
  openaev
}

input RegisterPlatformInput {
  organizationId: ID!
  platform: PlatformInput!
  identifier: PlatformIdentifier!
}

input CanUnregisterPlatformInput {
  platformId: String!
}

type RegistrationResponse {
  token: String!
}

enum PlatformRegistrationStatus {
  registered
  unregistered
  never_registered
}

input IsPlatformRegisteredInput {
  platformId: String!
}

type IsPlatformRegisteredOrganization implements Node {
  id: ID!
}

type IsPlatformRegisteredResponse {
  status: PlatformRegistrationStatus!
  platformTitle: String
  organization: IsPlatformRegisteredOrganization
}

type CanUnregisterResponse {
  isPlatformRegistered: Boolean!
  isAllowed: Boolean
  isInOrganization: Boolean
  organizationId: ID
}

input UnregisterPlatformInput {
  platformId: String!
  identifier: PlatformIdentifier!
}

enum PlatformRegistrationConnectivityStatus {
  active
  inactive
  not_found
}

input RefreshPlatformRegistrationConnectivityStatusInput {
  platformId: String!
  token: String!
  platformVersion: String!
  platformIdentifier: PlatformIdentifier
}

type RefreshPlatformRegistrationConnectivityStatusResponse {
  status: PlatformRegistrationConnectivityStatus!
}

type RefreshUserPlatformTokenResponse {
  token: String!
}

input RegisteredPlatformsInput {
  identifier: PlatformIdentifier
  onlyActive: Boolean
  onlyTrial: Boolean
}

input RegisteredPlatformInput {
  service_instance_id: ID!
}

input AutoRegisterPlatformInput {
  platform: PlatformInput!
  existing_users_count: Int
}

enum ServiceInstanceOrdering {
  name
  description
  ordering
}

enum ServiceInstanceCreationStatus {
  DISABLED
  PENDING
  CREATED
  READY
}

enum ServiceInstanceJoinType {
  JOIN_INVITE
  JOIN_ASK
  JOIN_AUTO
  JOIN_SELF
}

enum ServiceInstanceTag {
  openCTI
  openAEV
  trial
  others
}

enum ServiceInstanceFilterKey {
  tags
  service_definition_identifier
}

input ServiceInstanceFilter {
  key: ServiceInstanceFilterKey
  value: [String!]!
}

type ServiceInstance implements Node {
  id: ID!
  name: String!
  description: String
  slug: String
  creation_status: ServiceInstanceCreationStatus
  organization_subscribed: Boolean
  user_joined: Boolean
  links: [ServiceLink]
  organization: [Organization]
  subscriptions: [SubscriptionModel]
  capabilities: [String]!
  public: Boolean
  join_type: ServiceInstanceJoinType
  tags: [ServiceInstanceTag!]
  service_definition: ServiceDefinition
  logo_document_id: ID
  illustration_document_id: ID
  ordering: Int!
}

type ServiceInstanceEdge {
  cursor: String!
  node: ServiceInstance
}

type ServiceConnection {
  totalCount: Int!
  edges: [ServiceInstanceEdge!]!
  pageInfo: PageInfo!
}

type SeoServiceInstance implements Node {
  id: ID!
  name: String!
  slug: String
  description: String
  links: [ServiceLink]
  tags: [ServiceInstanceTag!]
  service_definition: ServiceDefinition!
  logo_document_id: ID
  illustration_document_id: ID
}

input AddServiceInput {
  service_instance_name: String
  service_instance_description: String
  fee_type: String
  price: Int
  organization_id: String
  url: String
}

input UpdatePlatformServiceMetadataInput {
  serviceInstanceId: ID!
  name: String
}

type SubscribedServiceInstanceConfiguration {
  token: String!
  platform_id: String!
  platform_url: String!
  registerer_id: String!
  platform_title: String!
  platform_contract: PlatformContract!
}

type SubscribedServiceInstance {
  service_instance_id: ID!
  organization_id: ID!
  is_personal_space: Boolean!
  configurations: [SubscribedServiceInstanceConfiguration]
}

type ServiceInstanceSubscription {
  add: ServiceInstance
  edit: ServiceInstance
  delete: ServiceInstance
}

type Subscription {
  ServiceInstance: ServiceInstanceSubscription
  User(organizationId: ID): UserSubscription
  MeUser: MeUserSubscription
  UserPending(organizationId: ID!): UserPendingSubscription
}

enum FiligranProduct {
  opencti
  openaev
  opengrc
  xtmone
  xtmhub
}

enum Timeline {
  now
  next
  under_consideration
}

enum EpicType {
  other
  integration
}

type Epic implements Node {
  id: ID!
  epic: String!
  title: String!
  short_description: String!
  description: String!
  active: Boolean!
  product: FiligranProduct!
  timeline: Timeline!
  epic_type: EpicType!
  document: Document
  document_id: ID
  uploader_id: String!
  updater_id: String
  created_at: Date!
  updated_at: Date
}

input CreateEpicInput {
  epic: String!
  title: String!
  short_description: String!
  description: String!
  active: Boolean
  product: FiligranProduct!
  timeline: Timeline!
  is_integration: Boolean
  illustration_document: Upload
}

input UpdateEpicInput {
  epic: String
  title: String
  short_description: String
  description: String
  active: Boolean
  product: FiligranProduct
  timeline: Timeline
  is_integration: Boolean
  illustration_document: Upload
}

type EpicEdge {
  cursor: String!
  node: Epic!
}

type EpicConnection {
  totalCount: Int!
  edges: [EpicEdge!]!
  pageInfo: PageInfo!
}

enum EpicOrdering {
  epic
}

type PlatformProvider {
  name: String!
  type: String!
  provider: String!
}

type Settings {
  platform_feature_flags: [String!]!
  platform_providers: [PlatformProvider!]!
  base_url_front: String!
  environment: String!
}

type UseCase implements Node {
  id: ID!
  name: String!
  color: String!
}

enum UseCaseOrdering {
  name
  color
}

type UseCaseEdge {
  cursor: String!
  node: UseCase!
}

type UseCaseConnection {
  totalCount: Int!
  edges: [UseCaseEdge!]!
  pageInfo: PageInfo!
}

input AddUseCaseInput {
  name: String!
  color: String!
}

input EditUseCaseInput {
  name: String
  color: String
}

enum SubscriptionOrdering {
  organization_name
  start_date
  end_date
  status
  service_name
  service_provider
  service_type
  service_description
}

type SubscriptionModel implements Node {
  id: ID!
  organization_id: ID!
  service_instance_id: ID!
  start_date: Date
  end_date: Date
  status: String
  organization: Organization!
  service_url: String!
  service_instance: ServiceInstance
  subscription_capability: [SubscriptionCapability]
  user_service: [UserService]!
}

type SubscriptionEdge {
  cursor: String!
  node: SubscriptionModel!
}

type TelemetryResponse {
  result: Boolean!
  message: String
}

input OneClickDeployInput {
  platform_identifier: PlatformIdentifier!
  service_instance_id: ID!
  resource_id: ID!
  resource_title: String!
  platform_service_instance_id: ID!
}

type SendTelemetryMutation {
  oneClickDeploy(input: OneClickDeployInput!): TelemetryResponse
}

type GenericServiceCapability implements Node {
  id: ID!
  name: String
}

input EditServiceCapabilityInput {
  user_service_id: String
  capabilities: [String]!
}

type UserServiceCapability implements Node {
  id: ID!
  user_service_id: ID!
  generic_service_capability: GenericServiceCapability
  subscription_capability: SubscriptionCapability
}

type SubscriptionCapability implements Node {
  id: ID!
  service_capability: ServiceCapability
}

type ServiceCapability implements Node {
  id: ID!
  name: String
  description: String
  service_definition_id: ID
}

enum UserServiceOrdering {
  first_name
  last_name
  email
  service_name
  service_provider
  service_type
  service_description
  subscription_status
  ordering
}

input UserServiceAddInput {
  email: [String!]!
  capabilities: [String]
  subscriptionId: ID
}

input UserServiceAddYourselfInput {
  email: [String!]!
  serviceInstanceId: ID
}

input UserServiceDeleteInput {
  email: String!
  capabilities: [String]
  subscriptionId: String!
}

type UserServiceConnection {
  totalCount: Int!
  edges: [UserServiceEdge!]!
  pageInfo: PageInfo!
}

type UserServiceEdge {
  cursor: String!
  node: UserService
}

type UserService implements Node {
  id: ID!
  subscription_id: ID!
  user_id: ID!
  user: User
  subscription: SubscriptionModel
  user_service_capability: [UserServiceCapability]
  ordering: Int
}

type UserServiceDeleted implements Node {
  id: ID!
  subscription_id: ID!
  user_id: ID!
}

enum UserOrdering {
  email
  first_name
  last_name
  disabled
  country
  last_login
}

type Capability implements Node {
  id: ID!
  name: PortalCapability!
}

type OrganizationCapabilities implements Node {
  id: ID!
  organization: Organization!
  capabilities: [OrganizationCapability!]
}

type User implements Node {
  id: ID!
  email: String!
  first_name: String
  last_name: String
  picture: String
  country: String
  disabled: Boolean
  selected_organization_id: String
  organizations: [Organization!]
  organization_capabilities: [OrganizationCapabilities!]
  capabilities: [Capability!]
  roles_portal: [RolePortal!]
  selected_org_capabilities: [OrganizationCapability!]
  last_login: Date
  pending_organization_id: ID
}

type UserEdge {
  cursor: String!
  node: User!
}

type UserConnection {
  totalCount: Int!
  edges: [UserEdge!]!
  pageInfo: PageInfo!
}

input UsersWithCapabilitiesInOrganizationInput {
  organizationId: ID!
  capabilities: [OrganizationCapability!]!
}

input AdminEditUserInput {
  disabled: Boolean
  first_name: String
  last_name: String
  email: String
  organization_capabilities: [OrganizationCapabilitiesInput!]
}

input EditUserCapabilitiesInput {
  capabilities: [String!]
}

input EditMeUserInput {
  first_name: String
  last_name: String
  country: String
}

input OrganizationCapabilitiesInput {
  organization_id: ID!
  capabilities: [String!]
}

input AddUserInput {
  email: String!
  password: String
  capabilities: [String!]
}

input AdminAddUserInput {
  email: String!
  first_name: String
  last_name: String
  password: String
  organization_capabilities: [OrganizationCapabilitiesInput!]
}

input BulkPendingUserFromOrganizationInput {
  ids: [ID!]
  searchTerm: String
  filters: [Filter!]
  excludedIds: [ID!]
}

type UserSubscription {
  add: User
  edit: User
  delete: User
  merge: MergeEvent
}

type MeUserSubscription {
  edit: User
  delete: User
}

type UserPendingSubscription {
  delete: User
  invalidate: OrganizationId
}

enum PortalCapability {
  BYPASS
  READ_TRIALS
  MODIFY_TRIALS
  MODIFY_TRIALS_QUOTA
  MODIFY_COMPETITORS
}

enum OrganizationCapability {
  ADMINISTRATE_ORGANIZATION
  MANAGE_ACCESS
  MANAGE_SUBSCRIPTION
  MANAGE_PLATFORM_REGISTRATION
}

enum ServiceRestriction {
  ACCESS_USER
  MANAGE_ACCESS
  UPLOAD
  DELETE
  UPSERT
}

interface Node {
  id: ID!
}

enum OrderingMode {
  asc
  desc
}

type PageInfo {
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String
  endCursor: String
}

type MergeEvent implements Node {
  id: ID!
  from: ID!
  target: ID!
}