scalar CompetitorId

enum CompetitorOrdering {
  name
  tier
  domain
}

enum CompetitorTier {
  tier1
  tier2
  tier3
}

type Competitor implements Node {
  id: ID!
  name: String!
  tier: CompetitorTier!
  domain: String!
}

type CompetitorEdge {
  cursor: String!
  node: Competitor!
}

type CompetitorConnection {
  totalCount: Int!
  edges: [CompetitorEdge!]!
  pageInfo: PageInfo!
}

input CreateCompetitorInput {
  name: String!
  tier: CompetitorTier!
  domain: String!
}

input UpdateCompetitorInput {
  id: CompetitorId!
  name: String
  tier: CompetitorTier
  domain: String
}

extend type Query {
  competitors(
    first: Int!
    after: ID
    orderBy: CompetitorOrdering!
    orderMode: OrderingMode!
  ): CompetitorConnection! @auth(portalCapa: MODIFY_COMPETITORS)
}

extend type Mutation {
  createCompetitor(input: CreateCompetitorInput!): Competitor!
    @auth(portalCapa: MODIFY_COMPETITORS)
  updateCompetitor(input: UpdateCompetitorInput!): Competitor!
    @auth(portalCapa: MODIFY_COMPETITORS)
  deleteCompetitor(id: CompetitorId!): Competitor!
    @auth(portalCapa: MODIFY_COMPETITORS)
}
