include:
  project: ci/ci-templates
  ref: main
  file: templates/Docker.ci.yml

.build-portal-component:
  extends: .use-docker-in-docker
  only:
    - main
  variables:
    DOCKER_IMAGE_NAME: apps/scred-portal/${SCRED_PORTAL_COMPONENT_NAME}
    DOCKER_IMAGE_VERSION: ${SCRED_PORTAL_VERSION}
    DOCKER_IMAGE_ADDITIONAL_TAGS: latest
    DOCKER_BUILD_DIR: ${SCRED_PORTAL_COMPONENT_NAME}/

variables:
  SCRED_PORTAL_VERSION: 1.0.0

build-portal-api:
  extends: .build-portal-component
  variables:
    SCRED_PORTAL_COMPONENT_NAME: portal-api

build-portal-front:
  extends: .build-portal-component
  variables:
    SCRED_PORTAL_COMPONENT_NAME: portal-front
