{{- if .Values.postgres.backup.enabled }}
{{- $existing := (lookup "barmancloud.cnpg.io/v1" "ObjectStore" .Release.Namespace (printf "%s-barman-objectstore" .Release.Name) ) }}
{{- $defaultPath := printf "s3://%s/backup-%s" .Values.postgres.backup.s3BucketName (now | date "20060102T150405") }}
{{- $destinationPath := dig "spec" "configuration" "destinationPath" $defaultPath $existing }}
apiVersion: barmancloud.cnpg.io/v1
namespace: {{ .Release.Namespace }}
kind: ObjectStore
metadata:
  name: "{{.Release.Name}}-barman-objectstore"
spec:
  retentionPolicy: "{{ .Values.postgres.backup.retentionPolicy }}"
  configuration:
    destinationPath: "{{ $destinationPath }}"
    endpointURL: "{{ .Values.postgres.backup.endpointURL }}"
    {{- with .Values.postgres.backup.s3Credentials  }}
    s3Credentials:
    {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
