
{{- if .Values.elasticsearch.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Namespace}}-{{ .Release.Name }}-es-ingress
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.tls_issuer }}
    external-dns.alpha.kubernetes.io/hostname: {{ tpl .Values.elasticsearch.ingress.host . }}
    external-dns.alpha.kubernetes.io/ttl: "120"
    prometheus.io/probe: "true"
    {{- with .Values.elasticsearch.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingressClass }} 
  rules:
  - host: {{ .Values.elasticsearch.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: elasticsearch-es-http
            port:
              number: 9200
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.elasticsearch.ingress.host }}
    secretName: elasticsearch-cert
{{- end }}
