---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
spec:
  instances: 2
  storage:
    size: {{ .Values.postgres.storage.size }}
  resources:
  {{- toYaml .Values.postgres.resources | nindent 4 }}
  monitoring:
    enablePodMonitor: true
  imageName: "ghcr.io/cloudnative-pg/postgresql:{{ .Values.postgres.version }}"
  imagePullPolicy: "IfNotPresent"
  bootstrap:
    initdb:
      database: xtmhub
      owner: xtmhub
