---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
spec:
  instances: {{ .Values.postgres.replicas }}
  storage:
    size: {{ .Values.postgres.storage.size }}
  resources:
  {{- toYaml .Values.postgres.resources | nindent 4 }}
  monitoring:
    enablePodMonitor: true
  imageName: "ghcr.io/cloudnative-pg/postgresql:{{ .Values.postgres.version }}"
  imagePullPolicy: "IfNotPresent"
  primaryUpdateMethod: switchover
  primaryUpdateStrategy: unsupervised
  {{- if .Values.postgres.spec.bootstrap }}
  bootstrap:
    {{- .Values.postgres.spec.bootstrap | toYaml | nindent 4 }}
  {{- end }}
  {{- if .Values.postgres.spec.externalClusters }}
  externalClusters:
    {{- .Values.postgres.spec.externalClusters | toYaml | nindent 4 }}
  {{- end }}
  {{- if .Values.postgres.spec.plugins }}
  plugins:
    {{- .Values.postgres.spec.plugins | toYaml | nindent 4 }}
  {{- end }}
