apiVersion: v1
kind: Secret
metadata:
  name: portal-api-config
type: Opaque
stringData:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "postgresql-app") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $password := (get $secretData "password") }}
  production.json: |-
    {
      "port": 4001,
      "admin": {
        "email": "{{ .Values.cloudportal.api.email }}",
        "password": "{{ .Values.cloudportal.api.password }}"
      },
      "database": {
        "host": "postgresql-rw.{{ .Release.Namespace}}",
        "port": 5432,
        "user": "cloudportal",
        "password": "{{ $password | b64dec }}",
        "database": "cloudportal"
      }
    }
