apiVersion: v1
kind: Secret
metadata:
  name: xtmhub-api-config
type: Opaque
data:
  ADMIN_EMAIL: {{.Values.xtmhub.api.admin.email | b64enc }}
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "xtmhub-api-config") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $adminpass := (get $secretData "ADMIN_PASSWORD") | default (randAlphaNum 16 | b64enc) }}
  ADMIN_PASSWORD: {{ $adminpass }}
  OIDC_CLIENT_SECRET: {{.Values.xtmhub.api.secret.OIDC_CLIENT_SECRET | b64enc }}