apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
type: Opaque
data:
  accessKey: {{ "minio" | b64enc }}
{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "minio-credentials") | default dict }}
{{- $secretData := (get $secretObj "data") | default dict }}
{{- $minioSecret := (get $secretData "secretKey") | default (randAlphaNum 12 | b64enc) }}
{{- $minioSecretDec := ($minioSecret | b64dec) }}
  secretKey: {{ $minioSecret }}
    {{- $config := printf "%s%s" "export MINIO_ROOT_USER=minio\nexport MINIO_ROOT_PASSWORD=" $minioSecretDec }}
  config.env: {{ $config | b64enc }}