apiVersion: v1
kind: Secret
metadata:
  name: portal-api-config
type: Opaque
data:
  ADMIN_EMAIL: {{.Values.cloudportal.api.admin.email | b64enc }}
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace portal-api-config) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $adminpass := (get $secretData "ADMIN_PASSWORD") | default (randAlphaNum 16 | b64enc) }}
  ADMIN_PASSWORD: {{ $adminpass }}
