import AppContext from '@/components/app-context';
import * as React from 'react';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <AppContext>{children}</AppContext>;
}
