scalar SubscriptionId

enum SubscriptionOrdering {
  organization_name
  start_date
  end_date
  service_name
  service_provider
  service_type
  service_description
}
type SubscriptionModel implements Node {
  id: ID!
  organization_id: OrganizationId!
  service_instance_id: ServiceInstanceId!
  start_date: Date
  end_date: Date
  organization: Organization!
  service_url: String!
  service_instance: ServiceInstance
  subscription_capability: [SubscriptionCapability]
  user_service: [UserService]!
}

type SubscriptionEdge {
  cursor: String!
  node: SubscriptionModel!
}

input CreateSubscriptionInput {
  service_instance_id: ServiceInstanceId!
  organization_id: [OrganizationId!]!
  capability_ids: [ServiceCapabilityId]
  start_date: Date!
  end_date: Date
}

input UpdateSubscriptionInput {
  start_date: Date
  end_date: Date
  capability_ids: [ServiceCapabilityId]
}

type Mutation {
  addSubscription(service_instance_id: ServiceInstanceId): ServiceInstance
    @auth(orgaCapa: [ADMINISTRATE_ORGANIZATION, MANAGE_SUBSCRIPTION])
  createSubscription(input: CreateSubscriptionInput): [SubscriptionModel]
    @auth(portalCapa: [BYPASS])
  updateSubscription(
    subscription_id: SubscriptionId!
    input: UpdateSubscriptionInput!
  ): SubscriptionModel
    @auth(orgaCapa: [ADMINISTRATE_ORGANIZATION, MANAGE_SUBSCRIPTION])
    @service_capa(requires: [MANAGE_ACCESS])
  deleteSubscription(subscription_ids: [SubscriptionId!]!): [SubscriptionModel]
    @auth(orgaCapa: [ADMINISTRATE_ORGANIZATION, MANAGE_SUBSCRIPTION])
    @service_capa(requires: [MANAGE_ACCESS])
}

type SubscriptionConnection {
  totalCount: Int!
  edges: [SubscriptionEdge!]!
  pageInfo: PageInfo!
}
enum SubscriptionFilterKey {
  organization_name
  service_instance_id
}
input SubscriptionFilter {
  key: SubscriptionFilterKey!
  value: [String!]!
}

type Query {
  subscriptionById(subscription_id: SubscriptionId): SubscriptionModel @auth
  subscriptions(
    first: Int!
    after: ID
    orderBy: SubscriptionOrdering!
    orderMode: OrderingMode!
    searchTerm: String
    filters: [SubscriptionFilter!]
  ): SubscriptionConnection! @auth
}
