scalar SubscriptionId

enum SubscriptionOrdering {
  organization_name
  start_date
  end_date
  service_name
  service_provider
  service_type
  service_description
}
type SubscriptionModel implements Node {
  id: ID!
  organization_id: ID!
  service_instance_id: ID!
  start_date: Date
  end_date: Date
  organization: Organization!
  service_url: String!
  service_instance: ServiceInstance
  subscription_capability: [SubscriptionCapability]
  user_service: [UserService]!
}

type SubscriptionEdge {
  cursor: String!
  node: SubscriptionModel!
}

input AddSubscriptionInput {
  service_instance_id: ServiceInstanceId!
  organization_id: OrganizationId!
  capability_ids: [ServiceCapabilityId]
  start_date: Date!
  end_date: Date
}

type Mutation {
  addSubscription(service_instance_id: ServiceInstanceId): ServiceInstance
    @auth(orgaCapa: [ADMINISTRATE_ORGANIZATION, MANAGE_SUBSCRIPTION])
  createSubscription(input: AddSubscriptionInput): SubscriptionModel
    @auth(portalCapa: [BYPASS])
  deleteSubscription(subscription_id: SubscriptionId!): SubscriptionModel
    @auth(orgaCapa: [ADMINISTRATE_ORGANIZATION, MANAGE_SUBSCRIPTION])
    @service_capa(requires: [MANAGE_ACCESS])
}

type SubscriptionConnection {
  totalCount: Int!
  edges: [SubscriptionEdge!]!
  pageInfo: PageInfo!
}
enum SubscriptionFilterKey {
  organization_name
  service_instance_id
}
input SubscriptionFilter {
  key: SubscriptionFilterKey
  value: [String!]!
}

type Query {
  subscriptionById(subscription_id: ID): SubscriptionModel @auth
  subscriptions(
    first: Int!
    after: ID
    orderBy: SubscriptionOrdering!
    orderMode: OrderingMode!
    searchTerm: String
    filters: [SubscriptionFilter!]
  ): SubscriptionConnection! @auth
}
