// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { DocumentId } from './Document';
import type { LabelId } from './Label';

/** Represents the table public.Document_Label */
export default interface DocumentLabel {
  document_id: DocumentId;

  label_id: LabelId;
}

/** Represents the initializer for the table public.Document_Label */
export interface DocumentLabelInitializer {
  document_id: DocumentId;

  label_id: LabelId;
}

/** Represents the mutator for the table public.Document_Label */
export interface DocumentLabelMutator {
  document_id?: DocumentId;

  label_id?: LabelId;
}
