// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ServiceId } from './Service';

/** Identifier type for public.Document */
export type DocumentId = string & { __brand: 'DocumentId' };

/** Represents the table public.Document */
export default interface Document {
  id: DocumentId;

  uploader_id: string | null;

  service_id: ServiceId | null;

  description: string | null;

  file_name: string | null;

  minio_name: string | null;

  active: boolean | null;

  created_at: Date;

  download_number: number | null;

  remover_id: string | null;

  mime_type: string | null;
}

/** Represents the initializer for the table public.Document */
export interface DocumentInitializer {
  /** Default value: gen_random_uuid() */
  id?: DocumentId;

  uploader_id?: string | null;

  service_id?: ServiceId | null;

  description?: string | null;

  file_name?: string | null;

  minio_name?: string | null;

  /** Default value: true */
  active?: boolean | null;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;

  /** Default value: 0 */
  download_number?: number | null;

  remover_id?: string | null;

  mime_type?: string | null;
}

/** Represents the mutator for the table public.Document */
export interface DocumentMutator {
  id?: DocumentId;

  uploader_id?: string | null;

  service_id?: ServiceId | null;

  description?: string | null;

  file_name?: string | null;

  minio_name?: string | null;

  active?: boolean | null;

  created_at?: Date;

  download_number?: number | null;

  remover_id?: string | null;

  mime_type?: string | null;
}
