// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UserServiceId } from './UserService';

/** Identifier type for public.Generic_Service_Capability */
export type GenericServiceCapabilityId = string & {
  __brand: 'GenericServiceCapabilityId';
};

/** Represents the table public.Generic_Service_Capability */
export default interface GenericServiceCapability {
  id: GenericServiceCapabilityId;

  user_service_id: UserServiceId | null;

  service_capability_name: string | null;
}

/** Represents the initializer for the table public.Generic_Service_Capability */
export interface GenericServiceCapabilityInitializer {
  id: GenericServiceCapabilityId;

  user_service_id?: UserServiceId | null;

  /** Default value: 'ACCESS_SERVICE'::text */
  service_capability_name?: string | null;
}

/** Represents the mutator for the table public.Generic_Service_Capability */
export interface GenericServiceCapabilityMutator {
  id?: GenericServiceCapabilityId;

  user_service_id?: UserServiceId | null;

  service_capability_name?: string | null;
}
