// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.Object_Label */
export type ObjectLabelObjectId = string & { __brand: 'ObjectLabelObjectId' };

/** Identifier type for public.Object_Label */
export type ObjectLabelLabelId = string & { __brand: 'ObjectLabelLabelId' };

/** Represents the table public.Object_Label */
export default interface ObjectLabel {
  object_id: ObjectLabelObjectId;

  label_id: ObjectLabelLabelId;
}

/** Represents the initializer for the table public.Object_Label */
export interface ObjectLabelInitializer {
  object_id: ObjectLabelObjectId;

  label_id: ObjectLabelLabelId;
}

/** Represents the mutator for the table public.Object_Label */
export interface ObjectLabelMutator {
  object_id?: ObjectLabelObjectId;

  label_id?: ObjectLabelLabelId;
}
