// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UserServiceId } from './UserService';

/** Identifier type for public.Service_Capability */
export type ServiceCapabilityId = string & { __brand: 'ServiceCapabilityId' };

/** Represents the table public.Service_Capability */
export default interface ServiceCapability {
  id: ServiceCapabilityId;

  user_service_id: UserServiceId | null;

  service_capability_name: string | null;
}

/** Represents the initializer for the table public.Service_Capability */
export interface ServiceCapabilityInitializer {
  id: ServiceCapabilityId;

  user_service_id?: UserServiceId | null;

  /** Default value: 'ACCESS_SERVICE'::text */
  service_capability_name?: string | null;
}

/** Represents the mutator for the table public.Service_Capability */
export interface ServiceCapabilityMutator {
  id?: ServiceCapabilityId;

  user_service_id?: UserServiceId | null;

  service_capability_name?: string | null;
}
