// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ServiceId } from './Service';

/** Identifier type for public.Service_Link */
export type ServiceLinkId = string & { __brand: 'ServiceLinkId' };

/** Represents the table public.Service_Link */
export default interface ServiceLink {
  id: ServiceLinkId;

  service_id: ServiceId | null;

  url: string | null;

  name: string | null;
}

/** Represents the initializer for the table public.Service_Link */
export interface ServiceLinkInitializer {
  /** Default value: gen_random_uuid() */
  id?: ServiceLinkId;

  service_id?: ServiceId | null;

  url?: string | null;

  name?: string | null;
}

/** Represents the mutator for the table public.Service_Link */
export interface ServiceLinkMutator {
  id?: ServiceLinkId;

  service_id?: ServiceId | null;

  url?: string | null;

  name?: string | null;
}
