// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.Service */
export type ServiceId = string & { __brand: 'ServiceId' };

/** Represents the table public.Service */
export default interface Service {
  id: ServiceId;

  name: string;

  description: string | null;

  provider: string | null;

  type: string | null;

  creation_status: string | null;

  subscription_service_type: string | null;
}

/** Represents the initializer for the table public.Service */
export interface ServiceInitializer {
  id: ServiceId;

  name: string;

  description?: string | null;

  /** Default value: 'SCRED'::character varying */
  provider?: string | null;

  /** Default value: 'Intel'::character varying */
  type?: string | null;

  /** Default value: 'READY'::text */
  creation_status?: string | null;

  /** Default value: 'SUBSCRIPTABLE_BACKOFFICE'::text */
  subscription_service_type?: string | null;
}

/** Represents the mutator for the table public.Service */
export interface ServiceMutator {
  id?: ServiceId;

  name?: string;

  description?: string | null;

  provider?: string | null;

  type?: string | null;

  creation_status?: string | null;

  subscription_service_type?: string | null;
}
