// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ServiceInstanceId } from './ServiceInstance';

/** Identifier type for public.Service_Price */
export type ServicePriceId = string & { __brand: 'ServicePriceId' };

/** Represents the table public.Service_Price */
export default interface ServicePrice {
  id: ServicePriceId;

  service_instance_id: ServiceInstanceId | null;

  fee_type: string | null;

  start_date: Date | null;

  price: number | null;
}

/** Represents the initializer for the table public.Service_Price */
export interface ServicePriceInitializer {
  /** Default value: gen_random_uuid() */
  id?: ServicePriceId;

  service_instance_id?: ServiceInstanceId | null;

  /** Default value: 'MONTHLY'::text */
  fee_type?: string | null;

  start_date?: Date | null;

  price?: number | null;
}

/** Represents the mutator for the table public.Service_Price */
export interface ServicePriceMutator {
  id?: ServicePriceId;

  service_instance_id?: ServiceInstanceId | null;

  fee_type?: string | null;

  start_date?: Date | null;

  price?: number | null;
}
