// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.ServiceInstance */
export type ServiceInstanceId = string & { __brand: 'ServiceInstanceId' };

/** Represents the table public.ServiceInstance */
export default interface ServiceInstance {
  id: ServiceInstanceId;

  name: string;

  description: string | null;

  provider: string | null;

  type: string | null;

  creation_status: string | null;

  public: boolean | null;

  join_type: string | null;

  tags: string[] | null;
}

/** Represents the initializer for the table public.ServiceInstance */
export interface ServiceInstanceInitializer {
  id: ServiceInstanceId;

  name: string;

  description?: string | null;

  /** Default value: 'SCRED'::character varying */
  provider?: string | null;

  /** Default value: 'Intel'::character varying */
  type?: string | null;

  /** Default value: 'READY'::text */
  creation_status?: string | null;

  /** Default value: false */
  public?: boolean | null;

  /** Default value: 'JOIN_INVITE'::text */
  join_type?: string | null;

  tags?: string[] | null;
}

/** Represents the mutator for the table public.ServiceInstance */
export interface ServiceInstanceMutator {
  id?: ServiceInstanceId;

  name?: string;

  description?: string | null;

  provider?: string | null;

  type?: string | null;

  creation_status?: string | null;

  public?: boolean | null;

  join_type?: string | null;

  tags?: string[] | null;
}
