// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type OrganizationId } from './Organization';
import { type ServiceId } from './Service';

/** Identifier type for public.Subscription */
export type SubscriptionId = string & { __brand: 'SubscriptionId' };

/** Represents the table public.Subscription */
export default interface Subscription {
  id: SubscriptionId;

  organization_id: OrganizationId | null;

  service_id: ServiceId | null;

  start_date: Date | null;

  end_date: Date | null;

  status: string | null;
}

/** Represents the initializer for the table public.Subscription */
export interface SubscriptionInitializer {
  id: SubscriptionId;

  organization_id?: OrganizationId | null;

  service_id?: ServiceId | null;

  start_date?: Date | null;

  end_date?: Date | null;

  /** Default value: 'ACCEPTED'::text */
  status?: string | null;
}

/** Represents the mutator for the table public.Subscription */
export interface SubscriptionMutator {
  id?: SubscriptionId;

  organization_id?: OrganizationId | null;

  service_id?: ServiceId | null;

  start_date?: Date | null;

  end_date?: Date | null;

  status?: string | null;
}
