// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { RolePortalId } from './RolePortal';
import type { UserId } from './User';

/** Identifier type for public.User_RolePortal */
export type UserRolePortalId = number & { __brand: 'UserRolePortalId' };

/** Represents the table public.User_RolePortal */
export default interface UserRolePortal {
  id: UserRolePortalId;

  user_id: UserId | null;

  role_portal_id: RolePortalId | null;
}

/** Represents the initializer for the table public.User_RolePortal */
export interface UserRolePortalInitializer {
  /** Default value: nextval('"User_RolePortal_id_seq"'::regclass) */
  id?: UserRolePortalId;

  user_id?: UserId | null;

  role_portal_id?: RolePortalId | null;
}

/** Represents the mutator for the table public.User_RolePortal */
export interface UserRolePortalMutator {
  id?: UserRolePortalId;

  user_id?: UserId | null;

  role_portal_id?: RolePortalId | null;
}
