// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { OrganizationId } from './Organization';

/** Identifier type for public.User */
export type UserId = string & { __brand: 'UserId' };

/** Represents the table public.User */
export default interface User {
  id: UserId;

  email: string | null;

  salt: string;

  password: string;

  first_name: string | null;

  last_name: string | null;

  selected_organization_id: OrganizationId;

  picture: string | null;
}

/** Represents the initializer for the table public.User */
export interface UserInitializer {
  id: UserId;

  email?: string | null;

  salt: string;

  password: string;

  first_name?: string | null;

  last_name?: string | null;

  selected_organization_id: OrganizationId;

  picture?: string | null;
}

/** Represents the mutator for the table public.User */
export interface UserMutator {
  id?: UserId;

  email?: string | null;

  salt?: string;

  password?: string;

  first_name?: string | null;

  last_name?: string | null;

  selected_organization_id?: OrganizationId;

  picture?: string | null;
}
