// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UserId } from './User';
import type { SubscriptionId } from './Subscription';

/** Identifier type for public.User_Service */
export type UserServiceId = string & { __brand: 'UserServiceId' };

/** Represents the table public.User_Service */
export default interface UserService {
  id: UserServiceId;

  user_id: UserId | null;

  subscription_id: SubscriptionId | null;

  service_personal_data: unknown | null;
}

/** Represents the initializer for the table public.User_Service */
export interface UserServiceInitializer {
  id: UserServiceId;

  user_id?: UserId | null;

  subscription_id?: SubscriptionId | null;

  service_personal_data?: unknown | null;
}

/** Represents the mutator for the table public.User_Service */
export interface UserServiceMutator {
  id?: UserServiceId;

  user_id?: UserId | null;

  subscription_id?: SubscriptionId | null;

  service_personal_data?: unknown | null;
}
