scalar UserServiceId

enum UserServiceOrdering {
  first_name
  last_name
  email
  service_name
  service_provider
  service_type
  service_description
  subscription_status
  ordering
}

input UserServiceAddInput {
  email: [String!]!
  capabilities: [String!]
  subscription_id: SubscriptionId!
}

input UserServiceAddYourselfInput {
  email: [String!]!
  serviceInstanceId: ServiceInstanceId
}

input UserServicesDeleteInput {
  userServiceIds: [UserServiceId!]!
}
input UserServiceEditInput {
  userServiceId: UserServiceId!
  capabilities: [String!]!
}

type Mutation {
  addUserService(
    input: UserServiceAddInput!
    service_instance_id: ServiceInstanceId!
  ): [UserService]
    @auth(
      portalCapa: [BYPASS]
      orgaCapa: [ADMINISTRATE_ORGANIZATION, MANAGE_SUBSCRIPTION]
    )
    @service_capa(requires: [MANAGE_ACCESS])
  editUserService(
    input: UserServiceEditInput!
    service_instance_id: ServiceInstanceId!
  ): UserService
    @auth(
      portalCapa: [BYPASS]
      orgaCapa: [ADMINISTRATE_ORGANIZATION, MANAGE_SUBSCRIPTION]
    )
    @service_capa(requires: [MANAGE_ACCESS])
  deleteUserServices(
    input: UserServicesDeleteInput!
    service_instance_id: ServiceInstanceId!
  ): [UserService]
    @auth(
      portalCapa: [BYPASS]
      orgaCapa: [ADMINISTRATE_ORGANIZATION, MANAGE_SUBSCRIPTION]
    )
    @service_capa(requires: [MANAGE_ACCESS])
}
type Query {
  userServiceFromSubscription(
    first: Int!
    after: ID
    orderBy: UserServiceOrdering!
    orderMode: OrderingMode!
    subscription_id: SubscriptionId!
  ): UserServiceConnection @auth
}
type UserServiceConnection {
  totalCount: Int!
  edges: [UserServiceEdge!]!
  pageInfo: PageInfo!
}

type UserServiceEdge {
  cursor: String!
  node: UserService
}

type UserService implements Node {
  id: ID!
  subscription_id: ID!
  user_id: ID!
  user: User
  subscription: SubscriptionModel
  user_service_capability: [UserServiceCapability]
  ordering: Int
}

type UserServiceDeleted implements Node {
  id: ID!
  subscription_id: ID!
  user_id: ID!
}
