import {
  type UseCasesListQueryVariables,
  useUseCasesListQuery,
} from '@graphql/generated';

export const useCaseListKeys = {
  all: () => ['UseCasesList'] as const, // the key is automatically generated by codegen
  list: (variables: UseCasesListQueryVariables) =>
    useUseCasesListQuery.getKey(variables),
};
