enum UserOrdering {
  email
  first_name
  last_name
  disabled
  country
  last_login
}

type Capability implements Node {
  id: ID!
  name: Restriction!
}

type OrganizationCapabilities implements Node {
  id: ID!
  organization: Organization!
  capabilities: [OrganizationCapability!]
}

type User implements Node {
  id: ID!
  email: String!
  first_name: String
  last_name: String
  picture: String
  country: String
  disabled: Boolean
  selected_organization_id: String
  organizations: [Organization!]
  organization_capabilities: [OrganizationCapabilities!]
  capabilities: [Capability!]
  roles_portal: [RolePortal!]
  selected_org_capabilities: [OrganizationCapability!]
  last_login: Date
  pending_organization_id: ID
}

type UserEdge {
  cursor: String!
  node: User!
}

type UserConnection {
  totalCount: Int!
  edges: [UserEdge!]!
  pageInfo: PageInfo!
}

input UsersWithCapabilitiesInOrganizationInput {
  organizationId: ID!
  capabilities: [OrganizationCapability!]!
}

type Query {
  me: User
  usersWithCapabilitiesInOrganization(
    input: UsersWithCapabilitiesInOrganizationInput!
  ): [User!]!
  users(
    first: Int!
    after: ID
    orderBy: UserOrdering!
    orderMode: OrderingMode!
    searchTerm: String
    filters: [Filter!]
  ): UserConnection! @auth
  pendingUsers(
    first: Int!
    after: ID
    orderBy: UserOrdering!
    orderMode: OrderingMode!
    searchTerm: String
    filters: [Filter!]
  ): UserConnection! @auth(requires: [ADMINISTRATE_ORGANIZATION, MANAGE_ACCESS])
  userHasOrganizationWithSubscription: Boolean! @auth
}

input AdminEditUserInput {
  disabled: Boolean
  first_name: String
  last_name: String
  email: String
  organization_capabilities: [OrganizationCapabilitiesInput!]
}

input EditUserCapabilitiesInput {
  capabilities: [String!]
}

input EditMeUserInput {
  first_name: String
  last_name: String
  picture: String
  country: String
}

input OrganizationCapabilitiesInput {
  organization_id: ID!
  capabilities: [String!]
}

input AddUserInput {
  email: String!
  password: String
  capabilities: [String!]
}
input AdminAddUserInput {
  email: String!
  first_name: String
  last_name: String
  password: String
  organization_capabilities: [OrganizationCapabilitiesInput!]
}

input BulkPendingUserFromOrganizationInput {
  ids: [ID!]
  searchTerm: String
  filters: [Filter!]
  excludedIds: [ID!]
}

type Mutation {
  # Admin
  adminAddUser(input: AdminAddUserInput!): User @auth(requires: [BYPASS])
  adminEditUser(id: ID!, input: AdminEditUserInput!): User!
    @auth(requires: [BYPASS])

  # Management
  mergeTest(from: ID!, target: ID!): ID!
    @auth(requires: [ADMINISTRATE_ORGANIZATION, MANAGE_ACCESS])
  addUser(input: AddUserInput!): User
    @auth(requires: [ADMINISTRATE_ORGANIZATION, MANAGE_ACCESS])
  editUserCapabilities(id: ID!, input: EditUserCapabilitiesInput!): User!
    @auth(requires: [ADMINISTRATE_ORGANIZATION, MANAGE_ACCESS])
  changeSelectedOrganization(organization_id: ID!): User @auth
  bulkRemovePendingUserFromOrganization(
    input: BulkPendingUserFromOrganizationInput
  ): Success @auth(requires: [ADMINISTRATE_ORGANIZATION, MANAGE_ACCESS])
  bulkAcceptPendingUserInOrganization(
    input: BulkPendingUserFromOrganizationInput
  ): Success @auth(requires: [ADMINISTRATE_ORGANIZATION, MANAGE_ACCESS])
  removePendingUserFromOrganization(user_id: ID!, organization_id: ID!): User
    @auth(requires: [ADMINISTRATE_ORGANIZATION, MANAGE_ACCESS])
  removeUserFromOrganization(user_id: ID!, organization_id: ID!): User
    @auth(requires: [ADMINISTRATE_ORGANIZATION, MANAGE_ACCESS])

  # Profile
  editMeUser(input: EditMeUserInput!): User! @auth
  resetPassword: Success! @auth
  requestTransferPersonalSpace(new_email: String): Success! @auth
  transferPersonalSpace(requestId: ID!): Success! @auth

  # Login
  login(email: String!, password: String): User
  logout: ID! @auth

  # Contact
  contactUs: Success!
}

type UserSubscription {
  add: User
  edit: User
  delete: User
  merge: MergeEvent
}

type MeUserSubscription {
  edit: User
  delete: User
}

type UserPendingSubscription {
  delete: User
  invalidate: OrganizationId
}

type Subscription {
  User(organizationId: ID): UserSubscription
    @auth(requires: [ADMINISTRATE_ORGANIZATION, MANAGE_ACCESS])
  MeUser: MeUserSubscription @auth
  UserPending(organizationId: ID!): UserPendingSubscription
    @auth(requires: [ADMINISTRATE_ORGANIZATION, MANAGE_ACCESS])
}
