services:
  portal-postgres:
    container_name: portal-postgres
    image: postgres:17.2
    volumes:
      - pgdata:/data/postgres
    environment:
      - POSTGRES_USER=portal
      - POSTGRES_PASSWORD=portal-password
      - POSTGRES_DB=cloud-portal
      - PGDATA=/data/postgres
    restart: unless-stopped
    ports:
      - "5434:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: unless-stopped
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: portal@filigran.io
      PGADMIN_DEFAULT_PASSWORD: portal-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  portal-minio:
    image: "minio/minio:RELEASE.2024-08-03T04-33-23Z"
    environment:
      MINIO_ROOT_USER: portal
      MINIO_ROOT_PASSWORD: changeme
    ports:
      - "9002:9000"
      - "8902:8902"
    volumes:
      - "minio:/data/minio"
    command: 'minio server /data/minio --console-address ":8902"'
    restart: always
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 10s
      timeout: 5s
      retries: 10

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  portal-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.3
    container_name: portal-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.ml.enabled=false
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ports:
      - "9202:9200"
      - "9302:9300"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    restart: unless-stopped

volumes:
  pgdata:
    driver: local
  pgadmin-data:
    driver: local
  minio:
    driver: local
  elasticsearch-data:
    driver: local
