version: '3'
services:

  portal-postgres:
    container_name: portal-postgres
    image: postgres:16.0
    volumes:
      - pgdata:/data/postgres
    environment:
      - POSTGRES_USER=portal
      - POSTGRES_PASSWORD=portal-password
      - POSTGRES_DB=cloud-portal
      - PGDATA=/data/postgres
    restart: unless-stopped
    ports:
      - "5432:5432"

  portal-minio:
    image: 'minio/minio:RELEASE.2024-08-03T04-33-23Z'
    environment:
      MINIO_ROOT_USER: portal
      MINIO_ROOT_PASSWORD: changeme
    ports:
      - '9000:9000'
      - '8900:8900'
    volumes:
      - 'minio:/data/minio'
    command: 'minio server /data/minio --console-address ":8900"'
    restart: always
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
    driver: local
  minio:
    driver: local
