version: '3'
services:
  portal-api:
    container_name: portal-api
    build: ../portal-api/.
    ports:
      - "4001:4001"
    depends_on:
      - portal-postgres

  portal-postgres:
    container_name: portal-postgres
    image: postgres:16.0
    volumes:
      - pgdata:/data/postgres
    environment:
      - POSTGRES_USER=portal
      - POSTGRES_PASSWORD=portal-password
      - POSTGRES_DB=cloud-portal
      - PGDATA=/data/postgres
    restart: unless-stopped
    ports:
      - "5432:5432"

volumes:
  pgdata:
    driver: local
