// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UserId } from './User';
import type { OrganizationId } from './Organization';
import type { ServiceInstanceId } from './ServiceInstance';
import type { DeploymentRequestDeploymentType, PlatformIdentifier, DeploymentRequestPlatformRegion, DeploymentRequestActivitySector, DeploymentRequestJobTitle, DeploymentRequestUseCase, DeploymentRequestHubStatus, DeploymentRequestPlatformState, DeploymentRequestSource } from '../../../__generated__/resolvers-types';

/** Identifier type for public.DeploymentRequest */
export type DeploymentRequestId = string & { __brand: 'public.DeploymentRequest' };

/** Represents the table public.DeploymentRequest */
export default interface DeploymentRequest {
  id: DeploymentRequestId;

  user_requester_id: UserId;

  organization_requester_id: OrganizationId;

  service_instance_id: ServiceInstanceId;

  type: DeploymentRequestDeploymentType;

  request_date: Date;

  start_date: Date | null;

  end_date: Date | null;

  platform_identifier: PlatformIdentifier | null;

  region: DeploymentRequestPlatformRegion;

  activity_sector: DeploymentRequestActivitySector | null;

  platform_token: string;

  platform_id: string | null;

  failure_reason: string | null;

  job_title: DeploymentRequestJobTitle | null;

  use_case: DeploymentRequestUseCase | null;

  hub_status: DeploymentRequestHubStatus;

  target_state: DeploymentRequestPlatformState | null;

  actual_state: DeploymentRequestPlatformState | null;

  ordering: number;

  counts_in_orga_quota: boolean;

  cancellation_user_id: string | null;

  cancellation_date: Date | null;

  cancellation_reason: string | null;

  source: DeploymentRequestSource;

  parent_id: DeploymentRequestId | null;

  url: string | null;
}

/** Represents the initializer for the table public.DeploymentRequest */
export interface DeploymentRequestInitializer {
  id: DeploymentRequestId;

  user_requester_id: UserId;

  organization_requester_id: OrganizationId;

  service_instance_id: ServiceInstanceId;

  type: DeploymentRequestDeploymentType;

  /** Default value: CURRENT_TIMESTAMP */
  request_date?: Date;

  start_date?: Date | null;

  end_date?: Date | null;

  platform_identifier?: PlatformIdentifier | null;

  region: DeploymentRequestPlatformRegion;

  activity_sector?: DeploymentRequestActivitySector | null;

  platform_token: string;

  platform_id?: string | null;

  failure_reason?: string | null;

  job_title?: DeploymentRequestJobTitle | null;

  use_case?: DeploymentRequestUseCase | null;

  hub_status?: DeploymentRequestHubStatus;

  target_state?: DeploymentRequestPlatformState | null;

  actual_state?: DeploymentRequestPlatformState | null;

  /** Default value: 0 */
  ordering?: number;

  /** Default value: true */
  counts_in_orga_quota?: boolean;

  cancellation_user_id?: string | null;

  cancellation_date?: Date | null;

  cancellation_reason?: string | null;

  source?: DeploymentRequestSource;

  parent_id?: DeploymentRequestId | null;

  url?: string | null;
}

/** Represents the mutator for the table public.DeploymentRequest */
export interface DeploymentRequestMutator {
  id?: DeploymentRequestId;

  user_requester_id?: UserId;

  organization_requester_id?: OrganizationId;

  service_instance_id?: ServiceInstanceId;

  type?: DeploymentRequestDeploymentType;

  request_date?: Date;

  start_date?: Date | null;

  end_date?: Date | null;

  platform_identifier?: PlatformIdentifier | null;

  region?: DeploymentRequestPlatformRegion;

  activity_sector?: DeploymentRequestActivitySector | null;

  platform_token?: string;

  platform_id?: string | null;

  failure_reason?: string | null;

  job_title?: DeploymentRequestJobTitle | null;

  use_case?: DeploymentRequestUseCase | null;

  hub_status?: DeploymentRequestHubStatus;

  target_state?: DeploymentRequestPlatformState | null;

  actual_state?: DeploymentRequestPlatformState | null;

  ordering?: number;

  counts_in_orga_quota?: boolean;

  cancellation_user_id?: string | null;

  cancellation_date?: Date | null;

  cancellation_reason?: string | null;

  source?: DeploymentRequestSource;

  parent_id?: DeploymentRequestId | null;

  url?: string | null;
}
