// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ServiceInstanceId } from './ServiceInstance';

/** Identifier type for public.Document */
export type DocumentId = string & { __brand: 'public.Document' };

/** Represents the table public.Document */
export default interface Document {
  id: DocumentId;

  uploader_id: string | null;

  service_instance_id: ServiceInstanceId | null;

  description: string | null;

  file_name: string | null;

  minio_name: string | null;

  active: boolean;

  created_at: Date;

  remover_id: string | null;

  mime_type: string | null;

  name: string | null;

  updated_at: Date | null;

  updater_id: string | null;

  short_description: string | null;

  slug: string | null;

  uploader_organization_id: string | null;

  type: string;

  source_type: string | null;

  is_decommissioned: boolean;

  version: string | null;

  tags: string[];
}

/** Represents the initializer for the table public.Document */
export interface DocumentInitializer {
  /** Default value: gen_random_uuid() */
  id?: DocumentId;

  uploader_id?: string | null;

  service_instance_id?: ServiceInstanceId | null;

  description?: string | null;

  file_name?: string | null;

  minio_name?: string | null;

  /** Default value: true */
  active?: boolean;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;

  remover_id?: string | null;

  mime_type?: string | null;

  name?: string | null;

  updated_at?: Date | null;

  updater_id?: string | null;

  short_description?: string | null;

  slug?: string | null;

  uploader_organization_id?: string | null;

  type: string;

  /** Default value: 'internal'::character varying */
  source_type?: string | null;

  /** Default value: false */
  is_decommissioned?: boolean;

  version?: string | null;

  /** Default value: '{}'::text[] */
  tags?: string[];
}

/** Represents the mutator for the table public.Document */
export interface DocumentMutator {
  id?: DocumentId;

  uploader_id?: string | null;

  service_instance_id?: ServiceInstanceId | null;

  description?: string | null;

  file_name?: string | null;

  minio_name?: string | null;

  active?: boolean;

  created_at?: Date;

  remover_id?: string | null;

  mime_type?: string | null;

  name?: string | null;

  updated_at?: Date | null;

  updater_id?: string | null;

  short_description?: string | null;

  slug?: string | null;

  uploader_organization_id?: string | null;

  type?: string;

  source_type?: string | null;

  is_decommissioned?: boolean;

  version?: string | null;

  tags?: string[];
}
