// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { FiligranProduct } from '../../../__generated__/resolvers-types';
import type { UserId } from './User';
import type { VotableFeatureId } from './VotableFeature';
import type { VotingRoundId } from './VotingRound';

/** Represents the table public.FeatureVote */
export default interface FeatureVote {
  user_id: UserId;

  voting_round_id: VotingRoundId;

  votable_feature_id: VotableFeatureId;

  product: FiligranProduct;

  created_at: Date;
}

/** Represents the initializer for the table public.FeatureVote */
export interface FeatureVoteInitializer {
  user_id: UserId;

  voting_round_id: VotingRoundId;

  votable_feature_id: VotableFeatureId;

  product: FiligranProduct;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;
}

/** Represents the mutator for the table public.FeatureVote */
export interface FeatureVoteMutator {
  user_id?: UserId;

  voting_round_id?: VotingRoundId;

  votable_feature_id?: VotableFeatureId;

  product?: FiligranProduct;

  created_at?: Date;
}
