// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ManifestType } from '../../../__generated__/resolvers-types';

/** Identifier type for public.Manifest */
export type ManifestId = string & { __brand: 'public.Manifest' };

/** Represents the table public.Manifest */
export default interface Manifest {
  id: ManifestId;

  product: string;

  version: string;

  type: ManifestType;

  name: string;

  created_at: Date;

  version_padded: string;
}

/** Represents the initializer for the table public.Manifest */
export interface ManifestInitializer {
  /** Default value: gen_random_uuid() */
  id?: ManifestId;

  product: string;

  version: string;

  type: ManifestType;

  name: string;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;

  version_padded: string;
}

/** Represents the mutator for the table public.Manifest */
export interface ManifestMutator {
  id?: ManifestId;

  product?: string;

  version?: string;

  type?: ManifestType;

  name?: string;

  created_at?: Date;

  version_padded?: string;
}
