// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { NewsFeedItemType, PlatformIdentifier } from '../../../__generated__/resolvers-types';

/** Identifier type for public.NewsFeedItem */
export type NewsFeedItemId = string & { __brand: 'public.NewsFeedItem' };

/** Represents the table public.NewsFeedItem */
export default interface NewsFeedItem {
  id: NewsFeedItemId;

  type: NewsFeedItemType;

  platform_identifier: PlatformIdentifier;

  title: string;

  creation_date: Date;

  tags: string[];

  is_deleted: boolean;
}

/** Represents the initializer for the table public.NewsFeedItem */
export interface NewsFeedItemInitializer {
  /** Default value: gen_random_uuid() */
  id?: NewsFeedItemId;

  type: NewsFeedItemType;

  platform_identifier: PlatformIdentifier;

  title: string;

  /** Default value: CURRENT_TIMESTAMP */
  creation_date?: Date;

  /** Default value: '{}'::text[] */
  tags?: string[];

  /** Default value: false */
  is_deleted?: boolean;
}

/** Represents the mutator for the table public.NewsFeedItem */
export interface NewsFeedItemMutator {
  id?: NewsFeedItemId;

  type?: NewsFeedItemType;

  platform_identifier?: PlatformIdentifier;

  title?: string;

  creation_date?: Date;

  tags?: string[];

  is_deleted?: boolean;
}
