// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UseCaseId } from './UseCase';

/** Identifier type for public.Object_UseCase */
export type ObjectUseCaseObjectId = string & { __brand: 'public.Object_UseCase' };

/** Represents the table public.Object_UseCase */
export default interface ObjectUseCase {
  object_id: ObjectUseCaseObjectId;

  use_case_id: UseCaseId;
}

/** Represents the initializer for the table public.Object_UseCase */
export interface ObjectUseCaseInitializer {
  object_id: ObjectUseCaseObjectId;

  use_case_id: UseCaseId;
}

/** Represents the mutator for the table public.Object_UseCase */
export interface ObjectUseCaseMutator {
  object_id?: ObjectUseCaseObjectId;

  use_case_id?: UseCaseId;
}
