// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.OneClickDeployment */
export type OneClickDeploymentId = string & { __brand: 'public.OneClickDeployment' };

/** Represents the table public.OneClickDeployment */
export default interface OneClickDeployment {
  id: OneClickDeploymentId;

  resource_id: string;

  platform_id: string;

  tenant_id: string | null;

  user_id: string | null;

  deployed_at: Date;
}

/** Represents the initializer for the table public.OneClickDeployment */
export interface OneClickDeploymentInitializer {
  /** Default value: gen_random_uuid() */
  id?: OneClickDeploymentId;

  resource_id: string;

  platform_id: string;

  tenant_id?: string | null;

  user_id?: string | null;

  deployed_at: Date;
}

/** Represents the mutator for the table public.OneClickDeployment */
export interface OneClickDeploymentMutator {
  id?: OneClickDeploymentId;

  resource_id?: string;

  platform_id?: string;

  tenant_id?: string | null;

  user_id?: string | null;

  deployed_at?: Date;
}
