// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { OrganizationId } from './Organization';
import type { UserId } from './User';

/** Identifier type for public.OneClickDeployment */
export type OneClickDeploymentId = string & { __brand: 'public.OneClickDeployment' };

/** Represents the table public.OneClickDeployment */
export default interface OneClickDeployment {
  id: OneClickDeploymentId;

  source_event_id: string;

  resource_id: string;

  resource_title: string | null;

  platform_id: string;

  platform_version: string | null;

  organization_id: OrganizationId | null;

  user_id: UserId | null;

  target_product: string;

  service: string;

  tenant_id: string | null;

  deployed_at: Date;
}

/** Represents the initializer for the table public.OneClickDeployment */
export interface OneClickDeploymentInitializer {
  /** Default value: gen_random_uuid() */
  id?: OneClickDeploymentId;

  source_event_id: string;

  resource_id: string;

  resource_title?: string | null;

  platform_id: string;

  platform_version?: string | null;

  organization_id?: OrganizationId | null;

  user_id?: UserId | null;

  target_product: string;

  service: string;

  tenant_id?: string | null;

  /** Default value: CURRENT_TIMESTAMP */
  deployed_at?: Date;
}

/** Represents the mutator for the table public.OneClickDeployment */
export interface OneClickDeploymentMutator {
  id?: OneClickDeploymentId;

  source_event_id?: string;

  resource_id?: string;

  resource_title?: string | null;

  platform_id?: string;

  platform_version?: string | null;

  organization_id?: OrganizationId | null;

  user_id?: UserId | null;

  target_product?: string;

  service?: string;

  tenant_id?: string | null;

  deployed_at?: Date;
}
