// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.Organization */
export type OrganizationId = string & { __brand: 'public.Organization' };

/** Represents the table public.Organization */
export default interface Organization {
  id: OrganizationId;

  name: string;

  domains: string[] | null;

  personal_space: boolean;
}

/** Represents the initializer for the table public.Organization */
export interface OrganizationInitializer {
  id: OrganizationId;

  name: string;

  domains?: string[] | null;

  /** Default value: false */
  personal_space?: boolean;
}

/** Represents the mutator for the table public.Organization */
export interface OrganizationMutator {
  id?: OrganizationId;

  name?: string;

  domains?: string[] | null;

  personal_space?: boolean;
}
