// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.PlatformMetadata */
export type PlatformMetadataKey = string & { __brand: 'public.PlatformMetadata' };

/** Represents the table public.PlatformMetadata */
export default interface PlatformMetadata {
  key: PlatformMetadataKey;

  value: string;
}

/** Represents the initializer for the table public.PlatformMetadata */
export interface PlatformMetadataInitializer {
  key: PlatformMetadataKey;

  value: string;
}

/** Represents the mutator for the table public.PlatformMetadata */
export interface PlatformMetadataMutator {
  key?: PlatformMetadataKey;

  value?: string;
}
