// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { PlatformIdentifier } from '../../../__generated__/resolvers-types';

/** Identifier type for public.ProductVersion */
export type ProductVersionId = string & { __brand: 'public.ProductVersion' };

/** Represents the table public.ProductVersion */
export default interface ProductVersion {
  id: ProductVersionId;

  product: PlatformIdentifier;

  version: string;

  version_padded: string;

  created_at: Date;
}

/** Represents the initializer for the table public.ProductVersion */
export interface ProductVersionInitializer {
  /** Default value: gen_random_uuid() */
  id?: ProductVersionId;

  product: PlatformIdentifier;

  version: string;

  version_padded: string;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;
}

/** Represents the mutator for the table public.ProductVersion */
export interface ProductVersionMutator {
  id?: ProductVersionId;

  product?: PlatformIdentifier;

  version?: string;

  version_padded?: string;

  created_at?: Date;
}
