// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ServiceInstanceId } from './ServiceInstance';
import { SeoServiceInstanceLanguage } from '../../../__generated__/resolvers-types';

/** Represents the table public.SEO_ServiceInstance */
export default interface SEOServiceInstance {
  service_instance_id: ServiceInstanceId;

  language: SeoServiceInstanceLanguage;

  meta_title: string;

  meta_description: string;
}

/** Represents the initializer for the table public.SEO_ServiceInstance */
export interface SEOServiceInstanceInitializer {
  service_instance_id: ServiceInstanceId;

  language: SeoServiceInstanceLanguage;

  meta_title: string;

  meta_description: string;
}

/** Represents the mutator for the table public.SEO_ServiceInstance */
export interface SEOServiceInstanceMutator {
  service_instance_id?: ServiceInstanceId;

  language?: SeoServiceInstanceLanguage;

  meta_title?: string;

  meta_description?: string;
}
