// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ServiceInstanceCreationStatus, ServiceInstanceTag } from '../../../__generated__/resolvers-types';
import type { ServiceDefinitionId } from './ServiceDefinition';
import type { DocumentId } from './Document';

/** Identifier type for public.ServiceInstance */
export type ServiceInstanceId = string & { __brand: 'public.ServiceInstance' };

/** Represents the table public.ServiceInstance */
export default interface ServiceInstance {
  id: ServiceInstanceId;

  name: string;

  description: string | null;

  creation_status: ServiceInstanceCreationStatus | null;

  public: boolean | null;

  tags: ServiceInstanceTag[] | null;

  service_definition_id: ServiceDefinitionId | null;

  logo_document_id: DocumentId | null;

  illustration_document_id: DocumentId | null;

  slug: string | null;

  ordering: number | null;
}

/** Represents the initializer for the table public.ServiceInstance */
export interface ServiceInstanceInitializer {
  id: ServiceInstanceId;

  name: string;

  description?: string | null;

  creation_status?: ServiceInstanceCreationStatus | null;

  /** Default value: false */
  public?: boolean | null;

  tags?: ServiceInstanceTag[] | null;

  service_definition_id?: ServiceDefinitionId | null;

  logo_document_id?: DocumentId | null;

  illustration_document_id?: DocumentId | null;

  slug?: string | null;

  /** Default value: 0 */
  ordering?: number | null;
}

/** Represents the mutator for the table public.ServiceInstance */
export interface ServiceInstanceMutator {
  id?: ServiceInstanceId;

  name?: string;

  description?: string | null;

  creation_status?: ServiceInstanceCreationStatus | null;

  public?: boolean | null;

  tags?: ServiceInstanceTag[] | null;

  service_definition_id?: ServiceDefinitionId | null;

  logo_document_id?: DocumentId | null;

  illustration_document_id?: DocumentId | null;

  slug?: string | null;

  ordering?: number | null;
}
