// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ServiceDefinitionId } from './ServiceDefinition';

/** Represents the table public.Service_Contract */
export default interface ServiceContract {
  service_definition_id: ServiceDefinitionId;

  schema: unknown;
}

/** Represents the initializer for the table public.Service_Contract */
export interface ServiceContractInitializer {
  service_definition_id: ServiceDefinitionId;

  schema: unknown;
}

/** Represents the mutator for the table public.Service_Contract */
export interface ServiceContractMutator {
  service_definition_id?: ServiceDefinitionId;

  schema?: unknown;
}
