// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { FiligranProduct } from '../../../__generated__/resolvers-types';

/** Identifier type for public.UseCase */
export type UseCaseId = string & { __brand: 'public.UseCase' };

/** Represents the table public.UseCase */
export default interface UseCase {
  id: UseCaseId;

  name: string;

  color: string;

  product: FiligranProduct[];
}

/** Represents the initializer for the table public.UseCase */
export interface UseCaseInitializer {
  /** Default value: gen_random_uuid() */
  id?: UseCaseId;

  name: string;

  color: string;

  product?: FiligranProduct[];
}

/** Represents the mutator for the table public.UseCase */
export interface UseCaseMutator {
  id?: UseCaseId;

  name?: string;

  color?: string;

  product?: FiligranProduct[];
}
