// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { VotableFeatureId } from './VotableFeature';
import type { UseCaseId } from './UseCase';

/** Represents the table public.VotableFeature_UseCase */
export default interface VotableFeatureUseCase {
  votable_feature_id: VotableFeatureId;

  use_case_id: UseCaseId;
}

/** Represents the initializer for the table public.VotableFeature_UseCase */
export interface VotableFeatureUseCaseInitializer {
  votable_feature_id: VotableFeatureId;

  use_case_id: UseCaseId;
}

/** Represents the mutator for the table public.VotableFeature_UseCase */
export interface VotableFeatureUseCaseMutator {
  votable_feature_id?: VotableFeatureId;

  use_case_id?: UseCaseId;
}
