scalar ServiceGroupId

enum ServiceGroupName {
  Admin
  Analyst
  Reader
  Manager
  Observer
  User
}

type ServiceGroup implements Node {
  id: ID!
  name: ServiceGroupName!
  users: [User!]
}

type UserPlatformGroup {
  platformIdentifier: PlatformIdentifier!
  name: ServiceGroupName!
}

type BundleUserServiceGroup {
  user: User!
  groups: [UserPlatformGroup!]!
}

input UpdateServiceGroupsInputGroup {
  id: ServiceGroupId!
  userIds: [UserId!]!
}

input UpdateServiceGroupsInput {
  groups: [UpdateServiceGroupsInputGroup!]!
}

type Query {
  serviceGroups(serviceInstanceId: ServiceInstanceId!): [ServiceGroup!]!
    @auth(
      portalCapa: [BYPASS]
      orgaCapa: [ADMINISTRATE_ORGANIZATION, MANAGE_PLATFORM_REGISTRATION]
    )
  bundleUserServiceGroups(
    serviceInstanceId: ServiceInstanceId!
  ): [BundleUserServiceGroup!]!
    @auth(
      portalCapa: [BYPASS]
      orgaCapa: [ADMINISTRATE_ORGANIZATION, MANAGE_PLATFORM_REGISTRATION]
    )
}

type Mutation {
  updateServiceGroups(input: UpdateServiceGroupsInput!): [ServiceGroup!]!
    @auth(
      portalCapa: [BYPASS]
      orgaCapa: [ADMINISTRATE_ORGANIZATION, MANAGE_PLATFORM_REGISTRATION]
    )
}
