export enum RESTRICTION {
  CAPABILITY_BYPASS = 'BYPASS',
  CAPABILITY_BCK_MANAGE_SERVICES = 'BCK_MANAGE_SERVICES',
  CAPABILITY_BCK_MANAGE_COMMUNITIES = 'BCK_MANAGE_COMMUNITIES',
  CAPABILITY_FRT_SERVICE_SUBSCRIBER = 'FRT_SERVICE_SUBSCRIBER',
  CAPABILITY_FRT_MANAGE_SETTINGS = 'FRT_MANAGE_SETTINGS',
  CAPABILITY_FRT_ACCESS_BILLING = 'FRT_ACCESS_BILLING',
  CAPABILITY_FRT_MANAGE_USER = 'FRT_MANAGE_USER',
  CAPABILITY_FRT_ACCESS_SERVICES = 'FRT_ACCESS_SERVICES',
}

export const DEBOUNCE_TIME = 300;
