export enum RESTRICTION {
  CAPABILITY_BYPASS = 'BYPASS',
}

export enum ORGANIZATION_CAPACITY {
  MANAGE_ACCESS = 'MANAGE_ACCESS',
  MANAGE_SUBSCRIPTION = 'MANAGE_SUBSCRIPTION',
}

export const DEBOUNCE_TIME = 300;
export const ANIMATION_TIME = 300;
