enum IntegrationFeedType {
  csv_feed
  connector
  rss_feed
  json_feed
  taxii_feed
  opencti_stream_feed
  third_party_integration
}

enum ConnectorType {
  EXTERNAL_IMPORT
  INTERNAL_ENRICHMENT
  INTERNAL_EXPORT_FILE
  INTERNAL_IMPORT_FILE
  STREAM
}

interface IntegrationFeed implements Node & Document {
  # Node
  id: ID!

  # Document
  type: String!
  uploader: User
  uploader_organization: Organization
  name: String!
  short_description: String
  description: String
  file_name: String
  minio_name: String!
  active: Boolean!
  created_at: Date!
  updated_at: Date
  updater_id: String
  download_number: Int
  share_number: Int
  slug: String!
  labels: [Label!]
  service_instance_id: String!
  service_instance: ServiceInstance
  subscription: SubscriptionModel
  children_documents: [ShareableResource!]

  remover_id: ID
  integration_type: IntegrationFeedType!
}

type Connector implements Node & Document & IntegrationFeed {
  # Node
  id: ID!
  # Document
  type: String!
  uploader: User
  uploader_organization: Organization @auth
  name: String!
  short_description: String
  description: String
  file_name: String @auth
  minio_name: String! @auth
  active: Boolean!
  created_at: Date!
  updated_at: Date
  updater_id: String @auth
  download_number: Int
  share_number: Int
  slug: String!
  labels: [Label!]
  service_instance_id: String!
  service_instance: ServiceInstance
  subscription: SubscriptionModel @auth
  children_documents: [ShareableResource!]
  # Integration Feed
  remover_id: ID @auth
  integration_type: IntegrationFeedType!
  product_version: String!
  container_image: String
  verified: Boolean!
  source_code: String
  subscription_link: String
  integration_subtype: ConnectorType!
  manager_supported: Boolean!
  playbook_supported: Boolean!
}

type IntegrationFeedEdge {
  cursor: String!
  node: IntegrationFeed!
}

type IntegrationFeedConnection {
  totalCount: Int!
  edges: [IntegrationFeedEdge!]!
  pageInfo: PageInfo!
}

type Query {
  integrationFeeds(
    first: Int!
    after: ID
    orderBy: DocumentOrdering!
    orderMode: OrderingMode!
    searchTerm: String
    filters: [Filter!]
    serviceInstanceId: String
  ): IntegrationFeedConnection! @auth
  integrationFeed(id: ID, serviceInstanceId: ID): IntegrationFeed @auth
  publicIntegrationFeeds(
    slug: String!
    first: Int!
    after: ID
    orderBy: DocumentOrdering!
    orderMode: OrderingMode!
    searchTerm: String
    filters: [Filter!]
    serviceInstanceId: String
  ): IntegrationFeedConnection!
  publicIntegrationFeedByServiceSlug(serviceSlug: String): [IntegrationFeed]
  publicIntegrationFeedBySlug(slug: String): IntegrationFeed
}
