interface IntegrationFeed implements Node & DocumentBase {
  # Node
  id: ID!

  # DocumentBase
  type: String!
  uploader: User
  uploader_organization: Organization
  name: String!
  short_description: String
  description: String
  file_name: String
  minio_name: String!
  active: Boolean!
  created_at: Date!
  updated_at: Date
  updater_id: String
  download_number: Int
  share_number: Int
  slug: String!
  labels: [Label!]
  service_instance_id: String!
  service_instance: ServiceInstance
  subscription: SubscriptionModel
  children_documents: [ShareableResourceImage!]

  remover_id: ID
  integration_type: String!
}

type Connector implements Node & DocumentBase & IntegrationFeed {
  # Node
  id: ID!
  # DocumentBase
  type: String!
  uploader: User
  uploader_organization: Organization @auth
  name: String!
  short_description: String
  description: String
  file_name: String @auth
  minio_name: String! @auth
  active: Boolean!
  created_at: Date!
  updated_at: Date
  updater_id: String @auth
  download_number: Int
  share_number: Int
  slug: String!
  labels: [Label!]
  service_instance_id: String! @auth
  service_instance: ServiceInstance @auth
  subscription: SubscriptionModel @auth
  children_documents: [ShareableResourceImage!]
  # Integration Feed
  remover_id: ID @auth
  integration_type: String!
  product_version: String!
  container_image: String
  verified: String!
  source_code: String
  subscription_link: String
  integration_subtype: String!
  manager_supported: String!
  playbook_supported: String!
}

type IntegrationFeedEdge {
  cursor: String!
  node: IntegrationFeed!
}

type IntegrationFeedConnection {
  totalCount: Int!
  edges: [IntegrationFeedEdge!]!
  pageInfo: PageInfo!
}

type Query {
  integrationFeeds(
    first: Int!
    after: ID
    orderBy: DocumentOrdering!
    orderMode: OrderingMode!
    searchTerm: String
    filters: [Filter!]
    serviceInstanceId: String
  ): IntegrationFeedConnection! @auth
  integrationFeed(id: ID, serviceInstanceId: ID): IntegrationFeed @auth
  publicIntegrationFeedByServiceSlug(serviceSlug: String): [IntegrationFeed]
  publicIntegrationFeedBySlug(slug: String): IntegrationFeed
}
