enum FiligranProduct {
  OpenCTI
  OpenAEV
  XTMHub
}
enum Timeline {
  Now
  Next
  Under_Consideration
}

enum EpicType {
  OTHER
  INTEGRATION
}

type Epic implements Node {
  id: ID!
  epic: String!
  title: String!
  short_description: String!
  long_description: String!
  is_active: Boolean!
  product: FiligranProduct!
  timeline: Timeline!
  epic_type: EpicType!
  document: Document
  document_id: ID
  uploader_id: String!
  updater_id: String
  created_at: Date!
  updated_at: Date
}

input CreateEpicInput {
  epic: String!
  title: String!
  short_description: String!
  long_description: String!
  is_active: Boolean
  product: FiligranProduct!
  timeline: Timeline!
  is_integration: Boolean
  illustration_document: Upload
}

input UpdateEpicInput {
  epic: String
  title: String
  short_description: String
  long_description: String
  is_active: Boolean
  product: FiligranProduct
  timeline: Timeline
  is_integration: Boolean
  illustration_document: Upload
}

type EpicEdge {
  cursor: String!
  node: Epic!
}
type EpicConnection {
  totalCount: Int!
  edges: [EpicEdge!]!
  pageInfo: PageInfo!
}
enum EpicOrdering {
  epic
}
type Query {
  epics(
    first: Int!
    after: ID
    orderBy: EpicOrdering!
    orderMode: OrderingMode!
  ): EpicConnection
}

type Mutation {
  createEpic(input: CreateEpicInput!, document: [Upload!]): Epic!
    @auth
    @service_capa(requires: [ADD])
  updateEpic(id: ID!, input: UpdateEpicInput!): Epic! @auth
  deleteEpic(id: ID!): Epic! @auth
}
