// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { CompetitorTier } from '../../../__generated__/resolvers-types';

/** Identifier type for public.Competitor */
export type CompetitorId = string & { __brand: 'public.Competitor' };

/** Represents the table public.Competitor */
export default interface Competitor {
  id: CompetitorId;

  name: string | null;

  tier: CompetitorTier | null;

  domain: string | null;
}

/** Represents the initializer for the table public.Competitor */
export interface CompetitorInitializer {
  id: CompetitorId;

  name?: string | null;

  tier?: CompetitorTier | null;

  domain?: string | null;
}

/** Represents the mutator for the table public.Competitor */
export interface CompetitorMutator {
  id?: CompetitorId;

  name?: string | null;

  tier?: CompetitorTier | null;

  domain?: string | null;
}
