// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { OrganizationId } from './Organization';
import type { ServiceInstanceId } from './ServiceInstance';
import type { UserId } from './User';

/** Identifier type for public.DeploymentRequest */
export type DeploymentRequestId = string & {
  __brand: 'public.DeploymentRequest';
};

/** Represents the table public.DeploymentRequest */
export default interface DeploymentRequest {
  id: DeploymentRequestId;

  user_requester_id: UserId;

  organization_requester_id: OrganizationId;

  service_instance_id: ServiceInstanceId;

  status: string;

  type: string;

  request_date: Date;

  start_date: Date | null;

  end_date: Date | null;

  platform_identifier: string;

  intention: string | null;

  region: string;

  activity_sector: string | null;

  platform_token: string | null;

  product_service_instance_id: string | null;

  failure_reason: string | null;
}

/** Represents the initializer for the table public.DeploymentRequest */
export interface DeploymentRequestInitializer {
  id: DeploymentRequestId;

  user_requester_id: UserId;

  organization_requester_id: OrganizationId;

  service_instance_id: ServiceInstanceId;

  status: string;

  type: string;

  /** Default value: CURRENT_TIMESTAMP */
  request_date?: Date;

  start_date?: Date | null;

  end_date?: Date | null;

  platform_identifier: string;

  intention?: string | null;

  region: string;

  activity_sector?: string | null;

  platform_token?: string | null;

  product_service_instance_id?: string | null;

  failure_reason?: string | null;
}

/** Represents the mutator for the table public.DeploymentRequest */
export interface DeploymentRequestMutator {
  id?: DeploymentRequestId;

  user_requester_id?: UserId;

  organization_requester_id?: OrganizationId;

  service_instance_id?: ServiceInstanceId;

  status?: string;

  type?: string;

  request_date?: Date;

  start_date?: Date | null;

  end_date?: Date | null;

  platform_identifier?: string;

  intention?: string | null;

  region?: string;

  activity_sector?: string | null;

  platform_token?: string | null;

  product_service_instance_id?: string | null;

  failure_reason?: string | null;
}
