// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { OrganizationId } from './Organization';
import type { ServiceInstanceId } from './ServiceInstance';
import type { UserId } from './User';

/** Identifier type for public.DeploymentRequest */
export type DeploymentRequestId = string & {
  __brand: 'public.DeploymentRequest';
};

/** Represents the table public.DeploymentRequest */
export default interface DeploymentRequest {
  id: DeploymentRequestId;

  user_requester_id: UserId;

  organization_requester_id: OrganizationId;

  service_instance_id: ServiceInstanceId;

  type: string;

  request_date: Date;

  start_date: Date | null;

  end_date: Date | null;

  platform_identifier: string;

  region: string;

  activity_sector: string | null;

  platform_token: string | null;

  platform_id: string | null;

  failure_reason: string | null;

  job_title: string | null;

  use_case: string | null;

  hub_status: string;

  target_state: string;

  actual_state: string;

  ordering: number;
}

/** Represents the initializer for the table public.DeploymentRequest */
export interface DeploymentRequestInitializer {
  id: DeploymentRequestId;

  user_requester_id: UserId;

  organization_requester_id: OrganizationId;

  service_instance_id: ServiceInstanceId;

  type: string;

  /** Default value: CURRENT_TIMESTAMP */
  request_date?: Date;

  start_date?: Date | null;

  end_date?: Date | null;

  platform_identifier: string;

  region: string;

  activity_sector?: string | null;

  platform_token?: string | null;

  platform_id?: string | null;

  failure_reason?: string | null;

  job_title?: string | null;

  use_case?: string | null;

  /** Default value: 'pending'::character varying */
  hub_status?: string;

  /** Default value: 'pending'::character varying */
  target_state?: string;

  /** Default value: 'pending'::character varying */
  actual_state?: string;

  /** Default value: 0 */
  ordering?: number;
}

/** Represents the mutator for the table public.DeploymentRequest */
export interface DeploymentRequestMutator {
  id?: DeploymentRequestId;

  user_requester_id?: UserId;

  organization_requester_id?: OrganizationId;

  service_instance_id?: ServiceInstanceId;

  type?: string;

  request_date?: Date;

  start_date?: Date | null;

  end_date?: Date | null;

  platform_identifier?: string;

  region?: string;

  activity_sector?: string | null;

  platform_token?: string | null;

  platform_id?: string | null;

  failure_reason?: string | null;

  job_title?: string | null;

  use_case?: string | null;

  hub_status?: string;

  target_state?: string;

  actual_state?: string;

  ordering?: number;
}
