// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { DocumentId } from './Document';

/** Identifier type for public.Document_Metadata */
export type DocumentMetadataKey = string & {
  __brand: 'public.Document_Metadata';
};

/** Represents the table public.Document_Metadata */
export default interface DocumentMetadata {
  document_id: DocumentId;

  key: DocumentMetadataKey;

  value: string | null;
}

/** Represents the initializer for the table public.Document_Metadata */
export interface DocumentMetadataInitializer {
  document_id: DocumentId;

  key: DocumentMetadataKey;

  value?: string | null;
}

/** Represents the mutator for the table public.Document_Metadata */
export interface DocumentMetadataMutator {
  document_id?: DocumentId;

  key?: DocumentMetadataKey;

  value?: string | null;
}
