// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { DocumentId } from './Document';

/** Identifier type for public.Epic */
export type EpicId = string & { __brand: 'public.Epic' };

/** Represents the table public.Epic */
export default interface Epic {
  id: EpicId;

  epic: string;

  title: string;

  is_active: boolean | null;

  short_description: string;

  long_description: string;

  product: string;

  timeline: string | null;

  epic_type: string | null;

  document_id: DocumentId | null;

  created_at: Date;

  updated_at: Date | null;

  updater_id: string | null;
}

/** Represents the initializer for the table public.Epic */
export interface EpicInitializer {
  /** Default value: gen_random_uuid() */
  id?: EpicId;

  epic: string;

  title: string;

  /** Default value: false */
  is_active?: boolean | null;

  short_description: string;

  long_description: string;

  product: string;

  /** Default value: 'OTHER'::text */
  timeline?: string | null;

  /** Default value: 'OTHER'::text */
  epic_type?: string | null;

  document_id?: DocumentId | null;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;

  updated_at?: Date | null;

  updater_id?: string | null;
}

/** Represents the mutator for the table public.Epic */
export interface EpicMutator {
  id?: EpicId;

  epic?: string;

  title?: string;

  is_active?: boolean | null;

  short_description?: string;

  long_description?: string;

  product?: string;

  timeline?: string | null;

  epic_type?: string | null;

  document_id?: DocumentId | null;

  created_at?: Date;

  updated_at?: Date | null;

  updater_id?: string | null;
}
