// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { FiligranProduct, Timeline, EpicType } from '../../../__generated__/resolvers-types';
import type { DocumentId } from './Document';

/** Identifier type for public.Epic */
export type EpicId = string & { __brand: 'public.Epic' };

/** Represents the table public.Epic */
export default interface Epic {
  id: EpicId;

  epic: string;

  title: string;

  active: boolean | null;

  uploader_id: string | null;

  short_description: string;

  description: string | null;

  product: FiligranProduct;

  timeline: Timeline | null;

  epic_type: EpicType | null;

  document_id: DocumentId | null;

  created_at: Date;

  updated_at: Date | null;

  updater_id: string | null;
}

/** Represents the initializer for the table public.Epic */
export interface EpicInitializer {
  /** Default value: gen_random_uuid() */
  id?: EpicId;

  epic: string;

  title: string;

  /** Default value: false */
  active?: boolean | null;

  uploader_id?: string | null;

  short_description: string;

  description?: string | null;

  product: FiligranProduct;

  timeline?: Timeline | null;

  epic_type?: EpicType | null;

  document_id?: DocumentId | null;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;

  updated_at?: Date | null;

  updater_id?: string | null;
}

/** Represents the mutator for the table public.Epic */
export interface EpicMutator {
  id?: EpicId;

  epic?: string;

  title?: string;

  active?: boolean | null;

  uploader_id?: string | null;

  short_description?: string;

  description?: string | null;

  product?: FiligranProduct;

  timeline?: Timeline | null;

  epic_type?: EpicType | null;

  document_id?: DocumentId | null;

  created_at?: Date;

  updated_at?: Date | null;

  updater_id?: string | null;
}
