// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.Generic_Service_Capability */
export type GenericServiceCapabilityId = string & {
  __brand: 'public.Generic_Service_Capability';
};

/** Represents the table public.Generic_Service_Capability */
export default interface GenericServiceCapability {
  id: GenericServiceCapabilityId;

  name: string | null;
}

/** Represents the initializer for the table public.Generic_Service_Capability */
export interface GenericServiceCapabilityInitializer {
  id: GenericServiceCapabilityId;

  name?: string | null;
}

/** Represents the mutator for the table public.Generic_Service_Capability */
export interface GenericServiceCapabilityMutator {
  id?: GenericServiceCapabilityId;

  name?: string | null;
}
