// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.Label */
export type LabelId = string & { __brand: 'public.Label' };

/** Represents the table public.Label */
export default interface Label {
  id: LabelId;

  name: string | null;

  color: string | null;
}

/** Represents the initializer for the table public.Label */
export interface LabelInitializer {
  /** Default value: gen_random_uuid() */
  id?: LabelId;

  name?: string | null;

  color?: string | null;
}

/** Represents the mutator for the table public.Label */
export interface LabelMutator {
  id?: LabelId;

  name?: string | null;

  color?: string | null;
}
