// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ActionTrackingId } from './ActionTracking';

/** Identifier type for public.MessageTracking */
export type MessageTrackingId = string & { __brand: 'public.MessageTracking' };

/** Represents the table public.MessageTracking */
export default interface MessageTracking {
  id: MessageTrackingId;

  tracking_id: ActionTrackingId | null;

  created_at: Date;

  technical: boolean | null;

  type: string;

  tracking_info: unknown | null;
}

/** Represents the initializer for the table public.MessageTracking */
export interface MessageTrackingInitializer {
  /** Default value: gen_random_uuid() */
  id?: MessageTrackingId;

  tracking_id?: ActionTrackingId | null;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;

  /** Default value: false */
  technical?: boolean | null;

  type: string;

  tracking_info?: unknown | null;
}

/** Represents the mutator for the table public.MessageTracking */
export interface MessageTrackingMutator {
  id?: MessageTrackingId;

  tracking_id?: ActionTrackingId | null;

  created_at?: Date;

  technical?: boolean | null;

  type?: string;

  tracking_info?: unknown | null;
}
