// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.migrations_lock */
export type MigrationsLockIndex = number & { __brand: 'MigrationsLockIndex' };

/** Represents the table public.migrations_lock */
export default interface MigrationsLock {
  index: MigrationsLockIndex;

  is_locked: number | null;
}

/** Represents the initializer for the table public.migrations_lock */
export interface MigrationsLockInitializer {
  /** Default value: nextval('migrations_lock_index_seq'::regclass) */
  index?: MigrationsLockIndex;

  is_locked?: number | null;
}

/** Represents the mutator for the table public.migrations_lock */
export interface MigrationsLockMutator {
  index?: MigrationsLockIndex;

  is_locked?: number | null;
}
