// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { NewsFeedItemId } from './NewsFeedItem';

/** Identifier type for public.NewsFeedItemMetadata */
export type NewsFeedItemMetadataKey = string & { __brand: 'public.NewsFeedItemMetadata' };

/** Represents the table public.NewsFeedItemMetadata */
export default interface NewsFeedItemMetadata {
  news_feed_item_id: NewsFeedItemId;

  key: NewsFeedItemMetadataKey;

  value: string | null;
}

/** Represents the initializer for the table public.NewsFeedItemMetadata */
export interface NewsFeedItemMetadataInitializer {
  news_feed_item_id: NewsFeedItemId;

  key: NewsFeedItemMetadataKey;

  value?: string | null;
}

/** Represents the mutator for the table public.NewsFeedItemMetadata */
export interface NewsFeedItemMetadataMutator {
  news_feed_item_id?: NewsFeedItemId;

  key?: NewsFeedItemMetadataKey;

  value?: string | null;
}
