// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { LabelId } from './Label';

/** Identifier type for public.Object_Label */
export type ObjectLabelObjectId = string & { __brand: 'public.Object_Label' };

/** Represents the table public.Object_Label */
export default interface ObjectLabel {
  object_id: ObjectLabelObjectId;

  label_id: LabelId;
}

/** Represents the initializer for the table public.Object_Label */
export interface ObjectLabelInitializer {
  object_id: ObjectLabelObjectId;

  label_id: LabelId;
}

/** Represents the mutator for the table public.Object_Label */
export interface ObjectLabelMutator {
  object_id?: ObjectLabelObjectId;

  label_id?: LabelId;
}
