// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { CapabilityPortalId } from './CapabilityPortal';
import type { RolePortalId } from './RolePortal';

/** Identifier type for public.RolePortal_CapabilityPortal */
export type RolePortalCapabilityPortalId = number & {
  __brand: 'public.RolePortal_CapabilityPortal';
};

/** Represents the table public.RolePortal_CapabilityPortal */
export default interface RolePortalCapabilityPortal {
  id: RolePortalCapabilityPortalId;

  capability_portal_id: CapabilityPortalId | null;

  role_portal_id: RolePortalId | null;
}

/** Represents the initializer for the table public.RolePortal_CapabilityPortal */
export interface RolePortalCapabilityPortalInitializer {
  /** Default value: nextval('"RolePortal_CapabilityPortal_id_seq"'::regclass) */
  id?: RolePortalCapabilityPortalId;

  capability_portal_id?: CapabilityPortalId | null;

  role_portal_id?: RolePortalId | null;
}

/** Represents the mutator for the table public.RolePortal_CapabilityPortal */
export interface RolePortalCapabilityPortalMutator {
  id?: RolePortalCapabilityPortalId;

  capability_portal_id?: CapabilityPortalId | null;

  role_portal_id?: RolePortalId | null;
}
