// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ServiceDefinitionId } from './ServiceDefinition';

/** Identifier type for public.Service_Capability */
export type ServiceCapabilityId = string & {
  __brand: 'public.Service_Capability';
};

/** Represents the table public.Service_Capability */
export default interface ServiceCapability {
  id: ServiceCapabilityId;

  name: string | null;

  description: string | null;

  service_definition_id: ServiceDefinitionId | null;
}

/** Represents the initializer for the table public.Service_Capability */
export interface ServiceCapabilityInitializer {
  /** Default value: gen_random_uuid() */
  id?: ServiceCapabilityId;

  name?: string | null;

  description?: string | null;

  service_definition_id?: ServiceDefinitionId | null;
}

/** Represents the mutator for the table public.Service_Capability */
export interface ServiceCapabilityMutator {
  id?: ServiceCapabilityId;

  name?: string | null;

  description?: string | null;

  service_definition_id?: ServiceDefinitionId | null;
}
