// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { DocumentId } from './Document';
import type { ServiceDefinitionId } from './ServiceDefinition';

/** Identifier type for public.ServiceInstance */
export type ServiceInstanceId = string & { __brand: 'public.ServiceInstance' };

/** Represents the table public.ServiceInstance */
export default interface ServiceInstance {
  id: ServiceInstanceId;

  name: string;

  description: string | null;

  creation_status: string | null;

  public: boolean | null;

  join_type: string | null;

  tags: string[] | null;

  service_definition_id: ServiceDefinitionId | null;

  logo_document_id: DocumentId | null;

  illustration_document_id: string | null;

  slug: string | null;

  ordering: number | null;
}

/** Represents the initializer for the table public.ServiceInstance */
export interface ServiceInstanceInitializer {
  id: ServiceInstanceId;

  name: string;

  description?: string | null;

  /** Default value: 'READY'::text */
  creation_status?: string | null;

  /** Default value: false */
  public?: boolean | null;

  /** Default value: 'JOIN_INVITE'::text */
  join_type?: string | null;

  tags?: string[] | null;

  service_definition_id?: ServiceDefinitionId | null;

  logo_document_id?: DocumentId | null;

  illustration_document_id?: string | null;

  slug?: string | null;

  /** Default value: 0 */
  ordering?: number | null;
}

/** Represents the mutator for the table public.ServiceInstance */
export interface ServiceInstanceMutator {
  id?: ServiceInstanceId;

  name?: string;

  description?: string | null;

  creation_status?: string | null;

  public?: boolean | null;

  join_type?: string | null;

  tags?: string[] | null;

  service_definition_id?: ServiceDefinitionId | null;

  logo_document_id?: DocumentId | null;

  illustration_document_id?: string | null;

  slug?: string | null;

  ordering?: number | null;
}
