// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.sessions */
export type SessionsSid = string & { __brand: 'public.sessions' };

/** Represents the table public.sessions */
export default interface Sessions {
  sid: SessionsSid;

  sess: unknown;

  expire: Date;

  created_at: Date | null;

  updated_at: Date | null;
}

/** Represents the initializer for the table public.sessions */
export interface SessionsInitializer {
  sid: SessionsSid;

  sess: unknown;

  expire: Date;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date | null;

  /** Default value: CURRENT_TIMESTAMP */
  updated_at?: Date | null;
}

/** Represents the mutator for the table public.sessions */
export interface SessionsMutator {
  sid?: SessionsSid;

  sess?: unknown;

  expire?: Date;

  created_at?: Date | null;

  updated_at?: Date | null;
}
