// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.SSOGroup_RolePortal */
export type SSOGroupRolePortalSSOGroup = string & {
  __brand: 'public.SSOGroup_RolePortal';
};

/** Identifier type for public.SSOGroup_RolePortal */
export type SSOGroupRolePortalRolePortal = string & {
  __brand: 'public.SSOGroup_RolePortal';
};

/** Represents the table public.SSOGroup_RolePortal */
export default interface SSOGroupRolePortal {
  SSOGroup: SSOGroupRolePortalSSOGroup;

  RolePortal: SSOGroupRolePortalRolePortal;
}

/** Represents the initializer for the table public.SSOGroup_RolePortal */
export interface SSOGroupRolePortalInitializer {
  SSOGroup: SSOGroupRolePortalSSOGroup;

  RolePortal: SSOGroupRolePortalRolePortal;
}

/** Represents the mutator for the table public.SSOGroup_RolePortal */
export interface SSOGroupRolePortalMutator {
  SSOGroup?: SSOGroupRolePortalSSOGroup;

  RolePortal?: SSOGroupRolePortalRolePortal;
}
