// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { OrganizationId } from './Organization';
import type { ServiceInstanceId } from './ServiceInstance';

/** Identifier type for public.Subscription */
export type SubscriptionId = string & { __brand: 'public.Subscription' };

/** Represents the table public.Subscription */
export default interface Subscription {
  id: SubscriptionId;

  organization_id: OrganizationId | null;

  service_instance_id: ServiceInstanceId | null;

  status: string | null;

  joining: string | null;

  billing: number | null;

  justification: string | null;

  start_date: Date | null;

  end_date: Date | null;
}

/** Represents the initializer for the table public.Subscription */
export interface SubscriptionInitializer {
  id: SubscriptionId;

  organization_id?: OrganizationId | null;

  service_instance_id?: ServiceInstanceId | null;

  /** Default value: 'ACCEPTED'::text */
  status?: string | null;

  /** Default value: 'AUTO_JOIN'::text */
  joining?: string | null;

  /** Default value: 100 */
  billing?: number | null;

  justification?: string | null;

  start_date?: Date | null;

  end_date?: Date | null;
}

/** Represents the mutator for the table public.Subscription */
export interface SubscriptionMutator {
  id?: SubscriptionId;

  organization_id?: OrganizationId | null;

  service_instance_id?: ServiceInstanceId | null;

  status?: string | null;

  joining?: string | null;

  billing?: number | null;

  justification?: string | null;

  start_date?: Date | null;

  end_date?: Date | null;
}
