// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ServiceCapabilityId } from './ServiceCapability';
import type { SubscriptionId } from './Subscription';

/** Identifier type for public.Subscription_Capability */
export type SubscriptionCapabilityId = string & {
  __brand: 'public.Subscription_Capability';
};

/** Represents the table public.Subscription_Capability */
export default interface SubscriptionCapability {
  id: SubscriptionCapabilityId;

  service_capability_id: ServiceCapabilityId | null;

  subscription_id: SubscriptionId | null;
}

/** Represents the initializer for the table public.Subscription_Capability */
export interface SubscriptionCapabilityInitializer {
  /** Default value: gen_random_uuid() */
  id?: SubscriptionCapabilityId;

  service_capability_id?: ServiceCapabilityId | null;

  subscription_id?: SubscriptionId | null;
}

/** Represents the mutator for the table public.Subscription_Capability */
export interface SubscriptionCapabilityMutator {
  id?: SubscriptionCapabilityId;

  service_capability_id?: ServiceCapabilityId | null;

  subscription_id?: SubscriptionId | null;
}
