// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.UseCase */
export type UseCaseId = string & { __brand: 'public.UseCase' };

/** Represents the table public.UseCase */
export default interface UseCase {
  id: UseCaseId;

  name: string | null;

  color: string | null;
}

/** Represents the initializer for the table public.UseCase */
export interface UseCaseInitializer {
  /** Default value: gen_random_uuid() */
  id?: UseCaseId;

  name?: string | null;

  color?: string | null;
}

/** Represents the mutator for the table public.UseCase */
export interface UseCaseMutator {
  id?: UseCaseId;

  name?: string | null;

  color?: string | null;
}
