// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UserId } from './User';

/** Identifier type for public.User_TransferRequest */
export type UserTransferRequestId = string & {
  __brand: 'public.User_TransferRequest';
};

/** Represents the table public.User_TransferRequest */
export default interface UserTransferRequest {
  id: UserTransferRequestId;

  from_user_id: UserId | null;

  to_user_id: UserId | null;
}

/** Represents the initializer for the table public.User_TransferRequest */
export interface UserTransferRequestInitializer {
  /** Default value: gen_random_uuid() */
  id?: UserTransferRequestId;

  from_user_id?: UserId | null;

  to_user_id?: UserId | null;
}

/** Represents the mutator for the table public.User_TransferRequest */
export interface UserTransferRequestMutator {
  id?: UserTransferRequestId;

  from_user_id?: UserId | null;

  to_user_id?: UserId | null;
}
