// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UserOrganizationId } from './UserOrganization';

/** Identifier type for public.UserOrganization_Capability */
export type UserOrganizationCapabilityId = number & {
  __brand: 'public.UserOrganization_Capability';
};

/** Represents the table public.UserOrganization_Capability */
export default interface UserOrganizationCapability {
  id: UserOrganizationCapabilityId;

  user_organization_id: UserOrganizationId | null;

  name: string;
}

/** Represents the initializer for the table public.UserOrganization_Capability */
export interface UserOrganizationCapabilityInitializer {
  /** Default value: nextval('"UserOrganization_Capability_id_seq"'::regclass) */
  id?: UserOrganizationCapabilityId;

  user_organization_id?: UserOrganizationId | null;

  name: string;
}

/** Represents the mutator for the table public.UserOrganization_Capability */
export interface UserOrganizationCapabilityMutator {
  id?: UserOrganizationCapabilityId;

  user_organization_id?: UserOrganizationId | null;

  name?: string;
}
