// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { OrganizationId } from './Organization';
import type { UserId } from './User';

/** Identifier type for public.User_Organization_Pending */
export type UserOrganizationPendingId = number & {
  __brand: 'public.User_Organization_Pending';
};

/** Represents the table public.User_Organization_Pending */
export default interface UserOrganizationPending {
  id: UserOrganizationPendingId;

  user_id: UserId | null;

  organization_id: OrganizationId | null;
}

/** Represents the initializer for the table public.User_Organization_Pending */
export interface UserOrganizationPendingInitializer {
  /** Default value: nextval('"User_Organization_Pending_id_seq"'::regclass) */
  id?: UserOrganizationPendingId;

  user_id?: UserId | null;

  organization_id?: OrganizationId | null;
}

/** Represents the mutator for the table public.User_Organization_Pending */
export interface UserOrganizationPendingMutator {
  id?: UserOrganizationPendingId;

  user_id?: UserId | null;

  organization_id?: OrganizationId | null;
}
