scalar UseCaseId

type UseCase implements Node {
  id: ID!
  name: String!
  color: String!
}

enum UseCaseOrdering {
  name
  color
}

type UseCaseEdge {
  cursor: String!
  node: UseCase!
}

type UseCaseConnection {
  totalCount: Int!
  edges: [UseCaseEdge!]!
  pageInfo: PageInfo!
}

input AddUseCaseInput {
  name: String!
  color: String!
}

input EditUseCaseInput {
  name: String
  color: String
}

type Query {
  useCases(
    first: Int!
    after: ID
    orderBy: UseCaseOrdering!
    orderMode: OrderingMode!
    searchTerm: String
    documentType: String
  ): UseCaseConnection
}

type Mutation {
  addUseCase(input: AddUseCaseInput!): UseCase! @auth(portalCapa: [BYPASS])
  editUseCase(id: ID!, input: EditUseCaseInput!): UseCase!
    @auth(portalCapa: [BYPASS])
  deleteUseCase(id: ID!): UseCase! @auth(portalCapa: [BYPASS])
}
