query PrivateNavigationServiceInstances(
  $count: Int!
  $orderBy: ServiceInstanceOrdering!
  $orderMode: OrderingMode!
) {
  serviceInstances(first: $count, orderBy: $orderBy, orderMode: $orderMode) {
    edges {
      node {
        id
        name
        service_definition {
          identifier
        }
        links {
          url
        }
      }
    }
  }
  registeredPlatforms(input: {}) {
    title
    url
    identifier
    subscription {
      service_instance {
        id
      }
    }
  }
}
