import { afterEach, describe, expect, it } from 'vitest';
import { PlatformIdentifier } from '../__generated__/resolvers-types';
import { clearTemplateCache, renderEmail } from './mail-service';

describe('renderEmail', () => {
  afterEach(() => {
    clearTemplateCache();
  });

  describe('template loading', () => {
    it('should render a template file and return html', async () => {
      const html = await renderEmail('welcome', {});
      expect(html).toBeTruthy();
      expect(html).toContain('Welcome to XTM Hub');
    });

    it('should cache templates on subsequent calls', async () => {
      const html1 = await renderEmail('welcome', {});
      const html2 = await renderEmail('welcome', {});
      expect(html1).toBe(html2);
    });
  });

  describe('variable substitution', () => {
    it('should replace simple variables', async () => {
      const html = await renderEmail('new_user_organization', {
        organizationName: 'Filigran',
        userName: 'Alice',
        invitedName: 'Bob',
      });
      expect(html).toContain('Filigran');
      expect(html).toContain('Bob');
    });

    it('should inject base_url_front and contactEmail automatically', async () => {
      const html = await renderEmail('welcome', {});
      expect(html).not.toContain('{{ base_url_front }}');
      expect(html).not.toContain('{{ contactEmail }}');
      expect(html).toContain('xtm-hub-support@filigran.io');
    });
  });

  describe('HTML escaping', () => {
    it('should escape HTML in double-brace variables by default', async () => {
      const html = await renderEmail('new_user_organization', {
        organizationName: '<script>alert("xss")</script>',
        userName: 'Alice',
        invitedName: 'Bob',
      });
      expect(html).not.toContain('<script>alert("xss")</script>');
      expect(html).toContain('&lt;script&gt;');
    });
  });

  describe('{{#each}} loops', () => {
    it('should render a list of users in organization_pending_user_digest', async () => {
      const html = await renderEmail('organization_pending_user_digest', {
        adminName: 'Admin',
        organizationName: 'Filigran',
        users: [
          { firstName: 'John', lastName: 'Doe', email: 'john@test.com' },
          { firstName: 'Jane', lastName: 'Smith', email: 'jane@test.com' },
        ],
        userCount: 2,
        requestLabel: 'requests',
      });
      expect(html).toContain('John');
      expect(html).toContain('Doe');
      expect(html).toContain('john@test.com');
      expect(html).toContain('Jane');
      expect(html).toContain('Smith');
      expect(html).toContain('jane@test.com');
      // Should have <li> elements generated by the {{#each}} loop
      expect(html).toContain('<li>');
    });

    it('should render an empty list when users array is empty', async () => {
      const html = await renderEmail('organization_pending_user_digest', {
        adminName: 'Admin',
        organizationName: 'Filigran',
        users: [],
        userCount: 0,
        requestLabel: 'requests',
      });
      expect(html).toContain('Admin');
      expect(html).not.toContain('<li>');
    });

    it('should render a single user correctly', async () => {
      const html = await renderEmail('organization_pending_user_digest', {
        adminName: 'Admin',
        organizationName: 'Filigran',
        users: [
          { firstName: 'Solo', lastName: 'User', email: 'solo@test.com' },
        ],
        userCount: 1,
        requestLabel: 'request',
      });
      const liCount = (html.match(/<li>/g) || []).length;
      expect(liCount).toBe(1);
      expect(html).toContain('Solo');
      expect(html).toContain('solo@test.com');
    });
  });

  describe('{{#if}} tests', () => {
    it('should render text conditionally', async () => {
      const html = await renderEmail('free_trial_registered', {
        firstName: 'User',
        platformUrl: 'http://myTestPlatform',
        platformIdentifier: PlatformIdentifier.Openaev,
      });

      expect(html).not.toContain('OpenCTI');
    });
  });
  describe('edge cases', () => {
    it('should handle empty string values gracefully', async () => {
      const html = await renderEmail('organization_pending_user_digest', {
        adminName: 'Admin',
        organizationName: 'Filigran',
        users: [{ firstName: '', lastName: 'Smith', email: 'user@test.com' }],
        userCount: 1,
        requestLabel: 'request',
      });
      expect(html).toContain('Smith');
      expect(html).toContain('user@test.com');
    });

    it('should escape special characters in user data within {{#each}}', async () => {
      const html = await renderEmail('organization_pending_user_digest', {
        adminName: 'Admin',
        organizationName: 'Filigran',
        users: [
          {
            firstName: '<b>Bold</b>',
            lastName: 'User',
            email: 'bold@test.com',
          },
        ],
        userCount: 1,
        requestLabel: 'request',
      });
      expect(html).not.toContain('<b>Bold</b>');
      expect(html).toContain('&lt;b&gt;Bold&lt;/b&gt;');
    });

    it('should handle many users in the list', async () => {
      const users = Array.from({ length: 50 }, (_, i) => ({
        firstName: `First${i}`,
        lastName: `Last${i}`,
        email: `user${i}@test.com`,
      }));
      const html = await renderEmail('organization_pending_user_digest', {
        adminName: 'Admin',
        organizationName: 'Filigran',
        users,
        userCount: 50,
        requestLabel: 'requests',
      });
      const liCount = (html.match(/<li>/g) || []).length;
      expect(liCount).toBe(50);
      expect(html).toContain('First0');
      expect(html).toContain('First49');
    });
  });
});
