import config from 'config';
import { toGlobalId } from 'graphql-relay/node/node.js';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { PlatformIdentifier } from '../__generated__/resolvers-types';
import * as producer from '../thirdparty/pgboss/producer';
import {
  buildPendingUserActionLink,
  clearTemplateCache,
  renderEmail,
  sendMail,
} from './mail-service';
import { templateSubjects } from './mail-template/mail';

vi.mock('config', async (importOriginal) => {
  const mod = await importOriginal<{ default: typeof config }>();
  return {
    default: {
      get: vi.fn(mod.default.get.bind(mod.default)),
      has: mod.default.has.bind(mod.default),
    },
  };
});

const buildDigestUser = ({
  firstName,
  lastName,
  email,
}: {
  firstName: string;
  lastName: string;
  email: string;
}) => ({
  firstName,
  lastName,
  email,
  approveLink: `https://hub.test/redirect/handle-pending-user?action=approve&organization_id=orga-global-id&user_id=${email}-global-id`,
  denyLink: `https://hub.test/redirect/handle-pending-user?action=deny&organization_id=orga-global-id&user_id=${email}-global-id`,
});

describe('renderEmail', () => {
  afterEach(() => {
    clearTemplateCache();
  });

  describe('template loading', () => {
    it('should render a template file and return html', async () => {
      const html = await renderEmail('welcome', {});
      expect(html).toBeTruthy();
      expect(html).toContain('Welcome to XTM Hub');
    });

    it('should cache templates on subsequent calls', async () => {
      const html1 = await renderEmail('welcome', {});
      const html2 = await renderEmail('welcome', {});
      expect(html1).toBe(html2);
    });
  });

  describe('variable substitution', () => {
    it('should replace simple variables', async () => {
      const html = await renderEmail('new_user_organization', {
        organizationName: 'Filigran',
        userName: 'Alice',
        invitedName: 'Bob',
      });
      expect(html).toContain('Filigran');
      expect(html).toContain('Bob');
    });

    it('should inject base_url_front and contactEmail automatically', async () => {
      const html = await renderEmail('welcome', {});
      expect(html).not.toContain('{{ base_url_front }}');
      expect(html).not.toContain('{{ contactEmail }}');
      expect(html).toContain('xtm-hub-support@filigran.io');
    });

    it('should use template subject for title and aria-label', async () => {
      const params = {
        organizationName: 'Filigran',
        userName: 'Alice',
        invitedName: 'Bob',
      };
      const expectedTitle = templateSubjects.new_user_organization(params);
      const escapedExpectedTitle = expectedTitle.replaceAll("'", '&#x27;');

      const html = await renderEmail('new_user_organization', params);

      expect(html).toContain(`<title>${escapedExpectedTitle}</title>`);
      expect(html).toContain(`aria-label="${escapedExpectedTitle}"`);
    });
  });

  describe('hTML escaping', () => {
    it('should escape HTML in double-brace variables by default', async () => {
      const html = await renderEmail('new_user_organization', {
        organizationName: '<script>alert("xss")</script>',
        userName: 'Alice',
        invitedName: 'Bob',
      });
      expect(html).not.toContain('<script>alert("xss")</script>');
      expect(html).toContain('&lt;script&gt;');
    });
  });

  describe('{{#each}} loops', () => {
    it('should render a list of users in organization_pending_user_digest', async () => {
      const html = await renderEmail('organization_pending_user_digest', {
        adminName: 'Admin',
        adminEmail: 'admin@test.com',
        organizationName: 'Filigran',
        users: [
          buildDigestUser({
            firstName: 'John',
            lastName: 'Doe',
            email: 'john@test.com',
          }),
          buildDigestUser({
            firstName: 'Jane',
            lastName: 'Smith',
            email: 'jane@test.com',
          }),
        ],
        userCount: 2,
        requestLabel: 'requests',
      });
      expect(html).toContain('John');
      expect(html).toContain('Doe');
      expect(html).toContain('john@test.com');
      expect(html).toContain('Jane');
      expect(html).toContain('Smith');
      expect(html).toContain('jane@test.com');
      // Should have one action row per user generated by the {{#each}} loop
      expect(html.match(/>\s*Approve\s*</g)).toHaveLength(2);
    });

    it('should render an empty list when users array is empty', async () => {
      const html = await renderEmail('organization_pending_user_digest', {
        adminName: 'Admin',
        adminEmail: 'admin@test.com',
        organizationName: 'Filigran',
        users: [],
        userCount: 0,
        requestLabel: 'requests',
      });
      expect(html).toContain('Admin');
      expect(html).not.toContain('Approve');
    });

    it('should render a single user correctly', async () => {
      const html = await renderEmail('organization_pending_user_digest', {
        adminName: 'Admin',
        adminEmail: 'admin@test.com',
        organizationName: 'Filigran',
        users: [
          buildDigestUser({
            firstName: 'Solo',
            lastName: 'User',
            email: 'solo@test.com',
          }),
        ],
        userCount: 1,
        requestLabel: 'request',
      });
      const actionRowCount = (html.match(/>\s*Approve\s*</g) || []).length;
      expect(actionRowCount).toBe(1);
      expect(html).toContain('Solo');
      expect(html).toContain('solo@test.com');
    });
  });

  describe('{{#if}} tests', () => {
    it('should render text conditionally for free trials', async () => {
      const html = await renderEmail('free_trial_registered', {
        firstName: 'User',
        platformUrl: 'http://myTestPlatform',
        platformIdentifier: PlatformIdentifier.Openaev,
        globalServiceInstanceId: 'test-global-service-instance-id',
      });

      expect(html).not.toContain('OpenCTI');
    });
    it('should render text conditionally for free trials admin mail', async () => {
      const html = await renderEmail('admin_saas_instance_requested', {
        organizationName: 'myorga',
        userName: 'firstName lastName',
        userEmail: 'user.email',
        region: 'Test region',
        activitySector: 'Test ActivitySector',
        useCase: 'Test UseCase',
        platformIdentifier: PlatformIdentifier.Openaev,
        deploymentType: 'Trial',
      });

      expect(html).toContain('openaev-trials');
    });
  });
  describe('edge cases', () => {
    it('should handle empty string values gracefully', async () => {
      const html = await renderEmail('organization_pending_user_digest', {
        adminName: 'Admin',
        adminEmail: 'admin@test.com',
        organizationName: 'Filigran',
        users: [
          buildDigestUser({
            firstName: '',
            lastName: 'Smith',
            email: 'user@test.com',
          }),
        ],
        userCount: 1,
        requestLabel: 'request',
      });
      expect(html).toContain('Smith');
      expect(html).toContain('user@test.com');
    });

    it('should escape special characters in user data within {{#each}}', async () => {
      const html = await renderEmail('organization_pending_user_digest', {
        adminName: 'Admin',
        adminEmail: 'admin@test.com',
        organizationName: 'Filigran',
        users: [
          buildDigestUser({
            firstName: '<b>Bold</b>',
            lastName: 'User',
            email: 'bold@test.com',
          }),
        ],
        userCount: 1,
        requestLabel: 'request',
      });
      expect(html).not.toContain('<b>Bold</b>');
      expect(html).toContain('&lt;b&gt;Bold&lt;/b&gt;');
    });

    it('should handle many users in the list', async () => {
      const users = Array.from({ length: 50 }, (_, i) =>
        buildDigestUser({
          firstName: `First${i}`,
          lastName: `Last${i}`,
          email: `user${i}@test.com`,
        })
      );
      const html = await renderEmail('organization_pending_user_digest', {
        adminName: 'Admin',
        adminEmail: 'admin@test.com',
        organizationName: 'Filigran',
        users,
        userCount: 50,
        requestLabel: 'requests',
      });
      const actionRowCount = (html.match(/>\s*Approve\s*</g) || []).length;
      expect(actionRowCount).toBe(50);
      expect(html).toContain('First0');
      expect(html).toContain('First49');
    });
  });

  describe('pending user action links', () => {
    const organizationId = '11111111-1111-1111-1111-111111111111';
    const userId = '22222222-2222-2222-2222-222222222222';

    const buildLinks = () => ({
      approveLink: buildPendingUserActionLink({
        action: 'approve',
        organizationId,
        userId,
      }),
      denyLink: buildPendingUserActionLink({
        action: 'deny',
        organizationId,
        userId,
      }),
    });

    it.each`
      action       | typeName          | rawId
      ${'approve'} | ${'Organization'} | ${organizationId}
      ${'approve'} | ${'User'}         | ${userId}
      ${'deny'}    | ${'Organization'} | ${organizationId}
      ${'deny'}    | ${'User'}         | ${userId}
    `(
      'should encode the $typeName id as a global id for action "$action"',
      ({ action, typeName, rawId }) => {
        const link = buildPendingUserActionLink({
          action,
          organizationId,
          userId,
        });

        const searchParams = new URL(link).searchParams;
        const param =
          typeName === 'Organization' ? 'organization_id' : 'user_id';

        expect(searchParams.get('action')).toBe(action);
        expect(searchParams.get(param)).toBe(toGlobalId(typeName, rawId));
      }
    );

    it('should point to the handle-pending-user redirect route', () => {
      const { approveLink } = buildLinks();

      expect(new URL(approveLink).pathname).toBe(
        '/redirect/handle-pending-user'
      );
    });

    it('should percent-encode the base64 padding of global ids', () => {
      const { approveLink } = buildLinks();

      expect(approveLink).not.toContain('=&');
      expect(approveLink).toContain('%3D');
    });

    it('should only differ by the action query param between approve and deny', () => {
      const { approveLink, denyLink } = buildLinks();

      expect(approveLink.replace('action=approve', 'action=deny')).toBe(
        denyLink
      );
    });

    it('should render one action row per pending user with its own links', async () => {
      const users = [
        { firstName: 'John', lastName: 'Doe', email: 'john@test.com' },
        { firstName: 'Jane', lastName: 'Smith', email: 'jane@test.com' },
        { firstName: 'Jack', lastName: 'Brown', email: 'jack@test.com' },
      ].map((user, index) => ({
        ...user,
        approveLink: buildPendingUserActionLink({
          action: 'approve',
          organizationId,
          userId: `${index}-${userId}`,
        }),
        denyLink: buildPendingUserActionLink({
          action: 'deny',
          organizationId,
          userId: `${index}-${userId}`,
        }),
      }));

      const html = await renderEmail('organization_pending_user_digest', {
        adminName: 'Admin',
        adminEmail: 'admin@test.com',
        organizationName: 'Filigran',
        users,
        userCount: users.length,
        requestLabel: 'requests',
      });

      // Handlebars HTML-escapes `&` and `=` within the double-stash query
      // string (e.g. `action=approve` becomes `action&#x3D;approve`), so
      // decode entities before comparing against the raw links.
      const decodedHtml = html.replace(/&amp;/g, '&').replace(/&#x3D;/g, '=');

      expect(decodedHtml.match(/action=approve/g)).toHaveLength(users.length);
      expect(decodedHtml.match(/action=deny/g)).toHaveLength(users.length);
      expect(html.match(/>\s*Approve\s*</g)).toHaveLength(users.length);
      expect(html.match(/>\s*Deny\s*</g)).toHaveLength(users.length);

      users.forEach((user) => {
        expect(decodedHtml).toContain(`href="${user.approveLink}"`);
        expect(decodedHtml).toContain(`href="${user.denyLink}"`);
      });
    });

    it('should not render any action row when there is no pending user', async () => {
      const html = await renderEmail('organization_pending_user_digest', {
        adminName: 'Admin',
        adminEmail: 'admin@test.com',
        organizationName: 'Filigran',
        users: [],
        userCount: 0,
        requestLabel: 'requests',
      });

      expect(html).not.toContain('handle-pending-user');
      expect(html).not.toContain('Approve');
    });
  });

  describe('sendMail', () => {
    it('should enqueue a job via PgBossProducer when queue processing is enabled', async () => {
      vi.mocked(config.get).mockReturnValue(true);

      const mockSend = vi
        .spyOn(producer.PgBossProducer, 'send')
        .mockResolvedValue('fake-job-id');

      await sendMail({
        to: 'test@example.com',
        template: 'welcome',
        params: {},
      });

      expect(mockSend).toHaveBeenCalledOnce();
      expect(mockSend).toHaveBeenCalledWith('mail.send', {
        to: 'test@example.com',
        template: 'welcome',
        params: {},
      });
    });

    it('should NOT enqueue a job when queue processing is disabled', async () => {
      vi.mocked(config.get).mockReturnValue(false);

      const mockSend = vi
        .spyOn(producer.PgBossProducer, 'send')
        .mockResolvedValue('fake-job-id');

      await sendMail({
        to: 'test@example.com',
        template: 'welcome',
        params: {},
      });

      expect(mockSend).not.toHaveBeenCalled();
    });
  });
});
