import config from 'config';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { PlatformIdentifier } from '../__generated__/resolvers-types';
import * as producer from '../thirdparty/pgboss/producer';
import { clearTemplateCache, renderEmail, sendMail } from './mail-service';
import { templateSubjects } from './mail-template/mail';

vi.mock('config', async (importOriginal) => {
  const mod = await importOriginal<{ default: typeof config }>();
  return {
    default: {
      get: vi.fn(mod.default.get.bind(mod.default)),
      has: mod.default.has.bind(mod.default),
    },
  };
});

describe('renderEmail', () => {
  afterEach(() => {
    clearTemplateCache();
  });

  describe('template loading', () => {
    it('should render a template file and return html', async () => {
      const html = await renderEmail('welcome', {});
      expect(html).toBeTruthy();
      expect(html).toContain('Welcome to XTM Hub');
    });

    it('should cache templates on subsequent calls', async () => {
      const html1 = await renderEmail('welcome', {});
      const html2 = await renderEmail('welcome', {});
      expect(html1).toBe(html2);
    });
  });

  describe('variable substitution', () => {
    it('should replace simple variables', async () => {
      const html = await renderEmail('new_user_organization', {
        organizationName: 'Filigran',
        userName: 'Alice',
        invitedName: 'Bob',
      });
      expect(html).toContain('Filigran');
      expect(html).toContain('Bob');
    });

    it('should inject base_url_front and contactEmail automatically', async () => {
      const html = await renderEmail('welcome', {});
      expect(html).not.toContain('{{ base_url_front }}');
      expect(html).not.toContain('{{ contactEmail }}');
      expect(html).toContain('xtm-hub-support@filigran.io');
    });

    it('should use template subject for title and aria-label', async () => {
      const params = {
        organizationName: 'Filigran',
        userName: 'Alice',
        invitedName: 'Bob',
      };
      const expectedTitle = templateSubjects.new_user_organization(params);
      const escapedExpectedTitle = expectedTitle.replaceAll("'", '&#x27;');

      const html = await renderEmail('new_user_organization', params);

      expect(html).toContain(`<title>${escapedExpectedTitle}</title>`);
      expect(html).toContain(`aria-label="${escapedExpectedTitle}"`);
    });
  });

  describe('hTML escaping', () => {
    it('should escape HTML in double-brace variables by default', async () => {
      const html = await renderEmail('new_user_organization', {
        organizationName: '<script>alert("xss")</script>',
        userName: 'Alice',
        invitedName: 'Bob',
      });
      expect(html).not.toContain('<script>alert("xss")</script>');
      expect(html).toContain('&lt;script&gt;');
    });
  });

  describe('{{#each}} loops', () => {
    it('should render a list of users in organization_pending_user_digest', async () => {
      const html = await renderEmail('organization_pending_user_digest', {
        adminName: 'Admin',
        organizationName: 'Filigran',
        users: [
          { firstName: 'John', lastName: 'Doe', email: 'john@test.com' },
          { firstName: 'Jane', lastName: 'Smith', email: 'jane@test.com' },
        ],
        userCount: 2,
        requestLabel: 'requests',
      });
      expect(html).toContain('John');
      expect(html).toContain('Doe');
      expect(html).toContain('john@test.com');
      expect(html).toContain('Jane');
      expect(html).toContain('Smith');
      expect(html).toContain('jane@test.com');
      // Should have <li> elements generated by the {{#each}} loop
      expect(html).toContain('<li>');
    });

    it('should render an empty list when users array is empty', async () => {
      const html = await renderEmail('organization_pending_user_digest', {
        adminName: 'Admin',
        organizationName: 'Filigran',
        users: [],
        userCount: 0,
        requestLabel: 'requests',
      });
      expect(html).toContain('Admin');
      expect(html).not.toContain('<li>');
    });

    it('should render a single user correctly', async () => {
      const html = await renderEmail('organization_pending_user_digest', {
        adminName: 'Admin',
        organizationName: 'Filigran',
        users: [
          { firstName: 'Solo', lastName: 'User', email: 'solo@test.com' },
        ],
        userCount: 1,
        requestLabel: 'request',
      });
      const liCount = (html.match(/<li>/g) || []).length;
      expect(liCount).toBe(1);
      expect(html).toContain('Solo');
      expect(html).toContain('solo@test.com');
    });
  });

  describe('{{#if}} tests', () => {
    it('should render text conditionally for free trials', async () => {
      const html = await renderEmail('free_trial_registered', {
        firstName: 'User',
        platformUrl: 'http://myTestPlatform',
        platformIdentifier: PlatformIdentifier.Openaev,
        globalServiceInstanceId: 'test-global-service-instance-id',
      });

      expect(html).not.toContain('OpenCTI');
    });
    it('should render text conditionally for free trials admin mail', async () => {
      const html = await renderEmail('admin_saas_instance_requested', {
        organizationName: 'myorga',
        userName: 'firstName lastName',
        userEmail: 'user.email',
        region: 'Test region',
        activitySector: 'Test ActivitySector',
        useCase: 'Test UseCase',
        platformIdentifier: PlatformIdentifier.Openaev,
        deploymentType: 'Trial',
      });

      expect(html).toContain('openaev-trials');
    });
  });
  describe('edge cases', () => {
    it('should handle empty string values gracefully', async () => {
      const html = await renderEmail('organization_pending_user_digest', {
        adminName: 'Admin',
        organizationName: 'Filigran',
        users: [{ firstName: '', lastName: 'Smith', email: 'user@test.com' }],
        userCount: 1,
        requestLabel: 'request',
      });
      expect(html).toContain('Smith');
      expect(html).toContain('user@test.com');
    });

    it('should escape special characters in user data within {{#each}}', async () => {
      const html = await renderEmail('organization_pending_user_digest', {
        adminName: 'Admin',
        organizationName: 'Filigran',
        users: [
          {
            firstName: '<b>Bold</b>',
            lastName: 'User',
            email: 'bold@test.com',
          },
        ],
        userCount: 1,
        requestLabel: 'request',
      });
      expect(html).not.toContain('<b>Bold</b>');
      expect(html).toContain('&lt;b&gt;Bold&lt;/b&gt;');
    });

    it('should handle many users in the list', async () => {
      const users = Array.from({ length: 50 }, (_, i) => ({
        firstName: `First${i}`,
        lastName: `Last${i}`,
        email: `user${i}@test.com`,
      }));
      const html = await renderEmail('organization_pending_user_digest', {
        adminName: 'Admin',
        organizationName: 'Filigran',
        users,
        userCount: 50,
        requestLabel: 'requests',
      });
      const liCount = (html.match(/<li>/g) || []).length;
      expect(liCount).toBe(50);
      expect(html).toContain('First0');
      expect(html).toContain('First49');
    });
  });
  describe('sendMail', () => {
    it('should enqueue a job via PgBossProducer when queue processing is enabled', async () => {
      vi.mocked(config.get).mockReturnValue(true);

      const mockSend = vi
        .spyOn(producer.PgBossProducer, 'send')
        .mockResolvedValue('fake-job-id');

      await sendMail({
        to: 'test@example.com',
        template: 'welcome',
        params: {},
      });

      expect(mockSend).toHaveBeenCalledOnce();
      expect(mockSend).toHaveBeenCalledWith('mail.send', {
        to: 'test@example.com',
        template: 'welcome',
        params: {},
      });
    });

    it('should NOT enqueue a job when queue processing is disabled', async () => {
      vi.mocked(config.get).mockReturnValue(false);

      const mockSend = vi
        .spyOn(producer.PgBossProducer, 'send')
        .mockResolvedValue('fake-job-id');

      await sendMail({
        to: 'test@example.com',
        template: 'welcome',
        params: {},
      });

      expect(mockSend).not.toHaveBeenCalled();
    });
  });
});
