enum PlatformContract {
  CE
  EE
}

type RegisteredPlatform implements Node {
  id: ID!
  url: String!
  title: String!
  contract: PlatformContract!
  platform_id: String!
  version: String
}

input PlatformInput {
  id: ID!
  url: String!
  title: String!
  contract: PlatformContract!
  version: String
}

enum PlatformIdentifier {
  opencti
  openaev
}

input RegisterPlatformInput {
  organizationId: ID!
  platform: PlatformInput!
  identifier: PlatformIdentifier!
}

input CanUnregisterPlatformInput {
  platformId: String!
}

type RegistrationResponse {
  token: String!
}

enum PlatformRegistrationStatus {
  registered
  unregistered
  never_registered
}

input IsPlatformRegisteredInput {
  platformId: String!
}

type IsPlatformRegisteredOrganization implements Node {
  id: ID!
}

type IsPlatformRegisteredResponse {
  status: PlatformRegistrationStatus!
  platformTitle: String
  organization: IsPlatformRegisteredOrganization
}

type CanUnregisterResponse {
  isPlatformRegistered: Boolean!
  isAllowed: Boolean
  isInOrganization: Boolean
  organizationId: ID
}

input UnregisterPlatformInput {
  platformId: String!
}

enum PlatformRegistrationConnectivityStatus {
  active
  inactive
}

input RefreshPlatformRegistrationConnectivityStatusInput {
  platformId: String!
  token: String!
  platformVersion: String!
}

type RefreshPlatformRegistrationConnectivityStatusResponse {
  status: PlatformRegistrationConnectivityStatus!
}

type RefreshUserPlatformTokenResponse {
  token: String!
}

input RegisteredPlatformsInput {
  identifier: PlatformIdentifier!
}

type Query {
  isPlatformRegistered(
    input: IsPlatformRegisteredInput!
  ): IsPlatformRegisteredResponse! @auth
  canUnregisterPlatform(
    input: CanUnregisterPlatformInput!
  ): CanUnregisterResponse! @auth
  registeredPlatforms(input: RegisteredPlatformsInput!): [RegisteredPlatform!]!
    @auth
  platformAssociatedOrganization(platformId: String!): Organization! @auth
}

type Mutation {
  registerPlatform(input: RegisterPlatformInput!): RegistrationResponse! @auth
  unregisterPlatform(input: UnregisterPlatformInput): Success! @auth
  refreshUserPlatformToken: RefreshUserPlatformTokenResponse! @auth
  # Warning ! Used by OpenCTI
  refreshPlatformRegistrationConnectivityStatus(
    input: RefreshPlatformRegistrationConnectivityStatusInput!
  ): RefreshPlatformRegistrationConnectivityStatusResponse!
}
