enum PlatformContract {
  CE
  EE
}

type OpenCTIPlatform implements Node {
  id: ID!
  url: String!
  title: String!
  contract: PlatformContract!
  platform_id: String!
}

input PlatformInput {
  id: ID!
  url: String!
  title: String!
  contract: PlatformContract!
}

enum PlatformIdentifier {
  opencti
}

input RegisterPlatformInput {
  organizationId: ID!
  platform: PlatformInput!
  identifier: PlatformIdentifier!
}

input CanUnregisterPlatformInput {
  platformId: String!
}

type RegistrationResponse {
  token: String!
}

enum PlatformRegistrationStatus {
  registered
  unregistered
  never_registered
}

input IsPlatformRegisteredInput {
  platformId: String!
}

type IsPlatformRegisteredOrganization implements Node {
  id: ID!
}

type IsPlatformRegisteredResponse {
  status: PlatformRegistrationStatus!
  organization: IsPlatformRegisteredOrganization
}

type CanUnregisterResponse {
  isPlatformRegistered: Boolean!
  isAllowed: Boolean
  isInOrganization: Boolean
  organizationId: ID
}

input UnregisterOpenCTIPlatformInput {
  platformId: String!
}

input OpenCTIPlatformRegistrationStatusInput {
  platformId: String!
  token: String!
}

enum OpenCTIPlatformRegistrationStatus {
  active
  inactive
}

type OpenCTIPlatformRegistrationStatusResponse {
  status: OpenCTIPlatformRegistrationStatus!
}

type RefreshUserPlatformTokenResponse {
  token: String!
}

type Query {
  isPlatformRegistered(
    input: IsPlatformRegisteredInput!
  ): IsPlatformRegisteredResponse! @auth
  canUnregisterPlatform(
    input: CanUnregisterPlatformInput!
  ): CanUnregisterResponse! @auth
  openCTIPlatforms: [OpenCTIPlatform!]! @auth
  openCTIPlatformRegistrationStatus(
    input: OpenCTIPlatformRegistrationStatusInput!
  ): OpenCTIPlatformRegistrationStatusResponse!
  openCTIPlatformAssociatedOrganization(platformId: String!): Organization!
    @auth
}

type Mutation {
  registerPlatform(input: RegisterPlatformInput!): RegistrationResponse! @auth
  unregisterOpenCTIPlatform(input: UnregisterOpenCTIPlatformInput): Success!
    @auth
  refreshUserPlatformToken: RefreshUserPlatformTokenResponse! @auth
}
