enum PlatformRegion {
  europe
  us
  apac
}

enum DeploymentType {
  trial
}

enum DeploymentRequestStatus {
  QUEUED
  PENDING
  PROVISIONING
  ACTIVE
  EXPIRED
  FAILED
  CANCELLED
}

type DeploymentRequest implements Node {
  id: ID!
  platform_identifier: PlatformIdentifier!
  region: PlatformRegion!
  type: DeploymentType!
  job_title: String
  activity_sector: String
  use_case: String
  start_date: Date
  end_date: Date
  status: DeploymentRequestStatus!
}

type PlatformDeploymentRequest {
  id: ID!
  platform_identifier: PlatformIdentifier!
  region: PlatformRegion!
  type: DeploymentType!
  platform_token: String!
  status: DeploymentRequestStatus!
  start_date: Date
  end_date: Date
  job_title: String
  activity_sector: String
  use_case: String
  organization_name: String!
  organization_domains: [String!]
  requester_email: String!
  product_service_instance_id: String
  failure_reason: String
}

input CreateDeploymentRequestInput {
  platform_identifier: PlatformIdentifier!
  region: PlatformRegion!
  type: DeploymentType!
  job_title: String
  activity_sector: String
  use_case: String
  status: DeploymentRequestStatus
}

input UpdateDeploymentRequestInput {
  id: ID!
  status: DeploymentRequestStatus
  start_date: Date
  end_date: Date
  product_service_instance_id: String
  failure_reason: String
}

enum DeploymentRequestFilterKey {
  region
  type
  status
  platform_identifier
}

input DeploymentRequestFilter {
  key: DeploymentRequestFilterKey
  value: [String!]!
}

type DeploymentRequestEdge {
  cursor: String!
  node: PlatformDeploymentRequest!
}

type DeploymentRequestConnection {
  totalCount: Int!
  edges: [DeploymentRequestEdge!]!
  pageInfo: PageInfo!
}

type DeploymentAvailability {
  region: PlatformRegion!
  availableCount: Int!
}

extend type Query {
  deploymentRequests(
    first: Int!
    after: ID
    filters: [DeploymentRequestFilter!]
  ): DeploymentRequestConnection! @system_token
  deploymentRequestsAvailable(
    platformIdentifier: PlatformIdentifier
  ): [DeploymentAvailability!]!
    @auth(requires: [ADMINISTRATE_ORGANIZATION, MANAGE_PLATFORM_REGISTRATION])
}

extend type Mutation {
  createDeploymentRequest(
    input: CreateDeploymentRequestInput
  ): DeploymentRequest!
    @auth(requires: [ADMINISTRATE_ORGANIZATION, MANAGE_PLATFORM_REGISTRATION])
  updateDeploymentRequest(
    input: UpdateDeploymentRequestInput!
  ): PlatformDeploymentRequest! @system_token
}
