mutation AddUsersToBundleGroups(
  $serviceInstanceId: ServiceInstanceId!
  $input: AddUsersToBundleGroupsInput!
) {
  addUsersToBundleGroups(serviceInstanceId: $serviceInstanceId, input: $input) {
    user {
      id
      email
    }
    groups {
      platformIdentifier
      name
    }
  }
}

mutation RemoveUsersFromBundleGroups(
  $serviceInstanceId: ServiceInstanceId!
  $userIds: [UserId!]!
) {
  removeUsersFromBundleGroups(
    serviceInstanceId: $serviceInstanceId
    userIds: $userIds
  )
}
