type UseCase implements Node {
    id: ID!
    name: String!
    color: String!
}

enum UseCaseOrdering {
    name
    color
}

type UseCaseEdge {
    cursor: String!
    node: UseCase!
}

type UseCaseConnection {
    totalCount: Int!
    edges: [UseCaseEdge!]!
    pageInfo: PageInfo!
}

input AddUseCaseInput {
    name: String!
    color: String!
}

input EditUseCaseInput {
    name: String
    color: String
}

type Query {
    useCases(
        first: Int!
        after: ID
        orderBy: UseCaseOrdering!
        orderMode: OrderingMode!
        searchTerm: String
        documentType: String
    ): UseCaseConnection
    #    // TODO : Still Used ?
    useCase(id: ID!): UseCase @auth
}

type Mutation {
    addUseCase(input: AddUseCaseInput!): UseCase! @auth(requires: [BYPASS])
    editUseCase(id: ID!, input: EditUseCaseInput!): UseCase! @auth(requires: [BYPASS])
    deleteUseCase(id: ID!): UseCase! @auth(requires: [BYPASS])
}
