name: dockerbuild

on:
  push:
    branches:
      - 'main'
    paths:
    - 'portal-api/**'
    - 'portal-front/**'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'
    paths:
    - 'portal-api/**'
    - 'portal-front/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - path: portal-api
          - path: portal-front
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
            cd ${{ matrix.path }}
            yarn install
      - name: Lint the code
        run: |
          cd ${{ matrix.path }}
          yarn lint
      - name: Build the project
        run: |
          cd ${{ matrix.path }}
          yarn build
