name: Run XTM Hub CI/CD
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "development"
    tags:
      - "v*"
  pull_request:
    branches:
      - "main"
      - "development"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:

  build-apps:
    runs-on: ubuntu-latest
    container: node:24.8-alpine3.22
    timeout-minutes: 10
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install build dep
        run: apk add --no-cache docker-cli git python3 make g++ libc6-compat tar
      - name: Corepack Enable
        run: corepack enable
      - name: Cache Next and Yarn
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/apps/portal-front/.next/cache
            ${{ github.workspace }}/.yarn
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push portal image
        run: |
          yarn install --immutable
          cd apps/portal-front
          yarn build 
          ls -la
          cd ../portal-api 
          yarn build
      - name: Upload artifact front
        uses: actions/upload-artifact@v4
        with:
          name: build-context-front-${{ github.event.pull_request.number || github.ref }}
          path: |
            apps/portal-front/.next
          include-hidden-files: true
          overwrite: true
          retention-days: 3
          if-no-files-found: error
      - name: Upload artifact dist api
        uses: actions/upload-artifact@v4
        with:
          name: build-context-api-dist-${{ github.event.pull_request.number || github.ref }}
          path: apps/portal-api/dist
          overwrite: true
          retention-days: 3
          if-no-files-found: error
      - name: Upload artifact node_modules api
        uses: actions/upload-artifact@v4
        with:
          name: build-context-api-node_modules-${{ github.event.pull_request.number || github.ref }}
          path: node_modules
          overwrite: true
          retention-days: 3
          if-no-files-found: error
      - name: Upload artifact config directory
        uses: actions/upload-artifact@v4
        with:
          name: build-context-api-config-${{ github.event.pull_request.number || github.ref }}
          path: apps/portal-api/config
          overwrite: true
          retention-days: 3
          if-no-files-found: error

  juste-pour-voir:
    runs-on: ubuntu-latest
    needs: build-apps
    container: node:24.8-alpine3.22
    timeout-minutes: 10
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download all artifacts for front
        uses: actions/download-artifact@v5
        with:
          pattern: build-context-front*
          path: apps/portal-front/.next
      - name: Download dist artifacts for api
        uses: actions/download-artifact@v5
        with:
          pattern: build-context-api-dist*
          path: apps/portal-api/dist
          merge-multiple: true
      - name: Download config artifacts for api
        uses: actions/download-artifact@v5
        with:
          pattern: build-context-api-config*
          path: config
          merge-multiple: true
      - name: Download node_modules artifacts for api
        uses: actions/download-artifact@v5
        with:
          pattern: build-context-api-node_modules*
          path: node_modules
          merge-multiple: true
      - name: List downloaded artifacts
        run: |
          echo "=== Structure des artifacts téléchargés ==="
          cd apps
          ls -la
          echo "=== portal-front ==="
          cd portal-front
          ls -la
          echo "=== FRONT .next==="
          ls -la .next
          echo "=== API==="
          cd ../..
          ls -la apps/portal-api
          echo "=== API dist==="
          ls -la apps/portal-api/dist
          echo "=== API config==="
          ls -la apps/portal-api/config
      - name: Je le démarre pour voir
        run: |
          node apps/portal-api/dist/index.js
