name: Run XTM Hub CI/CD
on:
  push:
    branches:
      - 'main'
    paths:
      - 'portal-api/**'
      - 'portal-front/**'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'portal-api/**'
      - 'portal-front/**'

jobs:
  build-deps:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: true
      matrix:
        include:
        - image: portal-front
        - image: portal-api
    outputs:
      docker-tags: ${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
      docker-labels: ${{ steps.meta.outputs.labels }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker meta deps
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: filigran/${{ matrix.image }}-deps
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Build and push portal deps
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.image }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=registry,ref=filigran/${{ matrix.image }}-deps:main
            type=registry,ref=filigran/${{ matrix.image }}-deps:${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
          target: deps
  backend-tests:
    needs: build-deps
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Launch docker compose
        uses: hoverkraft-tech/compose-action@v2.0.2
        env:
          IMAGE_TAGS: ${{ needs.build-deps.outputs.docker-tags }}
        with:
          compose-file: "./xtm-hub-dev/docker-compose-ci.yml"
          services: "portal-e2e-tests"
      - name: Build and push portal-api
        uses: docker/build-push-action@v5
        with:
          context: portal-api
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ needs.build-deps.outputs.docker-tags }}
          labels: ${{ needs.build-deps.outputs.docker-labels }}
          image: filigran/portal-api
          cache-from: xtm-hub-dev-portal-api
      - name: Build and push portal-front
        uses: docker/build-push-action@v5
        with:
          context: portal-front
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ needs.build-deps.outputs.docker-tags }}
          labels: ${{ needs.build-deps.outputs.docker-labels }}
          cache-from: xtm-hub-dev-portal-front
      - name: Build and push portal-e2e-tests
        uses: docker/build-push-action@v5
        with:
          context: portal-e2e-tests
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ needs.build-deps.outputs.docker-tags }}
          labels: ${{ needs.build-deps.outputs.docker-labels }}
          cache-from: xtm-hub-dev-portal-e2e-tests
      - name: restart deployment on staging
        if: github.event_name != 'pull_request'
        run: kubectl --server=https://api.staging.eu-west.filigran.io --token=${{ secrets.K8S_TOKEN }} -n wip-cloudportal rollout restart deployment
