name: Helm lint, test, package and publish

on:
  push:
    branches: ["main"]

jobs:
  helm-suite:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: "Helm publish"
      uses: mbovo/action-helm-artifactory@v1.0.5
      with:
        action: "push"
      env:
        CHART_DIR: chart
        ARTIFACTORY_URL: https://filigran.jfrog.io/artifactory/charts-helm/
        ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
        ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
