name: Send Release Email

on:
  workflow_dispatch:

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Get Last Release
        id: last_release
        uses: actions/github-script@v6
        with:
          script: |
            const { data: release } = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            core.setOutput("release_name", release.name);
            core.setOutput("release_tag", release.tag_name);
            core.setOutput("release_body", release.body);
            core.setOutput("release_url", release.html_url);
      - name: Send Email
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: ${{ secrets.SMTP_ADDRESS }}
          server_port: 465
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "[XTM Hub] Version: ${{ steps.last_release.outputs.release_tag }}"
          to: "all-employees@filigran.io"
          from: "XTM Hub Team"
          convert_markdown: true
          html_body:
           🔔 DING DING 🔔
            </br> </br>
           Dear Filigran team,
            </br> </br>
           The Engineering team is glad to inform you that <a href=${{steps.last_release.outputs.release_url}} target="_blank"> XTM Hub ${{ steps.last_release.outputs.release_tag }}</a> has been released 🥳!
           </br> </br>
           <h2>Release Note</h2>
            
           ${{ steps.last_release.outputs.release_body }}
            
            </br></br>
            Feel free to reach out to the <a href="mailto:engineering-product-management@filigran.io">product management team</a> to get more information 🚀
            </br></br>
           Thank you all for your efforts in serving our community and our customers 🎀
