name: Renovate
on:
  schedule:
    - cron: "0 11 * * *"
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Renovate
        run: npx renovate FiligranHQ/scred-project