name: Run Backend Tests

on:
  push:
    branches:
      - 'main'
    paths:
      - 'portal-api/**'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'portal-api/**'

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - path: portal-api
    container: node:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      - name: Install Docker Compose
        run: |
          apt-get update
          apt-get install -y docker-compose
      - name: Start local environment with Docker Compose
        run: | 
          cd ./xtm-hub-dev
          docker-compose up --detach
      - name: Init Test DB
        run: |
          cd ./xtm-hub-dev
          docker-compose exec -T portal-api yarn init-db-test
      - name: Launch tests backend
        run: |
          cd ./xtm-hub-dev
          docker-compose exec -T portal-api yarn test
