name: Run Backend Tests

on:
  push:
    branches:
      - 'main'
    paths:
      - 'portal-api/**'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'portal-api/**'

jobs:
  backend-tests:
    env:
      HOSTNAME: 0.0.0.0
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - path: portal-api
    container: node:latest
    services:
      portal-postgres:
        image: postgres:16.0
        volumes:
          - pgdata:/data/postgres
        environment:
          - POSTGRES_USER=portal
          - POSTGRES_PASSWORD=portal-password
          - POSTGRES_DB=cloud-portal
          - PGDATA=/data/postgres
        restart: unless-stopped
        ports:
          - "5432:5432"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t server-node .

      - name: Run Docker container
        run: docker run -d -p 4001:4001 --node server-node-container server-node

      - name: Check container is running
        run: docker ps
      - name: Init Test DB
        run: |
          cd ${{ matrix.path }}
          yarn init-db-test
      - name: Start test backend
        run: |
          cd ${{ matrix.path }}
          yarn start-test &
      - name: Launch tests backend
        run: |
          cd ${{ matrix.path }}
          yarn test
