name: Run E2E Tests

on:
  push:
    branches:
      - 'main'
    paths:
      - 'portal-api/**'
      - 'portal-front/**'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'portal-api/**'
      - 'portal-front/**'

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Docker Compose
        working-directory: portal-api
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - name: Launch E2E Tests
        working-directory: xtm-hub-dev
        run: docker-compose -f docker-compose-ci.yml run playwright-tests
