version: '3'
services:
  portal-dev-postgres:
    container_name: portal-dev-postgres
    image: postgres:16.0
    volumes:
      - pgdata:/data/postgres
    environment:
      - POSTGRES_USER=portal
      - POSTGRES_PASSWORD=portal-password
      - POSTGRES_DB=cloud-portal
      - PGDATA=/data/postgres
    restart: unless-stopped
    ports:
      - 5432:5432

volumes:
  pgdata:
    driver: local