export enum ErrorCode {
  IsOpenCTIPlatformRegisteredUnknownError = 'IS_OPENCTI_PLATFORM_REGISTERED_UNKNOWN_ERROR',
  CanUnregisterOpenCTIPlatformUnknownError = 'CAN_UNREGISTER_OPENCTI_PLATFORM_UNKNOWN_ERROR',
  RegisterOpenCTIPlatformUnknownError = 'REGISTER_OPENCTI_PLATFORM_UNKNOWN_ERROR',
  PlatformNotRegistered = 'PLATFORM_NOT_REGISTERED',
  InvalidImageUrl = 'INVALID_IMAGE_URL',
  InvalidServiceConfiguration = 'INVALID_SERVICE_CONFIGURATION',
  MissingCapabilityOnOrganization = 'MISSING_CAPABILITY_ON_ORGANIZATION',
  RegistrationOnAnotherOrganizationForbidden = 'REGISTRATION_ON_ANOTHER_ORGANIZATION_FORBIDDEN',
  ServiceContractNotFound = 'SERVICE_CONTRACT_NOT_FOUND',
  ServiceConfigurationNotFound = 'SERVICE_CONFIGURATION_NOT_FOUND',
  ServiceDefinitionNotFound = 'SERVICE_DEFINITION_NOT_FOUND',
  SubscriptionNotFound = 'SUBSCRIPTION_NOT_FOUND',
  UnregisterOpenCTIPlatformUnknownError = 'UNREGISTER_OPENCTI_PLATFORM_UNKNOWN_ERROR',
  UserIsNotInOrganization = 'USER_IS_NOT_IN_ORGANIZATION',
}
